### ISSUE TITLE
Procedure to install OpenBSD

### ISSUE THREAD

**Issue by erowley** [churchers/vm-bhyve#102]
Is this the procedure ?

1. pkg install vm-bhyve
2. zfs create pool/vm
3. echo 'vm_enable="YES"' >> /etc/rc.conf
4. echo 'vm_dir="zfs:pool/vm"' >> /etc/rc.conf
5. vm init
6. cp /usr/local/share/examples/vm-bhyve/* /mountpoint/for/pool/vm/.templates/
7. vm switch create public
8. vm switch add public em0
9. vm iso http://mirror.jmu.edu/pub/OpenBSD/5.9/amd64/install59.iso
10. vm create -t openbsd myopenbsd
11. vm [-f] install myopenbsd install59.iso
12. vm console myopenbsd

**Comment by churchers** [comment]
That looks about right. Are you having a problem getting it to work?

**Comment by erowley** [comment]
Correct, I am having a problem getting it to work. At step 11, this is the result I get:

root@wv1-r0r02-s02:~ # vm -f install myopenbsd install59.iso
VM:myopenbsd is not created.

This is occurring with the vm-bhyve 1.1.1 from ports on FreeBSD 11 alpha 6.

**Comment by churchers** [comment]
Hmm, I can't see any obvious reason why you should be getting that error. Can you post the log of the last run attempt from /path/to/the/vm/vm-bhyve.log (everything after 'initialising'), and also the guest config from myopenbsd.conf.

**Comment by erowley** [comment]
Jul 15 18:29:32: grub requested but sysutils/grub2-bhyve not installed?

^ that's it! How silly of me.

I'm surprised that grub2-bhyve was not automatically included as a prerequisite to the port.

After installing grub2-bhyve, it now works.

**Comment by churchers** [comment]
Cool that you got it working.
I don't know why you got that error, it shouldn't have tried to start byyve at all if the grub-bhyve loader didn't run. I'll give it a go and see if there's some error case I'm not catching.

I did consider adding dependencies to the port but I don't really want to force things to be installed if users don't want them - you don't need grub2-bhyve if you're only running BSD or UEFI guests.

It might be worth me looking at adding 'Linux support' and 'UEFI support' options to the port so it can pull in these dependencies if users want them. Once the UEFI port no longer installs gcc I may look at setting these by default, so users get Linux & UEFI out of the box with the package. Some users might not want these, but they aren't exactly big packages with dozens of their own dependencies.

**Comment by churchers** [comment]
Figured out why the error appears.
On shutdown, vm-bhyve still tries to destroy the bhyve vmm device even though it was never created. I've fixed this in GitHub, although it's not worth submitting an update to ports just yet as it's not really causing any problems, just a harmless error.

**Comment by artkiver** [comment]
> Cool that you got it working.
> I don't know why you got that error, it shouldn't have tried to start byyve at all if the grub-bhyve loader didn't run. I'll give it a go and see if there's some error case I'm not catching.
> 
> I did consider adding dependencies to the port but I don't really want to force things to be installed if users don't want them - you don't need grub2-bhyve if you're only running BSD or UEFI guests.
> 
> It might be worth me looking at adding 'Linux support' and 'UEFI support' options to the port so it can pull in these dependencies if users want them. Once the UEFI port no longer installs gcc I may look at setting these by default, so users get Linux & UEFI out of the box with the package. Some users might not want these, but they aren't exactly big packages with dozens of their own dependencies.

Per: https://wiki.freebsd.org/bhyve/OpenBSD

"As of FreeBSD 11.1-RELEASE, OpenBSD 5.9 amd64 and above can boot, install and run under bhyve’s native UEFI support (UEFI-GOP).

Note: All OpenBSD i386 releases must use grub2-bhyve as booting with i386 using UEFI is not supported.
"

Is there any reason why grub is being utilized by vm-bhyve rather given the above information on non-i386 guests?

Otherwise, seems like a neat project; I think it would be a candidate for getting merged into bhyveload if you wanted to get it off of github and take it upstream.
