### ISSUE TITLE
vm switch nat on fails to create reasonable pf-nat.conf

### ISSUE THREAD

**Issue by anteract** [churchers/vm-bhyve#103]
Docs say do this:
A $vm_dir/.config/pf-nat.conf file is created which contains pf nat rules for this bridge. We also automatically add an include statement to /etc/pf.conf pointing to this file.
Well, on my system, all that happens, but the contents of the file in .config/pf-nat.conf is exactly as follows:

    # vm-bhyve nat

Not really doing what we want.  IP gets assigned, the include gets added to pf.conf, etc., just nothing else in that .conf file.

Edit:  More digging in vm-switch.  Not seeing the lines added to the dnsmasq configs either.  Almost like its ignoring part of that function where it writes to these config files.

Someone smarter than me perhaps can fix this?  Please?

**Comment by churchers** [comment]
Hmm, not a problem I've come across before. Can you tell me what version of vm-bhyve you are using (vm version) and the contents of .config/system.conf (or .config/switch if you are using 1.0 or earlier).

**Comment by anteract** [comment]
vm-bhyve: Bhyve virtual machine management v1.1-p3 (build 101062)

.config/system.conf
switch_list="public"
ports_public="igb0"
console="tmux"
nat_public="yes"

The script added that last line, so that part is working.

**Comment by anteract** [comment]
Additional Note.  This part of switch::nat_init is the part that isn't firing, everything above and below it worked.  I typed this into the 2 different config files manually (replaced variables with proper labels) and it all works fine.  ~line 493 in vm-switch

        if [ "${_nat}" = "yes" -a -n "${_id}" ]; then
            _bnum=$(echo "${_id}" |awk -F'bridge' '{print $2}')
            _net24="172.16.${_bnum}"

            echo "nat on ${_gw} from {${_net24}.0/24} to any -> (${_gw})" >> "${vm_dir}/.config/pf-nat.conf"
            echo "" >> /usr/local/etc/dnsmasq.conf.bhyve
            echo "interface=${_id}" >> /usr/local/etc/dnsmasq.conf.bhyve
            echo "dhcp-range=${_net24}.10,${_net24}.254" >> /usr/local/etc/dnsmasq.conf.bhyve


Side note, you only reload pf, not dnsmasq after these changes.
2nd side note, make the dnsmasq.conf.bhyve changes an included file in dnsmasq.conf like you do in pf.conf.  works fine and less to fiddle with.  on mine the last line of dnsmasq.conf is this:
conf-file=/usr/local/etc/dnsmasq.conf.bhyve

**Comment by churchers** [comment]
If you run `vm switch list` does it show the correct bridge interface name under the `IDENT` column?
That block of code is inside an if statement that relies on two things

* `nat_{switchname}` being set to yes in the configuration file
* vm-bhyve being able to find the correct bridge interface on the system

If the correct bridge interface shows in the switch list, then I see no reason why it shouldn't be successfully finding the bridge, as it uses the same code. There's no easy way to tell if it's picking up the `nat_{switchname}` configuration setting, but I've not seen any other issues with reading 
configuration yet.

It's even more confusing that you say it assigns the IP address, as that is done in the same block of code. If you restart the host does it do the same thing?

Regarding the other note. I originally wrote config directly to `dnsmasq.conf` and restart both services. However in order for things to work correctly, vm-bhyve has to make fundamental changes to the configuration. These include things such as forcing it to only bind to the specified interfaces, and making sure it doesn't leak dns information from the host. Quite rightly users complained of vm-bhyve overwriting their configuration and suggested it would be better to provide the config and let the user enable. I could create an include, but I can't guarantee that would work as the user's existing configuration could be incompatible with the vm-bhyve configuration.

As DHCP isn't really a necessity for NAT (only the pf rule is really needed if you are happy assigning IP addresses in the guest manually). I decided to implement it the way it is currently. By default NAT works, but you need to manually assign IP addresses to the guest. If you want DHCP you can install the provided configuration file (which is mentioned when NAT is enabled), merge with your own, or even use a different DHCP service if you want.

**Comment by anteract** [comment]
This is the result of vm switch list
root@vm01:~ # vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         yes          igb0

To make it work, I added to the pf-nat.conf a single line
nat on igb0 from {172.16.0.0/24} to any -> (igb0)
 and added to dnsmasq.conf.bhyve
interface=bridge0
dhcp-range=172.16.0.10,172.16.0.254

It all works after I did that manually.  the bridge0 was set to IP 172.16.0.1 by the script.

vm switch nat public off , restart the server, vm switch nat public on and same result.
These settings did survive a reboot though if left "on"

As for the dnsmasq changes, point made, but it would be sweet if vm-bhyve worked more like Virtualbox in the network stuff.  i.e., just works.

**Comment by anteract** [comment]
Gets better...  and you can see this happen with the -xv command added to the vm script.
vm switch nat public on 
doesn't add those 3 lines

vm switch nat public off 
adds the 3 lines, and all is fine.
nat works/dhcp works, etc.
vm switch list says the NAT isn't there, but it is.

So, to make it work, vm switch nat public on then immediately vm switch nat public off, the if you want it to read right on the list of switches, vm switch nat public on again.

Guess technically it's still broken, since it will never remove the settings.

Freebsd 11.0-BETA1 if you were curious.

**Comment by churchers** [comment]
Think I've worked it out. I've (fairly) recently changed the configuration code so that rather than using `sysrc` all over the place, it loads the configuration file once during startup. 

It looks like the function to enable/disable nat is updating the configuration file, but then `switch::nat_init`, is picking up the old value, as the active configuration hasn't been reloaded.

A call to `config::core_load` at the top of the nat_init function should fix it.
