### ISSUE TITLE
utctime=NO not the same as utctime="NO"

### ISSUE THREAD

**Issue by anteract** [churchers/vm-bhyve#104]
bhyve uses a "-u" to tell the host to start the client in UTC time, this is the default, thats all good, and if you leave out the vm-bhyve command "utcdate", it should do the same thing.  It doesn't

This works
utcdate=NO
this doesn't
utcdate="NO"
utcdate=""

Someplace in vm-bhyve there is a "NO" with quotes or just quotes, and its kicking all the clients into UTC when I want them on local time, so the default in vm-bhyve is to force UTC, backward from the default in bhyve.

**Comment by churchers** [comment]
Can you show the following lines from the `vm-bhyve.log` log file for the 3 cases you have tried?

    Jul 25 12:00:37:  [utctime: no]

    Jul 25 12:00:37:  [bhyve options: -c 4 -m 2G -AHP]

**Comment by anteract** [comment]
Mistake above, the line that makes things work is:  utcdate="NO"
using Centos 7 Client, FBSD 11

Entries from log when it  "failed"
Jul 26 02:06:10:  [utctime: no]
Jul 26 02:06:13:  [bhyve options: -c 8 -m 16G -AHP -U 4a476d27-4af4-11e6-9c72-549f3518216e]

Entries from "works"
Jul 26 02:08:24:  [utctime: no]
Jul 26 02:08:28:  [bhyve options: -c 8 -m 16G -AHP -U 4a476d27-4af4-11e6-9c72-549f3518216e]

Yes, identical.  Any other thoughts?  Currently rebooting the entire machine to see if there is a creeping error in there.

**Comment by churchers** [comment]
Hmm, I'm not seeing the UTC option being specified to bhyve in either of those log entries?
If UTC time is being enabled, you should see `-u` on the end of the bhyve options string, as below:

    Jul 26 11:16:45:  [bhyve options: -c 2 -m 256M -AHP -U eef56d92-fca5-11e5-81b7-50e549369bc6 -u]

I did realise that spaces could cause a problem recently and added a fix on GitHub:

     Jul 26 11:19:39:  [utctime: no   ]
    Jul 26 11:19:42:  [bhyve options: -c 2 -m 256M -AHP -U eef56d92-fca5-11e5-81b7-50e549369bc6 -u]

I'll apply this fix to 1.1 and update ports along with the nat fix, although this doesn't appear to be relevant to your issue.

**Comment by churchers** [comment]
Just to clarify, from a vm-bhyve perspective, if you do not specify the `utctime` option, or set it to off/no, we run bhyve as default. If the `utctime` option is set to a positive value, we pass `-u`, which is visible in the log file.

`-u` is documented in bhyve as "RTC keept UTC time", so setting `utctime` in vm-bhyve tells the guest that the RTC is keeping UTC time.

If you see any situation where this is not happening as expected, post the setting from the config file, and the two log lines above, which should hopefully clearly show the `-u` setting being set when it shouldn't, or visa-versa.

**Comment by churchers** [comment]
I've also just realised you have `utcdate` in your first message, when the correct config option in vm-bhyve is `utctime`.

**Comment by anteract** [comment]
Yes, going back to the drawing board, I think with all the fiddling around I have confused myself somewhat.  Essentially what I am seeing is opposite of what I expect, but your logs show that vm-bhyve isn't sending the -u, so I need to figure out why my time is getting shifted 
local time is PDT, inside the client "date" command says PDT, but time shown is UTC.  ntpdate loaded at boot is going to do it for now, until I get more time to "experiment" properly.  Lets just close this for now, after reading the entire log entry I don't think it's anything vm-bhyve is doing.

**Comment by anteract** [comment]
Built a new 11 beta 1 server, on different hardware.
installed vm-bhyve  "master" using svn.
using basically the quick start, added a FreeBSD client
When it starts time is off 7 hours.
changed the .conf for that client, added a line:
utctime="YES"
the log files says:
Jul 26 19:47:42:  [bhyve options: -c 4 -m 16G -AHP -U e3fa75af-5398-11e6-9d2e-549f35182342 -u]

And the time is right (local time)

Removed the utctime="YES" and the time is off 7 hours.
Bhyve man page says:      -u          RTC keeps UTC time.
but on my system, RTC is keeping PDT.

Probably nothing you can do, except maybe fiddle with your "utctime" flag to make it match.  Would love to know if you see this too.

**Comment by churchers** [comment]
Hmm, it's amazing how confusing timezones are. The best description I can find for the `-u` option comes from the commit message.

    Add "-u" option to bhyve(8) to indicate that the RTC should maintain UTC time.

Fortunately the commit log does list some useful commands for seeing the RTC clock of the guest.
Can you run the following on your system and see what results you get:

Without the `-u` option:
```
# bhyvectl --vm=fbsd --get-rtc-time
rtc time 0x57984044: Wed Jul 27 05:01:56 2016
```
Guest RTC thinks it is 05:01, which is the time on my host. (It's actually 9am here but I've changed my timezone for testing). So the real time is being adjusted to the host's timezone before going into the guest RTC.

With the `-u` option, the guest RTC should be keeping UTC time, which it does in my case
```
# bhyvectl --vm=fbsd --get-rtc-time
rtc time 0x5798785f: Wed Jul 27 09:01:19 2016
```

Seeing as your host RTC is keeping PDT, I'd be interested to see if the `-u` option really does configure the guest to UTC on your machine, or if it just blindly passes along the hosts RTC.

**Comment by anteract** [comment]
Time at my desk, 0221
Dell R720, BIOS clock at UTC, 

Freebsd Host:  PDT  (0211) 
Freebsd Guest with -u:   Inside using console Guest,:   # date
Tue Aug  2 02:21:07 PDT 2016
from Host:  # bhyvectl --vm=fbsd11b3 --get-rtc-time
rtc time 0x57a06603: Tue Aug 02 09:21:07 2016

Freebsd Guest, No -u.  Inside Guest # date
Mon Aug  1 19:28:24 PDT 2016
From Host:  # bhyvectl --vm=fbsd11b3 --get-rtc-time
rtc time 0x57a0050c: Tue Aug 02 02:27:24 2016

It is confused, and confusing.  ntpd -q fixes the entire thing though :)  Ignore the small variations in times, I wasn't rushing to make them all match :)

**Comment by churchers** [comment]
> Freebsd Host: PDT (0211) 
> Freebsd Guest with -u: Inside using console Guest,: # date
> Tue Aug 2 02:21:07 PDT 2016
> from Host: # bhyvectl --vm=fbsd11b3 --get-rtc-time
> rtc time 0x57a06603: Tue Aug 02 09:21:07 2016

This looks right to me. Your local time is 02:21. UTC is 09:21
With the `-u` option, bhyve has configured the guests clock as UTC, and the `bhyvectl` command is correctly showing 09:21. Guest is configured as PDT and is showing 02:21 time.

In the second example bhyve has configured the guest rtc to its own localtime, so the RTC of the guest shows 02:21. Guest thinks this is a UTC clock and is adjusting for the timezone and going back 7 hours to 19:21 the previous day.

From what I can see the best configuration is to set always `utctime="yes"`, so that the `-u` option gets used and the guest gets a UTC clock. Then configure the guest timezone as you would on a normal host. However this only works if the `-u` option really does give the guest a UTC clock, which I'm not 100% convinced it will do if the host's RTC isn't UTC.

**Comment by churchers** [comment]
Of course it's probably a reasonable idea the run ntpd anyway.

I've just done a small test with a machine that was a few minutes out to see what affect updating the hosts time has.

I started a guest (using `-u`) and configured the time settings correctly. As with the host, it was a few minutes out. After running a sync on the host, the guest was still out, however it was correct after a reboot.

**Comment by churchers** [comment]
So the bhyve source uses the `time` C function to get the time for the RTC. The man page for this says:

> The time() function returns the value of time in seconds since 0 hours, 0 minutes, 0 seconds, January 1, 1970, Coordinated Universal Time.

I'm wondering if it actually makes sense to have vm-bhye always specify `-u`, unless the user specifically turns it off by setting the `utctime` configuration option...

**Comment by anteract** [comment]
After spending WAY too much time on this, I would agree, with -u is better, assuming RTC is UTC.  Probably okay to assume for most server platforms, but bhyve will get used on lots of small office/home systems that always tend to operate on local time so the option really is needed.  Just better explained maybe.

As for time, running ntp is critical on guests, the clock moves around all the time.  I only notice because one guest has Dovecot running, and its constantly complaining about the clock moving :)

**Comment by churchers** [comment]
I've changed 1.2 to set utc time by default. As per the man page for `time` above, I'm hoping that guests *should* always get a UTC clock if this option is enabled.

I've also updated the man page and the `sample.config` file that explains all the configuration options.
