### ISSUE TITLE
start first or stop last client cause network interface down

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#105]
FreeBSD 11.0 Beta2
vm-bhyve:  v1.2-alpha (build 102008)

output of ifconfig is

```
igb0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
    ether 00:19:99:82:f7:42
    inet 10.51.197.10 netmask 0xffffff00 broadcast 10.51.197.255 
    nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
    media: Ethernet autoselect (1000baseT <full-duplex>)
    status: active
igb1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
    ether 00:19:99:82:f7:43
    nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
    media: Ethernet autoselect
    status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
    options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
    inet6 ::1 prefixlen 128 
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
    inet 127.0.0.1 netmask 0xff000000 
    nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
    groups: lo 
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
    description: vm-public
    ether 02:6e:30:8c:fa:00
    nd6 options=1<PERFORMNUD>
    groups: bridge 
    id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
    maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
    root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
    member: igb0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 1 priority 128 path cost 20000

```

when start client. my ssh connection drop.
from dmesg

```
tap0: Ethernet address: 00:bd:66:71:f8:00
tap0: promiscuous mode enabled
igb0: link state changed to DOWN
bridge0: link state changed to DOWN
tap0: link state changed to UP
bridge0: link state changed to UP
igb0: link state changed to UP
```

igb0 DOWN, then UP

when stop client, ssh connection also drop.
from dmesg

```
tap0: link state changed to DOWN
igb0: link state changed to DOWN
igb0: link state changed to UP
```

when I start the second client, it does not cause this problem.
dmesg only show 

```
tap1: Ethernet address: 00:bd:f4:aa:02:01
tap1: link state changed to UP
```

**Comment by WanpengQian** [comment]
I found this is not the problem of vm-bhyve.

when manually add first tap to bridge. it will bring down the igb0, then up. 
adding second tap to bridge will not cause the same problem.

**Comment by churchers** [comment]
I have the same problem on my dev machine which I've always put down to the cheap realtek network interface. It doesn't happen on my other machines.

The first time I add a tap device to the bridge, it takes down the network long enough for me to usually lose my connection. I've been adding a dummy tap device to my bridge so that I can start/stop guests without triggering it.

I might post a message to the freebsd-net mailing list. I don't know if it's expected that some network interfaces will go down when bridging them, but it doesn't happen on most of my machines.

**Comment by churchers** [comment]
I don't think there is much I can do about this in vm-bhyve. I've added it to the known bugs section in the man page, if anyone ever happens to read it.

I'll also keep this issue here so people can see it's known about and hopefully don't raise additional issues about it.

**Comment by rayddteam** [comment]
ifconfig bridge0 priority 0
will makes highest priority for "Ethernet switch" bridge0, so it will think "he is root one" and will not try to find other with best priority (30 sec blocked network)
it is STP protocol used for if_bridge
But looks like there is bug, because it is set to RSTP by default, but RSTP make decision much faster (1-2 sec IIRC)

**Comment by WanpengQian** [comment]
before solve this problem, any thing can do? such as a workaround.
for example, on start, when vm-bhyve init the bridge interface, assign a dummy tap device to the bridge.

**Comment by rayddteam** [comment]
Please find two strings 'ifconfig "${_id}" description "vm-${_switch}" up' in the /usr/local/lib/vm-bhyve/vm-switch and put
ifconfig "${_id}" priority 0
before.

**Comment by WanpengQian** [comment]
@rayddteam thanks for your quick workaround!
now it only block a few seconds, not let the ssh connection drop.

**Comment by rayddteam** [comment]
welcome
Use FreeBSD and be happy :)

**Comment by churchers** [comment]
Thanks for the workaround
I've added it to the next vm-bhyve update

**Comment by rayddteam** [comment]
np

**Comment by Firemad03** [comment]
@churchers I got this problem when is the next release that fix it ? I got 1.1-p5

**Comment by WanpengQian** [comment]
The fix is on 1.1-p6

**Comment by WanpengQian** [comment]
this fix is missing after new switch code.

[code ref](https://github.com/churchers/vm-bhyve/commit/056b30d85eca14ff9f06abe7680a041a5ea665cc#diff-12d55c72049fea73ea69b1ca2f03d8cfR39)

**Comment by gunofmoon** [comment]
add one tap interface on boot time
```
# /etc/rc.conf
cloned_interfaces="tap0"
ifconfig_tap0="up"
```
and then add this tap to public switch
```
vm switch add public tap0
```

**Comment by gunofmoon** [comment]
> add one tap interface on boot time
> 
> ```
> # /etc/rc.conf
> cloned_interfaces="tap0"
> ifconfig_tap0="up"
> ```
> 
> and then add this tap to public switch
> 
> ```
> vm switch add public tap0
> ```

```
em0: link state changed to DOWN
vm-public: link state changed to UP
em0: promiscuous mode enabled
tap0: promiscuous mode enabled
vm-public: link state changed to DOWN
em0: link state changed to UP
vm-public: link state changed to UP
```
set phy interface to promiscuous mode at startup，may prevent nic from going down?

**Comment by WanpengQian** [comment]
OK. this issue has an answer that explain why.

[Creating bHyve virtual machines cause network flaps intel](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249427)

Quota from that thread:

> This is not the problem from bhyve side. The main problem is adding if_tuntap(4) to if_bridge(4) with igb(4) interface. When you add an interface without support TSO/CSUM e.t.c to if_bridge(4) which already has igb(4) with TSO/CSUM enabled, than if_bridge(4) resets offload flags on all interfaces. This is leads to link flap on igb(4).
> 
> So, it's work as expected, and described in if_bridge(4) manual page:
> 
>      The TOE, TSO, TXCSUM and TXCSUM6 capabilities on all interfaces added to
>      the bridge are disabled if any of the interfaces doesn't support/enable
>      them.  The LRO capability is always disabled.  All the capabilities are
>      restored when the interface is removed from the bridge.  Changing
>      capabilities at run-time may cause NIC reinit and a link flap.
> 
> As a workaround, you can turn off the offload flags on the igb(4) interface at boot time in /etc/rc.conf

After adding `-tso -lro -txcsum -rxcsum -txcsum6` to igb0 config in `/etc/rc.conf`, problem solved.

BTW: my /etc/rc.conf is something like this
```
ifconfig_igb0="inet 192.168.11.111 netmask 255.255.255.0 -tso -lro -txcsum -rxcsum -txcsum6"
```
