### ISSUE TITLE
Speedup image creation

### ISSUE THREAD

**Issue by larsengels** [churchers/vm-bhyve#106]
`vm create image`

takes a lot of time because of xz compression. xz however offers to use threaded compression significantly speeds up image creation at the expense of higher cpu load.
See this for example:

        % doas vm image create -d Gruninstallation_FreeBSD-10.3_User_lars_Pakete_zsh_vim-lite_git_doas freebsd10                                                                                 
    Creating a compressed image, this may take some time...
    load: 1.89  cmd: xz 6498 [running] 153.56r 152.07u 0.30s 100% 97936k
      --- %        45.3 MiB / 285.7 MiB = 0.159   1.9 MiB/s       2:33             
    load: 1.42  cmd: xz 6498 [running] 203.75r 201.87u 0.34s 100% 97940k
      --- %        57.2 MiB / 350.6 MiB = 0.163   1.7 MiB/s       3:23             
    load: 1.18  cmd: xz 6498 [running] 383.84r 380.84u 0.65s 100% 97940k
      --- %       122.2 MiB / 671.4 MiB = 0.182   1.7 MiB/s       6:23             
    load: 1.44  cmd: xz 6498 [running] 595.34r 589.99u 1.44s 100% 97940k
      --- %      361.8 MiB / 1067.0 MiB = 0.339   1.8 MiB/s       9:55             
    load: 1.11  cmd: xz 6498 [running] 895.08r 888.50u 1.99s 100% 97940k
      --- %      431.0 MiB / 1831.5 MiB = 0.235   2.0 MiB/s      14:55             
    load: 1.20  cmd: xz 6498 [running] 1065.71r 1058.62u 2.43s 100% 97940k
      --- %      544.8 MiB / 2177.5 MiB = 0.250   2.0 MiB/s      17:45             

vs. "xz -T0" in "lib/vm-zfs":

     % doas vm image create -d Gruninstallation_FreeBSD-10.3_User_lars_Pakete_zsh_vim-lite_git_doas freebsd10 
    Creating a compressed image, this may take some time...
    load: 3.63  cmd: xz 8622 [runnable] 105.88r 403.82u 0.89s 100% 547888k
      --- %       146.7 MiB / 687.2 MiB = 0.214   6.5 MiB/s       1:46             
    load: 3.74  cmd: xz 8622 [running] 121.70r 465.86u 1.15s 100% 647452k
      --- %       277.1 MiB / 825.6 MiB = 0.336   6.8 MiB/s       2:01             
    load: 3.74  cmd: xz 8622 [running] 122.27r 468.04u 1.15s 100% 649828k
      --- %       282.9 MiB / 831.4 MiB = 0.340   6.8 MiB/s       2:02             
    load: 3.76  cmd: xz 8622 [running] 127.39r 488.15u 1.22s 100% 665424k
      --- %       314.4 MiB / 874.2 MiB = 0.360   6.9 MiB/s       2:07             
    load: 3.76  cmd: xz 8622 [runnable] 127.90r 489.56u 1.22s 100% 667268k
      --- %       316.6 MiB / 877.3 MiB = 0.361   6.9 MiB/s       2:08             
    load: 3.76  cmd: xz 8622 [runnable] 128.36r 490.91u 1.22s 99% 668512k
      --- %       318.8 MiB / 880.5 MiB = 0.362   6.8 MiB/s       2:08             
    load: 4.25  cmd: xz 8622 [running] 363.43r 1388.02u 3.00s 100% 679952k
      --- %      826.8 MiB / 3369.6 MiB = 0.245   9.3 MiB/s       6:03             
    Image of freebsd10 created with UUID e45916cd-5723-11e6-837d-3c970e008394

**Comment by churchers** [comment]
Thanks for the info
I've added `-T0` to the xz command, and will include it in the next ports update for vm-bhyve-1.1

**Comment by nihr43** [comment]
Ah, I object.
This has been bothering me.  Until i found the '-u' option, i was annoyed that every time i image a vm, all other vms grind to a halt for a few minutes.   Depending on the environment, thats kind of a big deal.  Sure we want the imaging to be fast, but not at the debt of other, more critical services.

On the contrary, i think default behavior should be not to compress, and '--compress' be an option.  Besides, most people are running vm-bhyve on top of zfs, and thus have already chosen the transparent compression scheme thats right for them.  Double-compressing a waste of cpu in that case.
