### ISSUE TITLE
Windows guests ignoring stop commands

### ISSUE THREAD

**Issue by churchers** [churchers/vm-bhyve#11]
It seems that Windows can be fairly intermittent about responding to `vm stop` or `vm stopall`. Most critically, this may cause problems shutting down if a Windows guest is running; I'm not sure whether FreeBSD will wait forever or eventually kill the process.

As with most other hypervisors, I would recommend that guests are safely stopped before trying to shutdown the host, although obviously the ideal would be to have `vm stopall` work correctly. For Windows the best solution is to initiate a shutdown from inside the guest.

I don't believe this is an error with `vm-bhyve`, as we merely run a `kill BHYVE-PID` command. If for any reason we can't find the correct `PID`, we output an error, so no output from vm-bhyve suggests it is finding the process ID and sending the `kill` command.

I will need to see if any other bhyve users are experiencing this issue.

**Comment by meabandit** [comment]
It will kill the process I believe from /etc/defaults/rc.conf:

    rcshutdown_timeout="90" # Seconds to wait before terminating rc.shutdown

**Comment by churchers** [comment]
Ah ok. Of course the problem with increasing that is that you don't want to end up with a machine that won't reboot, or waits ages if something actually has locked up. Also Windows servers can take that long to shut down anyway, especially if they decide to run updates.

While not perfect, I think the best advice is as already mentioned. If `bhyve` is used in any production setting, shut down all guests properly first before trying to restart the host. I don't think it makes any sense to run `shutdown` with guests still running, and then just hope that they all stop cleanly automatically, before FreeBSD decides to give up and kill everything.

**Comment by WanpengQian** [comment]
I know bhyve does not support hibernate and resume now, when client is updating, kill the client can cause huge problem.
when host shutdown, better hibernate windows client other than send power off acpi event to client.

**Comment by churchers** [comment]
Closing this for now. 
Whether bhyve/windows correctly responds to a `kill {bhyve-pid}` isn't really our issue.
