### ISSUE TITLE
Feature Request: yes/no option

### ISSUE THREAD

**Issue by Fazik** [churchers/vm-bhyve#110]
Hello.
Some commands, for example poweroff, requires user's input (yes/no)
It will be great if there will be option for skipping this with "yes" or "no"

**Comment by churchers** [comment]
I will look at adding a force option to the `poweroff` & `reset` commands.

I assume you're aware that these are "hard" reset/poweroff, and should only be used if absolutely necessary? The normal way to stop a virtual machine is with `vm stop` which requires no confirmation and performs a normal ACPI shutdown of the guest.

**Comment by churchers** [comment]
Missed off `destroy` which also requires confirmation

**Comment by kuon** [comment]
I have the same issue, I run an Oracle vm which hangs sometimes after running. It is for testing and its filesystem is wiped after running, so I try to stop it, and if doesn't stop I poweroff it. It's hard to script without the ability to force `yes`.

Another option, which many command line tools follows, is to disable all prompts if the terminal is not a TTY. (and assume yes)
