### ISSUE TITLE
.template for ubuntu

### ISSUE THREAD

**Issue by anteract** [churchers/vm-bhyve#114]
.template/ubuntu.conf for ubuntu 16.04 needs a small change

If you add this to the bottom of the .template file for ubuntu...

```
grub_run0="linux /vmlinuz-4.4.0-21-generic root=/dev/mapper/ubuntu--vg-root ro"
grub_run1="initrd /initrd.img-4.4.0-21-generic"
```

It boots just fine after the installation.

**Comment by rajil** [comment]
This did not work for me out of the box. I had to specify the following for ubuntu-16.04.1-server-amd64.iso
`grub_run0="linux /vmlinuz-4.4.0-31-generic root=/dev/mapper/ubuntu-vg-root ro"
grub_run1="initrd /initrd.img-4.4.0-31-generic"
`

and in the grub boot menu
```
grub> set root=(hd0,gpt2)
grub> set prefix=(hd0,gpt2)/boot/grub
grub> boot
```

**Comment by anteract** [comment]
I understood that the grub menu was built off the .template, as mine was, this is what it looks like now.
(file is /vm/ubuntu/grub.cfg)
```
timeout=3  
menuentry 'ubuntu (bhyve run)' {  
    root=hd0,1  
    linux /vmlinuz-4.4.0-21-generic root=/dev/mapper/ubuntu--vg-root ro  
    initrd /initrd.img-4.4.0-21-generic  
}  
```

Same ISO even.  I'll destroy my test and try it again...

**Comment by rajil** [comment]
I suspect that your setup is slightly different to mine. I am passing the whole disk to the VM and installing grub on the MBR of the disk. This is the 'standard install' using lvm and guided partitioning of the whole disk. This is how my config looks like
```
guest="linux"                                                                                                                                                                                        
loader="grub"                                                                                                                                                                                        
cpu=4                                                                                                                                                                                                       memory=4096M                                                                                                                                                                                 
network0_type="virtio-net"                                                                                                                                                            
network0_switch="public"                                                                                                                                                              
disk0_type="ahci-hd"                                                                                                                                                                        
disk0_name="/dev/ada4"                                                                                                                                                                                        
disk0_dev="custom"                                                                                                                                                                          
grub_run0="linux /vmlinuz-4.4.0-31-generic root=/dev/mapper/ubuntu--vg-root ro"
grub_run1="initrd /initrd.img-4.4.0-31-generic"
```

The grub command line shows the kernel files on the gpt2 partition
```
grub> ls
(hd0) (hd0,gpt3) (hd0,gpt2) (hd0,gpt1) (host) (lvm/ubuntu--vg-swap_1) (lvm/ubun
tu--vg-root)
grub> ls (hd0,gpt2)/
lost+found/ System.map-4.4.0-31-generic abi-4.4.0-31-generic vmlinuz-4.4.0-31-g
eneric grub/ config-4.4.0-31-generic initrd.img-4.4.0-31-generic
```
The default grub menu shown below doesnt work for me
```
 | setparams 'ubuntu (bhyve run)'                                           |
 |                                                                          |
 |     root=hd0,1                                                           |
 |     linux /vmlinuz-4.4.0-31-generic root=/dev/mapper/ubuntu--vg-root ro  |
 |                                                                          |
 |     initrd /initrd.img-4.4.0-31-generic    
```

Once I specify the root and boot partition manually like so
```
grub> set root=(hd0,gpt2)
grub> set prefix=(hd0,gpt2)/grub
grub> insmod normal
grub> normal
```
i get additional entries in the grub menu. 
```
 +--------------------------------------------------------------------------+
 |ubuntu (bhyve run)                                                        |
 |Ubuntu                                                                    |
 |Advanced options for Ubuntu                                               |
 |                                                                          |
```

Using the second entry 'Ubuntu' i am able to boot into the system. The first entry ubuntu (bhyve run) doesnt work for me.

**Comment by EpiJunkie** [comment]
I believe when you use LVM on debian/ubuntu, then you must use the `grub_run_dir="/grub"` directive.

> I am passing the whole disk to the VM and installing grub on the MBR of the disk. 

Neat. I am curious, do you boot the guest as bare metal from this disk?

**Comment by rajil** [comment]
Yes, the guest is on bare metal. Works fine!

**Comment by m3lloa** [comment]
Just did a fresh FreeBSD 11 install to test bhyve with vm-bhyve. Works fine for FreeBSD VM. Ubuntu 17.04 server VM install, but won't run; drops to grub. As the point for me was to run other OSs with bhyve, as for FreeBSD jails can be used, I'd think some template changes could be needed to make the process automatic. Any template suggestions would be appreciated.

**Comment by m3lloa** [comment]
Update:

ubuntu 16.04 server -> lvm -> added grub_run_dir="/grub" to conf file;
ubuntu 17.04 server -> no lvm -> added grub_run_dir="/boot/grub" to conf file

Both installed and boot to ubuntu without issues.

**Comment by lbartoletti** [comment]
@m3lloa Same problem (ubuntu 16.04) and works with your tips.

**Comment by churchers** [comment]
Closing old issue. Unfortunately the commands also depend heavily on the exact guest distro and version being used.

If possible, it's worth seeing if the guest will work with UEFI as this generally boots like a standard machine and doesn't require custom commands.

**Comment by haikadev** [comment]
Update for 16.4.4
In the conf file you have the line:
grub_run0="linux /vmlinuz-4.4.0-116-generic root=/dev/mapper/ubuntu--vg-root ro"
or grub_run0="linux /vmlinuz-4.4.0-130-generic root=/dev/mapper/ubuntu--vg-root ro" if you update kernel by sudo apt upgrade until today.
Just change the "root=/dev/mapper/ubuntu--vg-root ro" to root=/dev/mapper/(name of username you create in install)--vg-root.
He use the username like parameter to LVM name group.
To don't get error after install, put ubuntu in username when installing or change the parameter after install.
Tested without uefi in conf.
My conf:

guest="linux"
loader="grub"
cpu=2
memory=2G
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
grub_run0="linux /vmlinuz-4.4.0-130-generic root=/dev/mapper/test--vg-root ro"
grub_run1="initrd /initrd.img-4.4.0-130-generic"

uuid="axxxxx-yyyy-aaaa-dfcvd-eeeeeeeeee"
network0_mac="aa:bb:cc:dd:ee"

OBS: test is the user created in install.

**Comment by haikadev** [comment]
Update for 16.4.4
In the conf file you have the line:
grub_run0="linux /vmlinuz-4.4.0-116-generic root=/dev/mapper/ubuntu--vg-root ro"
or grub_run0="linux /vmlinuz-4.4.0-130-generic root=/dev/mapper/ubuntu--vg-root ro" if you update kernel by sudo apt upgrade until today.
Just change the "root=/dev/mapper/ubuntu--vg-root ro" to root=/dev/mapper/(hostname you created in install)--vg-root.
He use the host name like parameter to LVM name group.
To don't get error after install, put ubuntu in hostname when installing or change the parameter after install.
Tested without uefi in conf.
My conf:

guest="linux"
loader="grub"
cpu=2
memory=2G
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
grub_run0="linux /vmlinuz-4.4.0-130-generic root=/dev/mapper/test--vg-root ro"
grub_run1="initrd /initrd.img-4.4.0-130-generic"

uuid="axxxxx-yyyy-aaaa-dfcvd-eeeeeeeeee"
network0_mac="aa:bb:cc:dd:ee"

OBS: test is the hostname created in install (test.domain).
