### ISSUE TITLE
Automatic PF configuration

### ISSUE THREAD

**Issue by ezoSresyeK** [churchers/vm-bhyve#123]
Could there be a setting in the general config that keeps from automatically generating a line or 2 in /etc/pf.conf. On a very configured pf installation, this happening at boot could cause nat related lines to be placed below rules related lines causing pf to fail to load which could be quite disruptive to other services on the host. It's actually bit me in the butt already once. It's nice to generate such files but perhaps having directions as to how to include them vs automatically including them would be better or at least having the option.

**Comment by churchers** [comment]
More recent versions create a separate file that must be included in the main pf configuration.

In future versions we will likely drop automatic firewall configuration completely as not all users use pf, and it can cause more harm than good if there is existing configuration.
