### ISSUE TITLE
vm console just hangs

### ISSUE THREAD

**Issue by petr-fischer** [churchers/vm-bhyve#127]
Hello, I am on FreeBSD 11.0-RELEASE, with vm-bhyve-1.1.5

Two things:

1) When I run `vm console centos7`, I get message `Connected` and then, "cu" hangs, no additional output or console connection, no input cursor, nothing...

2) When I run `vm -f start centos7`, I can see whole centos7 boot process, I can login, but my DELETE and BACKSPACE keys didn't work (just some messed chars instead of deletion).

Some problem with tmux? Can I debug/test more?

**Comment by churchers** [comment]
It looks like you're using the standard nmdm/cu console so tmux will not be involved.
Have you tried pressing enter when connected to the console? The cu console only shows output while you are connected, everything before that is lost. If the machine has already booted and output the login prompt, you will see nothing when you connect. Usually pressing enter will cause it to output the login prompt again.

I'm not sure about the second issue, I'll have to do some testing.

You may want to try using the tmux console as that can be a bit easier to use and more predictable.
You'll need to install tmux from ports and add the following to `$vm_dir/.config/system.conf`

    console="tmux"

**Comment by petr-fischer** [comment]
Thanks! `console=tmux` works! Also, the second issue with wrong DELETE key - this is problem only in FreeBSD login, after login, in shells, there is no problem at all with delete keys (so you can ignore it).

Without tmux (with "cu"), pressing enter didn't help (no keyboard input possible), and also guest centos7 cpu usage grows to 100%, until I kill "cu" process.

**Comment by churchers** [comment]
Hopefully using tmux solves the problem here, which seems to be a much better choice in general.

I've more than once considered setting tmux the default, but it would need to be a dependency on the port; Seems much easier to use and interactive mode is very useful for installs.
