### ISSUE TITLE
PCI passthrough in FreeBSD 11

### ISSUE THREAD

**Issue by rajil** [churchers/vm-bhyve#129]
Hello,

Following the guide (https://wiki.freebsd.org/bhyve/pci_passthru), i specified the following in /boot/loader.conf
```
vmm_load="YES"
pptdevs="3/0/0 3/0/1"
```

The /etc/rc.conf has the following entry:
```
vm_enable="YES"
vm_dir="zfs:tank/vm"
vm_list="ubuntu debian"
vm_delay="5"
```
However, the ixgbe driver still takes over the PCI NICs. It seems the pptdevs line has no effect. Is there a clash between vmm_load in loader.conf and vm_enable in rc.conf?
```
# pciconf -v -l|grep ix
ix0@pci0:3:0:0: class=0x020000 card=0x152815d9 chip=0x15288086 rev=0x01 hdr=0x00
ix1@pci0:3:0:1: class=0x020000 card=0x152815d9 chip=0x15288086 rev=0x01 hdr=0x00
```

**Comment by rajil** [comment]
I had a typo in loader.conf which was preventing the passthrough. After correcting it passthrough works.

**Comment by dariusc93** [comment]
What was the typo so anyone else who have the same issue will know
