### ISSUE TITLE
Wish list: add custom options to switch creation

### ISSUE THREAD

**Issue by jjuanino** [churchers/vm-bhyve#130]
Hi,

I think would be nice if vm will support to add custom options to  switch creation. Let me to show the following scenario:

I use `ctladm` to present LUNs to guest. To achieve this, I create a virtual switch, let say `iscsi`:

```
# vm switch create iscsi
```

For each guest, I connect it to `iscsi` switch:

```
# vm add -t network -s iscsi <guestname>
```

But this setup has a lot of drawbacks:

1. You can reach each guest from other, and this is undesirable. `iscsi` switch is not intented to connect the guests between them, only to serve volumes via iSCSI protocol. Each guest only should see the iSCSI server (the physical host, of course).
1. The bridge supporting this switch has a mtu 1500. But I need set to 9000 to boost performance.
1. The bridge supporting this switch has no ip address. But this address is just the iSCSI target, and is needed.

There are several ways to work around this issue, but all of them are annoying:

1. Create the bridge and the interface via `rc.conf`, for example:
```
cloned_interfaces="bridge0"
ifconfig_bridge0="192.168.254.1/24 mtu 9000 addm tap0"
```
Then, use `vm switch` import and such.
1. After switch creation with `vm create switch` above, and *before* startup any guest, modify the bridge configuration:
```
ifconfig bridge0 192.168.254.1/24 mtu 9000
```
After that, the tapX interfaces dynamically created will have a 9000 mtu also.

I think it would be nice to support something like `opts_iscsi="192.168.245.1/24 mtu 9000"` to switch configuration file, and apply these options each time vm starts the switch.

To isolate the interfaces, you need the `private` bridge option (see man ifconfig). I do not know which is the best way to accomplish this, but it would be very useful also. Maybe something like `networkX_opts` also?

Well, I hope you understand me, my english is not very good. Best regards

**Comment by churchers** [comment]
Hello,

Yes all makes sense. The `private` option looks interesting. I will look at adding additional configuration options for switches to allow more control over the `ifconfig` commands.

This bit intrigues me though:

> The bridge supporting this switch has no ip address. But this address is just the iSCSI target, and is needed.

If the iSCSI target is on the bhyve host, would it not perform better to just pass the block devices through using `virtio-blk/ahci-hd` devices in the guest rather than using iSCSI?

**Comment by jjuanino** [comment]
Hello, 

thanks you for your reply.

About the iSCSI target: in order to pass the block device through using `virtio/ahci-hd`, you need to stop the guest. With iSCSI and `ctladm`, you can pass the block device while the guest is running, and this is a big win. It works like a charm :-) and performs very well if you use jumbo frames in the virtual switch (mtu 9000). I am thinking in _bhyve_ and _vm-bhyve_ as a real cloud environment, similar to VMWare. Regards.

**Comment by churchers** [comment]
Ah, being able to add/remove iscsi devices while guest is running is a decent reason.

I've added some new options to switch create that should make these things possible. The options are explained in the man page but the following should create a bridge with a 9000 mtu, IP address and make all guest members private -

    vm switch create -a 172.1.2.3/24 -m 9000 -p iscsi

This is currently only in the GitHub code. I still have some work to do to make these configurable on existing switches, but it should work during creation as above.

**Comment by jjuanino** [comment]
Hi, sorry for my late reply. I have tested your changes and works as expected:

<pre>
# vm version
vm-bhyve: Bhyve virtual machine management v1.2-alpha (build 102036)
</pre>

Only a little thing: in the man vm, the -p flags says the following:

>              -p            Use this option to create a private switch. If this
>                            is enabled, no traffic will be allowed between
>                            guests on the same switch, however then will all be
>                            able to communicate with any physical interfaces
>                            added to the switch.
> 

But it could be no physical interface involved at all. In my scenario, the host computer is the iSCSI target, and it is exposed only to the internal 192.168.253/24 net:

<pre>
# ifconfig bridge6
bridge6: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 9000
        description: vm-iscsi0
        ether 02:10:ef:9e:c0:06
        inet 192.168.253.1 netmask 0xffffff00 broadcast 192.168.253.255
........
</pre>

But there is no physical interface joined to this bridge.

Best regards
