### ISSUE TITLE
Rebooting VM cause grub-bhyve to loader error

### ISSUE THREAD

**Issue by AK107** [churchers/vm-bhyve#133]
Have a centos vm (with rhel, debian, etc got the same error).

vm starts ok, but when it reboots (type reboot in ssh) the grub-bhyve stops with error:

> Dec 03 16:31:05: initialising
Dec 03 16:31:05:  [loader: grub]
Dec 03 16:31:05:  [uefi: no]
Dec 03 16:31:05:  [cpu: 1]
Dec 03 16:31:05:  [memory: 512M]
Dec 03 16:31:05:  [hostbridge: standard]
Dec 03 16:31:05:  [com ports: com1]
Dec 03 16:31:05:  [uuid: e9aaad36-9eba-11e6-9789-a0b3cce891a9]
Dec 03 16:31:05:  [utctime: yes]
Dec 03 16:31:05:  [debug mode: no]
Dec 03 16:31:05:  [primary disk: disk0]
Dec 03 16:31:05:  [primary disk dev: zvol]
Dec 03 16:31:05: initialising network device tap0
Dec 03 16:31:05: adding tap0 -> bridge0 (public addm)
Dec 03 16:31:05: booting
Dec 03 16:31:05: create file /bhyve/centos/device.map
Dec 03 16:31:05:  -> (hd0) /dev/zvol/data/bhyve/centos/disk0
Dec 03 16:31:05: /usr/local/sbin/grub-bhyve -c /dev/nmdm0A -m /bhyve/centos/device.map -M 512M -r hd0,1 -d /grub2 centos
Dec 03 16:31:13:  [bhyve options: -c 1 -m 512M -AHP -U e9aaad36-9eba-11e6-9789-a0b3cce891a9 -u]
Dec 03 16:31:13:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol/data/bhyve/centos/disk0 -s 5:0,virtio-net,tap0,mac=58:9c:fc:06:d8:da]
Dec 03 16:31:13:  [bhyve console: -l com1,/dev/nmdm0A]
Dec 03 16:31:13: starting bhyve (run 1)
Dec 03 16:34:56: bhyve exited with status 0
Dec 03 16:34:56: restarting
Dec 03 16:34:56: create file /bhyve/centos/device.map
Dec 03 16:34:57:  -> (hd0) /dev/zvol/data/bhyve/centos/disk0
Dec 03 16:34:57: /usr/local/sbin/grub-bhyve -c /dev/nmdm0A -m /bhyve/centos/device.map -M 512M -r hd0,1 -d /grub2 centos
Dec 03 16:34:57: **fatal; loader returned error 1**
Dec 03 16:34:57: destroying network device tap0
Dec 03 16:34:57: stopped

centos.conf

> guest="linux"
loader="grub"
grub_run_dir="/grub2"
cpu=1
memory=512M
network0_type="virtio-net"
network0_switch="public"
disk0_dev="zvol"
disk0_type="virtio-blk"
disk0_name="disk0"

this [https://github.com/churchers/vm-bhyve/issues/75](url) solution doesn't work for me.

in iohyve it's just works :(

**Comment by AK107** [comment]
Any ideas?

Sometimes reboots work, but for the first time. The next reboot failed. 

For example:

> Dec 24 11:39:57: initialising
Dec 24 11:39:57:  [loader: grub]
Dec 24 11:39:57:  [uefi: no]
Dec 24 11:39:57:  [cpu: 1]
Dec 24 11:39:57:  [memory: 512M]
Dec 24 11:39:57:  [hostbridge: standard]
Dec 24 11:39:57:  [com ports: com1]
Dec 24 11:39:57:  [uuid: e9aaad36-9eba-11e6-9789-a0b3cce891a9]
Dec 24 11:39:57:  [utctime: yes]
Dec 24 11:39:57:  [debug mode: no]
Dec 24 11:39:57:  [primary disk: disk0]
Dec 24 11:39:57:  [primary disk dev: zvol]
Dec 24 11:39:57: initialising network device tap0
Dec 24 11:39:57: adding tap0 -> bridge0 (public addm)
Dec 24 11:39:57: booting
Dec 24 11:39:57: create file /bhyve/centos/device.map
Dec 24 11:39:57:  -> (hd0) /dev/zvol/data/bhyve/centos/disk0
Dec 24 11:39:57: /usr/local/sbin/grub-bhyve -c /dev/nmdm0A -m /bhyve/centos/device.map -M 512M -r hd0,1 -d /grub2 centos
Dec 24 11:40:05:  [bhyve options: -c 1 -m 512M -AHP -U e9aaad36-9eba-11e6-9789-a0b3cce891a9 -u]
Dec 24 11:40:05:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol/data/bhyve/centos/disk0 -s 5:0,virtio-net,tap0,mac=58:9c:fc:06:d8:da]
Dec 24 11:40:05:  [bhyve console: -l com1,/dev/nmdm0A]
Dec 24 11:40:05: starting bhyve (run 1)
Dec 25 15:54:25: bhyve exited with status 0
**Dec 25 15:54:25: restarting**
Dec 25 15:54:25: create file /bhyve/centos/device.map
Dec 25 15:54:25:  -> (hd0) /dev/zvol/data/bhyve/centos/disk0
Dec 25 15:54:25: /usr/local/sbin/grub-bhyve -c /dev/nmdm0A -m /bhyve/centos/device.map -M 512M -r hd0,1 -d /grub2 centos
Dec 25 15:54:36:  [bhyve options: -c 1 -m 512M -AHP -U e9aaad36-9eba-11e6-9789-a0b3cce891a9 -u]
Dec 25 15:54:36:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol/data/bhyve/centos/disk0 -s 5:0,virtio-net,tap0,mac=58:9c:fc:06:d8:da]
Dec 25 15:54:36:  [bhyve console: -l com1,/dev/nmdm0A]
Dec 25 15:54:36: starting bhyve (run 2)
Dec 25 15:55:58: bhyve exited with status 0
**Dec 25 15:55:58: restarting**
Dec 25 15:55:58: create file /bhyve/centos/device.map
Dec 25 15:55:58:  -> (hd0) /dev/zvol/data/bhyve/centos/disk0
Dec 25 15:55:58: /usr/local/sbin/grub-bhyve -c /dev/nmdm0A -m /bhyve/centos/device.map -M 512M -r hd0,1 -d /grub2 centos
Dec 25 15:55:58: fatal; loader returned error 1
Dec 25 15:55:58: destroying network device tap0
Dec 25 15:55:58: stopped

**Comment by churchers** [comment]
What version of CentOS are you running?
I'd like to replicate the error but the CentOS vm I'm using doesn't have grub2 installed so my vm-bhvye config file is providing the grub commands directly.

**Comment by AK107** [comment]
$ uname -a
Linux centos 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

>> so my vm-bhvye config file is providing the grub commands directly.

it's doesn't matter: direct call grub commands (kernel, etc) from  conf, like:

grub_run0="linux /vmlinuz-2.6.32-573.el6.x86_64 root=/dev/mapper/VolGroup-lv_root"
grub_run1="initrd /initramfs-2.6.32-573.el6.x86_64.img"

still doesn't help in case of reboot.

**Comment by jstarcher** [comment]
What about using UEFI? Possible to install with grub and boot with UEFI like how coreOS is doing it?

**Comment by jstarcher** [comment]
My rather lame workaround was to install Centos 7.2.511 and running an upgrade

**Comment by sskincc** [comment]
FreeBSD requires some time to release resources after destroying virtual machine.
If we try to recreate the same virtual machine immediately after destroying, we will get this error.
This patch fixes it:
```
--- vm-run.orig 2016-08-19 10:54:27.000000000 +0200
+++ vm-run      2017-03-20 01:42:38.095775000 +0200
@@ -188,6 +188,7 @@
                 _exit=15
                 break
             fi
+            sleep 1
         fi
 
         # set full iso path
```
This is a somewhat dirty workaround, but it used in some places of vm-core and vm-rctl.

**Comment by cactus** [comment]
@sskincc your "fix" worked for me with a debian vm as well. 👌

**Comment by zuglufttier** [comment]
I have the same error with FreeBSD or Debian as bhyve guests.

The "fix" seems to do it for me as well but I'm not yet 100% sure.
