### ISSUE TITLE
Update UEFI firmware installation procedure

### ISSUE THREAD

**Issue by lubo** [churchers/vm-bhyve#137]
After installing UEFI firmware using installation procedure described in documentation, UEFI did not worked for me. However, it works after using `sysutils/bhyve-firmware`. Also, using the package (which is also available in the binary repository) is much more comfortable.

**Comment by DaveQB** [comment]
Thanks @Lubo 
I tried that and it didn't work for me. Looking at the logs for my clients, the command and arguments ran do not include the fbuf options, so it is like vm-bhyve doesn't honour when a vm is graphics enabled :(

**Comment by churchers** [comment]
> the command and arguments ran do not include the fbuf options, so it is like vm-bhyve doesn't honour when a vm is graphics enabled :(

Do you have the FreeBSD & vm-bhyve version you are running, and the relevant guest config/logs.
It's strange that it would omit the fbuf options if graphics is enabled. Not something I've come across before...
