### ISSUE TITLE
"vm switch add public <interface>" fail if there is already a <bridge0>

### ISSUE THREAD

**Issue by jonasbarsten** [churchers/vm-bhyve#138]

**Comment by anteract** [comment]
does "vm switch list" show the public switch?   (vm switch create public before add?)
 Is the <interface> already in another bridge?
Just a few of my thoughts.
Maybe posting the error you received would help get answers.

**Comment by churchers** [comment]
Closing this for now. Switch code has changed extensively since.
Please open a new issue if this problem continues in v1.2
