### ISSUE TITLE
Capture the error message of bhyve

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#14]
When using ```vm _run guest```, the bhyve error message can be displayed in console like the following
```
root@bhyve:/zones/vm/debian # vm _run debian
Unable to setup memory (17)
```
while in ```vm start guest```, this error message cannot be captured in vm-bhyve.log
It will be nice to display that kind of log in vm-bhyve.log.
```
Oct 22 05:35:19: create file /zones/vm/debian/device.map
Oct 22 05:35:19:  -> (hd0) /dev/zvol/zones/vm/debian/disk0
Oct 22 05:35:19: grub-bhyve -c /dev/nmdm1A -r hd0,msdos1 -m /zones/vm/debian/device.map -M 512M debian
Oct 22 05:35:25:  [bhyve options: -c 1 -m 512M -AHP -U 2c208d8f-77f0-11e5-b01a-0021cc60a290 -S]
Oct 22 05:35:25:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol/zones/vm/debian/disk0 -s 5:0,virtio-net,tap1 -s 6:0,passthru,0/22/0]
Oct 22 05:35:25:  [bhyve console: -l com1,/dev/nmdm1A]
Oct 22 05:35:25: starting bhyve
Oct 22 05:35:25: bhyve exited with status 1
Oct 22 05:35:25: destroying network device tap1
Oct 22 05:35:25: stopped
```

**Comment by churchers** [comment]
It seems adding the following to the end of the bhyve command in lib/vm-run captures errors 

     >"${vm_dir}/${_name}/bhyve.log" 2>&1

I'm not sure yet whether it's a good idea to add this as a standard function, or possibly as part of a 'debug' mode that can be switched on if needed.

**Comment by churchers** [comment]
I've added an option to the configuration file:

    debug="yes"

With this enabled, all the output (STDOUT & STDERR) is written to `${vm_dir}/guest/bhyve.log`. I think this is a reasonable compromise to allow the output to be captured if required, with the ability to just leave it there if you always want to capture `bhyve` output. By default we run as normal.

**Comment by WanpengQian** [comment]
It works. thank you!
