### ISSUE TITLE
`vm install {name} {iso}` does not verify iso name

### ISSUE THREAD

**Issue by sdwilsh** [churchers/vm-bhyve#141]
I had a typo in my `{iso}` that was one character different from the name in `vm iso`.  This still started the vm, but since this was an Ubuntu VM, it dropped me to grub.  It took me quite a while to realize what was wrong.

Can this warn or error if it's not a VM from the list?

**Comment by churchers** [comment]
Thanks for the report.
I think there's a few other little bugs I need to fix but I'll get this submitted as to ports as `1.1-p6` soon.
