### ISSUE TITLE
Debian template fails on Debian 8 clients

### ISSUE THREAD

**Issue by DaveQB** [churchers/vm-bhyve#142]
Hi,

I just wanted to report this to save others the pain. 
I found I had to do two things to the config for a newly installed Debian 8 client. You can make these changes to the template to save making it for each client installed.

1. Add
grub_run_partition="msdos1"

2. Either remove this line or change:
grub_run_dir="/grub" --> grub_run_dir="/boot/grub"

Thanks for this great piece of software.

**Comment by churchers** [comment]
Thanks, I've just tested this and installed/booted 8.7.1 successfully.
I'll submit it to ports as part of vm-bhyve 1.1-p6
