### ISSUE TITLE
About autostart flag of vm

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#143]
currently ```vm_list``` in ```/etc/rc.conf``` will control the vm on startup/shutdown.
when vm name is renamed or destroyed, this list will not sync automatically and can be wrong.

I think it is better put the 
```auto_start = "yes"``` 
flag at each vm.conf.

and for better control start/stop dependency of each vm, it is better have something like 
```
start_before="vm_name"
stop_after="vm_name"
```
and for no dependency vms, we can startup parallels, that will save some startup time.

**Comment by churchers** [comment]
I'd like to do something like this, but handling the before/after dependencies is quite complex, especially in shell.

The current method is actually quite similar to how it's done in ESX, where they have a dedicated section in the host configuration to enable autostart and manually choose the guest order. (The main difference being configurable delays and shutdown ordering). From a user perspective I don't really see that having the setting inside a guest will make things any easier or quicker for them, and it solves a lot of headaches letting the user choose their own order.

I do of like the idea parallel start up, but a few seconds delay between starts is fairly unnoticeable, and even small things like having multiple processes try and create interfaces at the same time has the scope to cause problems.

I am looking into making stop honour the startup order, although that has its own complexities.
