### ISSUE TITLE
strange network problem about bridge

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#146]
Here is the problem description.

FreeBSD host has an IP ``10.51.197.30/24`` on ``igb0`` interface
VM guest. OS is win7, has an IP ``10.51.197.35/24``
on host, there is a ``bridge0`` which is created by ``vm-bhyve``, have two members, ``igb0`` and ``tap0``.

on host, ``samba`` is running.

and in guest. I can ping host's IP, which is ``10.51.197.30``.
but I can't connect to samba server by ``\\10.51.197.30``.

I try ``tcpdump`` on interface ``igb0/bridge0/tap0``,
only ``tap0`` can see the package from guest when access samba service.
``igb0`` only saw the first packet.

I think after first tcp packet, the rest packet from guest to host just walk through ``tap0`` interface,
and kernel process it. which never come to ``igb0`` interface anymore.

currently I have a workaround, plug another network adapter to host. and set the ``10.51.197.30`` IP on 
this adapter (``igb0`` has no IP, both adapter connect to switch). and it works. 

is there any other workaround exists?

**Comment by cactus** [comment]
Generally you want to put the host ip on the bridge (so says FreeBSD handbook too). I recommend setting up the bridge manually, and telling vm-bhyve to simply use it (bridge import).

Here is an example based on what I use (mac is set specifically on bridge to avoid it changing when I reboot)":
```
cloned_interfaces="bridge0 tap0"
# add a dummy tap just to keep this from happening
# https://github.com/churchers/vm-bhyve/issues/105
ifconfig_bridge0="ether 96:3d:4b:f1:79:7a addm igb1 addm tap0 up"
ifconfig_bridge0_alias0="inet 172.16.100.16/24"
ifconfig_igb1="up"
ifconfig_tap0="description 'dummy-tap' up"
```

Then in vm/.config/system.conf

```
switch_list="public"
bridge_public="bridge0"
```

```
$ vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          manual     bridge0     n/a       n/a          n/a
```

see also: https://github.com/churchers/vm-bhyve/issues/25

**Comment by churchers** [comment]
Closing old issue. It's possible to now configure an address on a virtual switch which may be a solution to this problem. Please re-open if issue persists
