### ISSUE TITLE
Installation of windows7 silently fails 

### ISSUE THREAD

**Issue by jbulow** [churchers/vm-bhyve#150]
Followed instructions. vm-bhyve.log:

Feb 28 12:40:15: initialising
Feb 28 12:40:15:  [loader: none]
Feb 28 12:40:15:  [uefi: yes]
Feb 28 12:40:15:  [cpu: 1]
Feb 28 12:40:15:  [memory: 2G]
Feb 28 12:40:15:  [hostbridge: standard]
Feb 28 12:40:15:  [com ports: com1]
Feb 28 12:40:15:  [uuid: 5240d496-fdaa-11e6-9f15-0cc47ad9ded8]
Feb 28 12:40:15:  [utctime: no]
Feb 28 12:40:15:  [debug mode: no]
Feb 28 12:40:15:  [primary disk: disk0.img]
Feb 28 12:40:15:  [primary disk dev: file]
Feb 28 12:40:15: initialising network device tap1
Feb 28 12:40:15: adding tap1 -> bridge0 (public)
Feb 28 12:40:15: booting
Feb 28 12:40:15:  [bhyve options: -c 1 -m 2G -Hwl bootrom,/zroot/vm/.config/BHYVE_UEFI.fd -U 5240d496-fdaa-11e6-9f15-0cc47ad9ded8]
Feb 28 12:40:15:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,ahci-hd,/zroot/vm/win7/disk0.img -s 5:0,virtio-net,tap1,mac=58:9c:fc:02:95:3b]
Feb 28 12:40:15:  [bhyve console: -l com1,/dev/nmdm1A]
Feb 28 12:40:15:  [bhyve iso device: -s 3:0,ahci-cd,/zroot/vm/.iso/win7repack.iso]
Feb 28 12:40:15: starting bhyve (run 1)
Feb 28 12:40:15: bhyve exited with status 1
Feb 28 12:40:15: destroying network device tap1
Feb 28 12:40:15: stopped

**Comment by abishai** [comment]
This is obvious path errors. Are you sure that full path to guest is /zroot/vm ? Maybe /vm ?

**Comment by jbulow** [comment]
How is this an obvious path error? I have other VMs (FreeBSD and Ubuntu) in /zroot/vm working just fine.

**Comment by abishai** [comment]
I remember I had exit with status 1 when my paths was incorrect. I have windows 7 guests now and they works just fine.
```
zdata                                         3.47T  6.74T   140K  none
zdata/bhyve                                   22.1G  6.74T  2.64G  /usr/local/bhyve
zdata/bhyve/base                              4.23G  6.74T  4.16G  /usr/local/bhyve/base
```
```
vm_enable="YES"
vm_dir="zfs:zdata/bhyve"
```
```
Mar 04 23:13:12: booting
Mar 04 23:13:12:  [bhyve options: -c 1 -m 2G -Hwl bootrom,/usr/local/bhyve/.config/BHYVE_UEFI.fd -U bf5a56bd-0114-11e7-a5dc-001b21bf3ef9]
Mar 04 23:13:12:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,ahci-hd,/usr/local/bhyve/base/disk0.img,sectorsize=512 -s 5:0,virtio-net,tap0,mac=58:9c:fc:02:71:70]
Mar 04 23:13:12:  [bhyve console: -l com1,/dev/nmdm0A]
Mar 04 23:13:12:  [bhyve iso device: -s 3:0,ahci-cd,/usr/local/bhyve/.iso/x64-windows7.iso]
```

**Comment by churchers** [comment]
It's worth adding `debug="yes"` to the config file and seeing if anything interesting gets written to `{guest_directory/bhyve.log}`

**Comment by jbulow** [comment]
more /zroot/vm/win7/bhyve.log
bhyve: Could not open backing file: /dev/zvol/zroot/vm/win7/disk0.img: No such file or directory

What step did I miss?

**Comment by jbulow** [comment]
This issue was caused by missing the disk0_dev="sparse-vol" in config when recreating the vms after repeated failure. 

The installation now fails because bhyve corrupts the VNC data during the installation process making it impossible to install windows.
