### ISSUE TITLE
No network connection from guest

### ISSUE THREAD

**Issue by herrbischoff** [churchers/vm-bhyve#151]
I have two servers, both with identical hardware and software setup (FreeBSD 11, newest patches, used Synth to install `vm-bhyve`. On both machines I have followed the installation instruction to the letter. On both machines I have one external interface, thus using NAT for bhyve IP addresses. On one machine networking from and to guests works without issues, on one of the machines it does not work.

I have already tried (without success):

* disabling `pf`
* removing an IP alias (second IP)
* uninstalling `vm-bhyve`, removing all network interfaces created, reboot, reinstall

I can ping the guest from the host machine but not vice versa. The host cannot even see the gateway.

Any idea what could be amiss?

**Comment by herrbischoff** [comment]
Addition after two weeks of no answer.

Here's what I did, several times from scratch, step by step:

```
pkg install vm-bhyve
zfs create zroot/vm
sysrc vm_enable="YES"
sysrc vm_dir="zfs:zroot/vm"
vm init
cp /usr/local/share/examples/vm-bhyve/* /zroot/vm/.templates/
vm switch create public
vm switch nat public on
vm iso http://releases.ubuntu.com/16.04.2/ubuntu-16.04.2-server-amd64.iso
vm create -t ubuntu -s 50G testvm
vm [-f] install testvm ubuntu-16.04.2-server-amd64.iso
vm console testvm
```

Install runs, obviously no DHCP auto configuration, manually set to 172.16.0.2/24, gateway 172.16.0.1. No network connectivity. I manually restarted pf after the new config include is added.

```
$ vm switch info
------------------------
Virtual Switch: public
------------------------
  type: auto
  ident: bridge0
  vlan: -
  nat: yes
  physical-ports: -
  bytes-in: 10582 (10.333K)
  bytes-out: 210 (210.000B)

  virtual-port
    device: tap0
    vm: testvm
```

Here's the files involved:

```
$ cat /zroot/vm/testvm/testvm.conf
loader="grub"
cpu=4
memory=2048M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid="3366b5df-08d4-11e7-a9e7-448a5b29dff9"
```

```
$ cat /etc/pf.conf
[...]
include "/zroot/vm/.config/pf-nat.conf"
[...]
```

```
$ cat /zroot/vm/.config/pf-nat.conf
# vm-bhyve nat
nat on re0 from {172.16.0.0/24} to any -> (re0)
```

```
$ cat /etc/sysctl.conf
[...]
net.inet.ip.forwarding=1
[...]
```

**Comment by WanpengQian** [comment]
what is your output of ```ifconfig -a``` from host?

**Comment by herrbischoff** [comment]
Thanks to the FreeBSD forum, you can find the solution to this problem here: https://forums.freebsd.org/threads/60123/#post-345664

It turns out, a pf `block drop in all` rule that had no corresponding `set skip on bridge0`. @churchers, that may be interesting to add to the documentation as a troubleshooting hint. I'm aware that I should have seen this but sometimes you cannot see the forest for the trees.
