### ISSUE TITLE
Run DragonFly BSD 4.8 as a guest

### ISSUE THREAD

**Issue by iron-udjin** [churchers/vm-bhyve#157]
Hello,

I tried to install DragonFly BSD as a guest. Here what I found:
In case I put **disk0_type="virtio-blk"** in VM configuration - installer cannot format disk and failes to continue install process. WIth **disk0_type="ahci-hd"** I was able to install OS.
When I tried to bootup the OS, it stucks on bootloader prompt. Here is what I see:
```
OK 
OK ls
open '/' failed: no such file or directory
OK lsdev
host devices:
    host0:   Host filesystem
disk devices:
    disk0:   Guest drive image
      disk0p1: EFI
      disk0p2: Unknown
zfs devices:
OK load /boot/kernel/kernel                             
can't find '/boot/kernel/kernel'
OK 
```
My VM configuration:
```
graphics="yes"
graphics_listen="x.x.x.x"
graphics_port="5901"
graphics_res="800x600"
graphics_wait="yes"
uefi="yes"
guest="generic"
loader="bhyveload"
cpu=4
memory=8192M
network0_type="virtio-net"
network0_switch="public"
#disk0_type="virtio-blk"
disk0_type="ahci-hd"
disk0_name="/dev/zvol/zroot/vm/php7-dfly_zvol"
disk0_dev="custom"
uuid="0ec14c29-2086-11e7-80ef-002590d96932"
network0_mac="00:50:56:00:C0:35"
```
How can I correctly boot from the EFI partition?

P.S: Please update documentation. Without `uefi="yes"` option bhyve doesn't start VNC server even if graphics* options exist.

**Comment by asomers** [comment]
@iron-udjin see https://github.com/churchers/vm-bhyve/pull/156 for a working DragonFly template
