### ISSUE TITLE
SmartOS Support

### ISSUE THREAD

**Issue by churchers** [churchers/vm-bhyve#16]
As of commit 4292fee 24/10, it's possible to run a SmartOS guest. The `vm-bhyve` configuration is the same as `windows.conf`, with the following changes:

    guest="generic"
    uefi="csm"
    hostbridge="none"
    comports="com1 com2"

Seeing as it's a UEFI guest and requires no specific loader, there's no point me adding another guest support function for it when `generic` can be used.

Note that you'll need a copy of the UEFI CSM firmware which can be obtained from the same place as the normal UEFI firmware. The other important difference, that is only possible since the commit mentioned, is `hostbridge="none"`. At the moment the hostbridge causes the `virtio-net` network adapter to be presented to SmartOS in a way that causes it to panic. I believe this is down to a VirtIO bug in Illumos which has already been fixed in development versions.

The other issue with SmartOS is that it is designed to never boot from the hard disk. It is designed to run from a CD, or more commonly a network location. The hard disk is only used as persistent storage. Because of this, the guest always needs to be started in install mode. The first time SmartOS will enter a configuration menu to set up the system and store configuration on the hard disk. The next time it boots off the ISO it will boot straight to a login prompt.

    vm install smartosguest smartos-latest.iso

If you use the normal `vm start` command, it will fail to boot, as there's not actually any boot code or kernel installed to the hard disk. Unfortunately this does mean that you can't use the autostart (start on boot) option with SmartOS, as that uses the `start` command.

If there are any requests for this to be supported, comment here. If people actually want it supported properly, I can add a `bootiso="isofilename.iso"` configuration option, which can be used to specify an ISO file which should be used for every boot of a guest. That way you can `vm start smartos`, and it will still boot off the ISO. It's not worth adding this if there's no requests for it though as SmartOS is a bit of a special case.

**Comment by WanpengQian** [comment]
Great Job, Now I can run SmartOS in my bhyve server smoothly. Thanks.
