### ISSUE TITLE
How to use CSM firmware(installing solaris 11.3)?

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#160]
I am trying to install solaris 11.3 on bhyve.

FreeBSD version is 12.0 current.
```
root@current:/zroot/vm/sol113 # uname -a
FreeBSD current 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r317181: 
Thu Apr 20 05:39:11 UTC 2017    
root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```
vm-bhyve version is
```
root@current:/zroot/vm/sol113 # vm version
vm-bhyve: Bhyve virtual machine management v1.2-alpha (build 102038)
```

By using UEFI firmware, the cd loader get stuck at following stage:
![image](https://cloud.githubusercontent.com/assets/6359418/25376580/b48c7ab6-29df-11e7-9234-85ec2f2fbee9.png)

Since SmartOS can run with CSM firmware, I am trying to use CSM firmware, 
but after connect to vnc console, nothing display.
and I also cannot get anything from serial console.

The cpu usage of bhyve is about 100%, I think it is running.

Any tips?

**Comment by churchers** [comment]
I also have a lot of trouble getting anything to run with the CSM firmware, and it's a bit beyond me for debugging. If anyone can provide info on possible changes to the bhyve command to fix these I'm welcome to apply them.
