### ISSUE TITLE
Custom options, or more of the commandline implemented

### ISSUE THREAD

**Issue by ehasting** [churchers/vm-bhyve#162]
I see that a case suggesting something similar is being closed.  however i would like a way to set custom options.. or map out the -w option someway.  running bhyve on my AMD i need this option to get things going (dunno if this is normal for all AMDs?).

-w: ignore unimplemented MSRs

so either a "optional parameter" variable or option, or map it directly.

**Comment by churchers** [comment]
I've added an `ignore_bad_msr` config option to the latest stable version (1.1-p8). I'll see if I can get a PR submitted to ports today.

I will also look at possibly adding a `bhyve_options` feature to the config file. The vast majority of bhyve functionality can be accessed using the "user-friendly names" in vm-bhyve config, although there are some things such as CPU pinning or debug options that I don't really have any plan to support, but could be useful for some users.
