### ISSUE TITLE
Multiple vm_dir location

### ISSUE THREAD

**Issue by Firemad03** [churchers/vm-bhyve#164]
Hi,

Is it possible to have multiple location of the pool/vm location ?

For example I want to use a dataset on my pool that have ssd and another dataset on my HDD.

I want to create vm on my ssd dataset and other vm on my second dataset. Both dataset is on a different pool in ZFS.

If I read the wiki it seem that you can only add only one location in the vm_dir variable inside the rc.conf

I know that I can use multiple datastore but if I want 100% to one location ?

Thanks

**Comment by Firemad03** [comment]
Nvm, I read the wiki datastore and I found my answer :)

**Comment by churchers** [comment]
```
vm datastore add ssddatastore zfs:ssdpool/my/dataset
vm create -d ssddatastore myguest
```
