### ISSUE TITLE
~ + Ctrl+D on another keyboard layout is impossible

### ISSUE THREAD

**Issue by Firemad03** [churchers/vm-bhyve#165]
Hi,

The ~ + Ctrl+D is really a pain with another keyboard layout. I'm using canadian french and it's impossible.

I need to do a ctrl+alt + another one to get the ~ but since I was using the ctrl well I can't do the Ctrl + D....

I suggest something more friendly like Ctrl + A + D or anything else :)

**Comment by brd** [comment]
This is the standard cu(1) disconnect sequence.. From the man page:

>      ~^D or ~.
>             Drop the connection and exit.  Only the connection is dropped –
>             the login session is not terminated.

Is the other one easier?

**Comment by Firemad03** [comment]
Yes the other one is easier! :) thx !

**Comment by churchers** [comment]
I actually prefer using tmux these days. If you have tmux installed and are running v1.1 or newer, just edit `${vm_dir}/.config/system.conf` and set the following:

    console="tmux"

You can then use the tmux `Ctrl+b, then d` to detach.
