### ISSUE TITLE
An option to disable persistent automatic write pf nat rules

### ISSUE THREAD

**Issue by trippleflux** [churchers/vm-bhyve#169]
I have already write my own pf nat rules for bhyves, and vm-bhyve seems still automatically added the pf-rules at the end of my /etc/pf.conf, it would be great if there is an option to disable this automatic rewrite.

Chmod /etc/pf.conf seems no use, as vm-bhyve seems still able to write into it :-(.

**Comment by churchers** [comment]
vm-bhyve greps for `${vm_dir}/.config/pf-nat.conf` in `/etc/pf.conf`, so hopefully leaving the include line in there but commenting it out should stop it from continually adding it.

**Comment by trippleflux** [comment]
Yes but it still count sort of 'hacks' than upstream implementation :-(.

**Comment by churchers** [comment]
I'm not leaving it up to the user to add rules to `pf.conf`, or whatever other firewall/service they want to use for NAT.
