### ISSUE TITLE
Installing windows 7 on FreeBSD 11 still broken

### ISSUE THREAD

**Issue by jbulow** [churchers/vm-bhyve#175]
Using this config:

> uefi="yes"
> cpu=8
> memory=16G
> network0_type="virtio-net"
> network0_switch="public"
> disk0_type="ahci-hd"
> disk0_name="disk0.img"
> disk0_dev="sparse-zvol"
> uuid="873d0a08-71f5-11e7-b323-0cc47ad9ded8"
> network0_mac="58:9c:fc:0a:77:db"
> graphics="yes"
> debug="yes"
> 

Installation ends with this (on both console and vnc):

> UEFI Interactive Shell v2.1
> EDK II
> UEFI v2.40 (BHYVE, 0x00010000)
> Mapping table
>      BLK0: Alias(s):BLK1:;BLK2:;BLK3:
>           PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x0,0x0,0x0)
> Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
> Shell>

Are there any other updated instructions on how to install windows on bhyve?

**Comment by jbulow** [comment]
The same result when trying with windows 10.

**Comment by jbulow** [comment]
The log file:

> Jul 26 14:10:34: initialising
Jul 26 14:10:34:  [loader: none]
Jul 26 14:10:34:  [uefi: yes]
Jul 26 14:10:34:  [cpu: 8]
Jul 26 14:10:34:  [memory: 16G]
Jul 26 14:10:34:  [hostbridge: standard]
Jul 26 14:10:34:  [com ports: com1]
Jul 26 14:10:34:  [uuid: 47a0c680-71fb-11e7-b323-0cc47ad9ded8]
Jul 26 14:10:34:  [utctime: no]
Jul 26 14:10:34:  [debug mode: yes]
Jul 26 14:10:34:  [primary disk: disk0.img]
Jul 26 14:10:34:  [primary disk dev: sparse-zvol]
Jul 26 14:10:34: generated static mac 58:9c:fc:05:cd:14 (based on 'win10:0:1501071034:0')
Jul 26 14:10:34: initialising network device tap0
Jul 26 14:10:34: adding tap0 -> bridge0 (public)
Jul 26 14:10:34: dynamically allocated port 5900 for vnc connections
Jul 26 14:10:34: booting
Jul 26 14:10:34:  [bhyve options: -c 8 -m 16G -Hwl bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd -U 47a0c680-71fb-11e7-b323-0cc47ad9ded8]
Jul 26 14:10:34:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,ahci-hd,/dev/zvol/zroot/vm/win10/disk0.img -s 5:0,virtio-net,tap0,mac=58:9c:fc:05:cd:14 -s 6:0,fbuf,tcp=0.0.0.0:5900,wait]
Jul 26 14:10:34:  [bhyve console: -l com1,/dev/nmdm0A]
Jul 26 14:10:34:  [bhyve iso device: -s 3:0,ahci-cd,/zroot/vm/.iso/win10.iso]
Jul 26 14:10:34: starting bhyve (run 1)

**Comment by jbulow** [comment]
Using FreeBSD 11.1 and vm-script 1.1-p8.

**Comment by churchers** [comment]
What does the `bhyve.log` file contain for this guest. Is it the same output as issue #150?

**Comment by jbulow** [comment]
Nope. 

I just found the solution for this one: make sure to press a key in VNC before it moves on automatically. A fat note in the instructions should be added about this annoying behavior. 

(But the installation not fails later in the process because bhyve is broken in FreeBSD 11.1)
