### ISSUE TITLE
manual bridge doesn't addm tap dev on VM restart

### ISSUE THREAD

**Issue by philpennock** [churchers/vm-bhyve#176]
I have a working network and VM setup, for one start of a new VM; it's a not-common network setup, so I manually setup the bridge in `/etc/rc.conf` and used `vm switch import` to make it known to `vm-bhyve`.  On first start, everything works.

If I shut down the VM and then start it again, the tap device owned by the new bhyve process does not become a member of the bridge.  If I `ifconfig vmbridge addm ${TAPDEV:?}` to put it back in, it works.

```
# vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          manual     vmbridge    n/a       n/a          n/a
```

**Comment by chunlinyao** [comment]
+1 I have the same issue, I have a bridge0 configured in `/etc/rc.conf`, and this is my `system.conf`

    switch_list="public"
    bridge_public="bridge0"

The tap device does not added to bridge0 when start a VM.

**Comment by WanpengQian** [comment]
As far as I know you can not doing this in current version.
If you want to have a try, you can modify the source code.

For example, 
https://github.com/WanpengQian/vm-bhyve/commit/18e2c8c18db34bf7ff1c5c8ae5098364e187b20b

After vm TAP device is created. you can add some custom script to add that TAP to your bridge.
(Of course, you have to define a custom config.)

**Comment by churchers** [comment]
Closing this for now. Switch code has changed extensively since.
Please open a new issue if this problem continues in v1.2
