### ISSUE TITLE
Can I change 172.16.0.0/24 to 192.168.8.0/24?

### ISSUE THREAD

**Issue by bleakwind** [churchers/vm-bhyve#178]
Can I change 172.16.0.0/24 to 192.168.8.0/24?
Thanks...

**Comment by mateuszkwiatkowski** [comment]
This seem to be supported with current master:
```
switch create [-t type] [-i interface] [-n vlan-id] [-m mtu] [-a address/prefix-len] [-b bridge] [-p] <name>
```

**Comment by churchers** [comment]
In GitHub master or upcoming releases you can specify the ip address used on a virtual switch.

Note that as it stands, NAT will configured manually, either with PF or whatever other firewall/NAT subsystem users want to use.
