### ISSUE TITLE
Generated device.map file should contain all defined disks

### ISSUE THREAD

**Issue by packardb** [churchers/vm-bhyve#180]
The generated devices.map file should contain all the disks added to the virtual machine, not only the hard-coded (hd0), or at least it should not overwrite the file if it already exists.

**Comment by packardb** [comment]
```
[root@builder /media/storage/VMs]# cat ubuntu-lvm/device.map 
(hd0) /media/storage/VMs/ubuntu-lvm/disk0.img
(hd1) /media/storage/VMs/ubuntu-lvm/disk1.img

```

**Comment by churchers** [comment]
This has been addressed in https://github.com/churchers/vm-bhyve/commit/8d11d35dcee75a59c131f711600b605e1ca2f41c, although unfortunately it's not mentioned in the commit message as I didn't realise it was part of the commit I was making :(

```
Jun 21 15:09:11: create file /vm/ub1/device.map
Jun 21 15:09:11:  -> (hd0) /vm/ub1/disk0.img
Jun 21 15:09:11:  -> (hd1) /vm/ub1/disk1.img
```
