### ISSUE TITLE
Possibility to change the preferred boot disk

### ISSUE THREAD

**Issue by packardb** [churchers/vm-bhyve#181]
It looks like the `_bootdisk` variable in `lib/vm-run` is hard-coded to disk0_name. We should have a way to specify the desired boot disk (eg. bootdisk="diskN" in a VM's configuration file).

**Comment by packardb** [comment]
This, along with #180 would enable people to present more than one device to grub (preferably, all the disks present in the configuration file) and enable them to set the desired boot disk from which to boot from (eg. disk3).

**Comment by packardb** [comment]
The `_root` variable in `lib/vm-guest`, line 97, should probably be set to the selected boot disk instead of the hard-coded value of "hd0,1".

**Comment by churchers** [comment]
Issue #180 has been addressed to provide all disks in `device.map`.
If I get enough calls for it I will add an option to configure the disk name via guest configuration.
