### ISSUE TITLE
Debian 9 Grub Issue

### ISSUE THREAD

**Issue by marcotuna** [churchers/vm-bhyve#184]
I love this tool. It works great. I've already managed to create a VM with PFSense and Ubuntu, however when I try with Debian 9 (Netinstall) it always get stuck in Bootloader.
I've tried all kinds of different configurations/templates (including the one in the .templates directory) and nothing seems to work.
I would appreciate some help regarding this subject. Thanks!

**Comment by marcotuna** [comment]
I managed to get it work by using Debian (UEFI) configuration.
https://github.com/churchers/vm-bhyve/wiki/Supported-Guest-Examples

**Comment by nihr43** [comment]
I have Debian 9.3 working fine using grub2-bhyve version 0.40_3 , vm-bhyve 1.1.8_2, FreeBSD 11.1 using the following:

``
loader="grub"
cpu=2
memory=512M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
grub_run_partition="1"
grub_run_dir="/boot/grub"
``

**Comment by sekrett** [comment]
I don't understand why I should care about boot process details? The bootsector has all that information.

I installed Debian with UEFI configuration, it booted, but at second reboot it does not boot anymore. So I found a much easier way to solve the problem. It's funny but it works. Any Linux distro is somehow Windows compatible.

```
guest="windows"
uefi="yes"
graphics="yes"
xhci_mouse="yes"
graphics_res="1024x768"
graphics_wait="yes"
```

**Comment by nihr43** [comment]
@sekrett ... "I don't understand why I should care about boot process details"  ...  Yes, this is one of the current shortcomings with bhyve in general.   There is no general purpose "bios"  written for it, hence the need to literally run grub or bhyveload on the host.  Or run uefi...

Anyway I too ran into issues in the past with some older version of ubuntu on uefi...   The linux installer didn't put the EFI something-or-other in the expected place.  I don't remember if it was 16.04 or older, but [this](https://forums.freenas.org/index.php?threads/howto-how-to-boot-linux-vms-using-uefi.54039/) helped.   Newer linux distros I've used work as expected.

**Comment by cactus** [comment]
I wonder if `uefi-edk2-bhyve-csm`, which supposedly has legacy bios support, would be easier to use in some cases.

@nihr43 I have run into that as well, with a centos **update**! The upgrade removed a few files in /boot/efi, and I had to use the efi prompt to load the files manually, then fix the efi things after finally getting it to boot manually. What a pain!

**Comment by sekrett** [comment]
Finally I found the real problem. UEFI itself works well, I install any Linux, it boots. I can reboot any times I want, BUT if I shutdown the vm, it does not boot anymore. The reason is UEFI-bhyve does not persist settings on shutdown, but the path was (probably) set correctly before by installer. The easiest solution is to find the right EFI file which boots (type `exit` on console and go to menu "Boot from file", easy to find) and copy it to what is default path for UEFI: `/boot/efi/EFI/BOOT/BOOTX64.EFI`. I recommend to write a little script, because you will need to copy it again after upgrade.

This is not related to `vm-bhyve` but I think it should be documented in wiki to help people save time.

**Comment by dch** [comment]
Seeing similar problems here, 12.0-CURRENT, vm-bhyve 1.18 & debian9.4 amd64 netinst.

None of the options above seem to work, `vm console <name>` just drops me into grub loader.

config file is vanilla:

```
# /hive/.templates/debian.conf 
loader="grub"
cpu=1
memory=1024M
network0_type="virtio-net"
network0_switch="public"
disk0_type="ahci-hd"
disk0_name="disk0.img"
grub_run_partition="1"
grub_run_dir="/boot/grub"
```

the variants above dont' seem to work either, any ideas?

**Comment by sekrett** [comment]
@dch For latest version of Debian the recommended loader is UEFI.

**Comment by churchers** [comment]
As mentioned, please use UEFI if possible. It's a much better option than manual grub commands that depend on distro/version and may change after upgrades.

Unfortunately a known issue with bhyve is that EFI variables are not saved. Hopefully this will be implemented at some point....

**Comment by dch** [comment]
FWIW this is what I ended up with, works perfectly. I am keen to use UEFI in future but this was at least workable:

```
loader="grub"
guest="linux"
grub_run_partition="msdos1"
grub_run_partition="2"
cpu=2
memory=2G
network0_type="virtio-net"
network0_switch="public"
disk0_type=virtio-blk
disk0_name=disk0
disk0_dev=sparse-zvol
graphics="yes"
xhci_mouse="yes"
graphics_res="1024x768"
graphics_wait="no"
uuid="..."
network0_mac="..."
```

Many thanks @churchers for this "just right" feel tool!

**Comment by mzs114** [comment]
I prefer to avoid UEFI, I wanted simple MBR boot and the VM seemed to be waiting/stuck at bootloading state, thinking something is wrong in the configuration and after many changes to the VM config file I finally tried pressing return key and it worked, it was not obvious that the user needs to press a key, perhaps this can be note for users in the wiki(?).

Further I trimmed down the said configuration file(`/vm/deb0/deb0.conf`) to minimal(pasting it below), this was on FreeBSD 11.2-RELEASE with latest available packages installed using `pkg`.

Config file contents(note the commented out entries, they seem to have no effect)

`
loader="grub"
#guest="linux"
cpu=1
memory=1024M
network0_type="virtio-net"
network0_switch="public0"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid="system-generated-ID"
#grub_run_partition="1"
#grub_run_dir="/boot/grub"
network0_mac="system-generated-mac
`

OS and Package details:

`freebsd-version 
11.2-RELEASE-p4

pkg info | grep -i bhyve
grub2-bhyve-0.40_5             Grub-emu loader for bhyve
vm-bhyve-1.2.3                 Management system for bhyve virtual machines`
