### ISSUE TITLE
Gentoo install

### ISSUE THREAD

**Issue by rajil** [churchers/vm-bhyve#186]
Just want to leave this here. For gentoo install using minimal iso following is required in config:
```
grub_install0="linux /isolinux/gentoo root=/dev/ram0 init=/linuxrc  dokeymap looptype=squashfs loop=/image.squashfs  cdroot"
grub_install1="initrd /isolinux/gentoo.igz"
```

**Comment by rajil** [comment]
These kernel [options](https://wiki.gentoo.org/wiki/QEMU/Linux_guest#Kernel) need to be setup in the kernel for disk and network support.

**Comment by rafiks** [comment]
boot works for me instead of /isolinux
grub_install0="linux /boot/gentoo root=/dev/ram0 init=/linuxrc  dokeymap looptype=squashfs loop=/image.squashfs  cdroot"
grub_install1="initrd /boot/gentoo.igz"
