### ISSUE TITLE
Doesn't support alternative block devs

### ISSUE THREAD

**Issue by meabandit** [churchers/vm-bhyve#19]
Other block dev should be able to be used eg  /dev/zvol/zroot/demo

    disk0_name="/dev/zvol/zroot/owncloud-demo"

fails to boot because it appends that string to the vm_dir.
changing to:

    disk0_name="owncloud-demo"

and creating a soft link to /dev/zvol/zroot/owncloud-demo works.

Probably there should be some sort of mechanism to pass extra params to bhyve too.  Then some vm's needing some obtuse configuration can still be used in the framework.

**Comment by churchers** [comment]
Hi @meabandit,
I added this ability a few days ago If you're using a recent copy from GitHub.
Try the following:

    disk0_type="custom"
    disk0_name="/path/to/any/device/or/image/file"
