### ISSUE TITLE
Generate new MAC and UUID for cloned virtual machines

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#195]
I found it convenient to use `vm clone` instead of `vm image provision` to create new virtual machines from templates. The main reason is that `vm clone` is much faster than provisioning. However, cloned virtual machines has the same UUID and MAC address like their origin.

It would be nice to add a switch to `vm clone` command to force generating new MAC and UUID.

Related issue: https://github.com/churchers/vm-bhyve/issues/48

**Comment by mateuszkwiatkowski** [comment]
I found out that it is already implemented but me it doesn't work for me: https://github.com/churchers/vm-bhyve/blob/ae8c20b30b8de6156d0ae992b0710708df08507f/lib/vm-zfs#L305-L316

**Comment by churchers** [comment]
Yes, I may even remove the image commands at some point. A much better idea is to create "template" guests which are not used, then just clone them when needed.

Several parts of the code need to replace the uuid/mac of a guest. I've now added a basic `generalise` function which can be called wherever needed to remove any fixed ids from a guest. (These are generated at runtime if needed already)

I've done some basic tests on this with clone and the relevant config settings are removed.
