### ISSUE TITLE
Support for zvols?

### ISSUE THREAD

**Issue by tajh** [churchers/vm-bhyve#2]
Hi, thank you for you your scripts - exactly what I needed.

Q: Is anyone working on adding support for zvols?

It seems like a small amount (hehe) of rework around the $_disk bits for zvols ...

**Comment by churchers** [comment]
Hey, thanks for trying it out.

I was reluctant to add ZVOLs, as in years of using and supporting ZFS, I've seen various problems come up with them on the mailing lists that don't happen with normal datasets. I've also seen a few big bhyve users report that they get better performance by just using files.

Having said that, a lot of people want to use them, and it's not a big change. Most of it is supporting the additional configuration option, which may come in useful if I ever support any other type of backing store for the disks.

I have added a new configuration option which can be added to the templates:

    disk0_dev="zvol"

This can be "zvol" or "sparse-zvol". If it's missing (as it is in the existing templates), or set to any other value, vm-bhyve just uses a file as normal.

I would recommend changing the disk name in the template as well to remove the extension, so you don't end up with a ZVOL called "disk0.img":

    disk0_name="disk0"

Once the template has been updated, just use it as normal to create the virtual machine

    # vm create -t zvol-template-name -s XXG vmname

I've only given it a quick test but it seems functional.

**Comment by churchers** [comment]
Forgot to add, for now none of these changes are in the downloadable archive or latest release.

You'll need to pull a copy from GitHub master. (It's only lib/vm-core & lib/vm-zfs that have changed)

I'll leave this open until I've updated the vm-bhyve-latest.tgz archive

**Comment by churchers** [comment]
I've now update `vm-bhyve-latest.tgz`. There's no actual GitHub release that includes this as I'm not sure such a small change warrants another release, but you can download the tgz or checkout the raw files.

Obviously ZVOL is only allowed as the disk device type if you have already told `vm-bhyve` that you are using a ZFS dataset as the storage location and want to use ZFS functions:

    vm_dir="zfs:pool/my/vm/dataset"

**Comment by tajh** [comment]
Zvols support seems to be working perfectly - I adjusted my directory mapping to match the  pool/vms/vm/zvol pattern and it fit into my already running system using zvols perfectly!  Thank you!
