### ISSUE TITLE
Switch MAC collisions

### ISSUE THREAD

**Issue by nihr43** [churchers/vm-bhyve#201]
As per IF_BRIDGE(4), FreeBSD /only/ guarantees that bridge link layer addresses will be unique on the local machine.  I recently ran into address collisions between vm-bhyve switches on two of my machines, trashing arp tables and ultimately causing some downtime.

These two servers are identical hardware, near identically configured.  I'm not sure how FreeBSD chooses mac addresses for bridges, but I would guess that having identical servers is what led to this situation.  My workaround was to have switch::init() and switch::create() run net/macchanger to truly randomize the addresses.

Since vm-bhyve so heavily relies on bridges, and FreeBSD doesn't always guarantee unique MACs on bridges, I believe the vm-switch code should be randomizing MACs.

**Comment by ocochard** [comment]
I'm generating half part of my MAC addresses by converting "sysctl -n kern.hostid" into hexadecimal: It's not perfect but it's a small step for avoiding MAC collisions between VMs hosted on multiple bhyve hosts.

**Comment by nihr43** [comment]
Oh, thanks to [r305860](https://svnweb.freebsd.org/base?view=revision&revision=305860) ifconfig in 11 STABLE and therefore 11.2 has this built in, in a way that supposedly generates RFC compliant addresses.  Glad I found this, very useful.  I'm thinking vm-bhyve should check freebsd-version, and randomize bridge MACs by default.  Bad idea?

Looking at Red Hat's oVirt, their solution to this problem is to have the system as a whole keep track of mac address "pools", and its up to the administrator to allocate pools to different clusters/broadcast domains.  This seems over complicated to me.  Yes, pools would guarantee no collisions; but at 48 bits the chances are pretty low.  I'd think that if you've enough machines on one switched domain for it to be a concern, you've got bigger problems.

If I have some free time in the near future I'll implement this and put in a pull request.

**Comment by churchers** [comment]
For switches that create a bridge interface, I've added a call to `ifconfig <bridge> link random` if the host is 11.2+. I'm currently not doing this for "custom" switches under the assumption that if people want to configure their own bridge, we shouldn't override any of its settings.
