### ISSUE TITLE
NVME support

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#202]
https://t.co/PcgWlSVcKx
Anyone working on this new feature?

**Comment by churchers** [comment]
I'm not 100% sure what the use-case for this is. I've also been looking at the `virtio-scsi` support, which has recently been committed, but not sure of the specific need for that either.

**Comment by WanpengQian** [comment]
As bhyve-dev said in twitter: https://twitter.com/bhyve_dev/status/955684857522212866
The big carrot is Windows guest block i/o performance.

Recently I am running some VMs on top of INTEL optane SSD,  the AHCI driver performance cannot reach optane SSD performance. 

Using NVME driver will greatly increase guest disk io performance.

**Comment by churchers** [comment]
Ah ok, so the AHCI interface is holding back the disk performance of the guest. I wonder whether the virtio-blk interface has any specific limits.

When it's actually part of a release hopefully it will just be as simple as changing the `diskX_type` option.

**Comment by WanpengQian** [comment]
nvme emu is already on 12-CURRENT
https://svnweb.freebsd.org/changeset/base/335974

**Comment by churchers** [comment]
Don't have a 12 machine around, but it looks like it's been implemented in bhyve using the exact same device format as `virtio-blk/ahci-hd`,, so you can probably do the following -

    disk0_type="nvme"
    disk0_name="filename.img"

**Comment by churchers** [comment]
One interesting thing is that it supports the following device paths -

	accepted devpath:
		/dev/blockdev
		/path/to/image
		ram=size_in_MiB

So, although it probably doesn't have that many uses, it should be possible to do something like the following to create a ramdisk in a guest -

    disk1_type="nvme"
    disk1_dev="custom"
    disk1_name="ram=500"

They might of done this as it made testing easier, since nvme should out-perform standard disks or SSDs.
