### ISSUE TITLE
vm startall command does not work

### ISSUE THREAD

**Issue by emwe1** [churchers/vm-bhyve#207]
I have defined 2 vms. When starting them individually via "vm start name" everything works fine but when using the "vm startall" command I get "WARNING: "lede" does not seem to be a valid virtual machine": 

`root@fbsd:~ # vm list

NAME            DATASTORE       LOADER      CPU    MEMORY    VNC                  AUTOSTART    STATE
lede            default         uefi        2      192M      -                    No           Stopped
servers         default         grub        4      384M      -                    No           Stopped
root@fbsd:~ # vm start lede
root@fbsd:~ # vm list
NAME            DATASTORE       LOADER      CPU    MEMORY    VNC                  AUTOSTART    STATE
lede            default         uefi        2      192M      0.0.0.0:5911         No           Running (99756)
servers         default         grub        4      384M      -                    No           Stopped
root@fbsd:~ # vm stop lede
Sending ACPI shutdown to lede
root@fbsd:~ # vm list
NAME            DATASTORE       LOADER      CPU    MEMORY    VNC                  AUTOSTART    STATE
lede            default         uefi        2      192M      0.0.0.0:5911         No           Running (99756)
servers         default         grub        4      384M      -                    No           Stopped
root@fbsd:~ # vm list
NAME            DATASTORE       LOADER      CPU    MEMORY    VNC                  AUTOSTART    STATE
lede            default         uefi        2      192M      -                    No           Stopped
servers         default         grub        4      384M      -                    No           Stopped
root@fbsd:~ # vm startall
Starting "lede"...
/usr/local/sbin/vm: WARNING: "lede" does not seem to be a valid virtual machine
root@fbsd:~ # vm list
NAME            DATASTORE       LOADER      CPU    MEMORY    VNC                  AUTOSTART    STATE
lede            default         uefi        2      192M      -                    No           Stopped
servers         default         grub        4      384M      -                    No           Stopped`

As you see no machine gets started after issueing "vm startall". Unfortunately there is also no log entry regarding this so I'm seriously stuck here.
I came to this issue when trying to autostart the vm's via "vm_list" in rc.conf.

**Comment by anteract** [comment]
in /etc/rc.conf check the line
vm_list="lede servers"
does it look exactly like that?

**Comment by emwe1** [comment]
Yes, it looked like this. Currently I have only lede there. I tried several combinations, "servers" first, "lede" first, only "servers" and only "lede". The result was always the same. I got the message "WARNING: "vm_name" does not seem to be a valid virtual machine", where "vm_name" was the name of the first vm in "vm_list" and no vm was started.

Here is the actual bhyve section from my rc.conf.

    ###### kernel modules to load
    #
    kld_list="radeonkms amdtemp fuse libiconv libmchain cd9660_iconv msdosfs_iconv if_bridge if_tap nmdm vmm"
    ###### vm bhyve settings
    #
    vm_enable="YES"
    vm_dir="/vm"
    vm_list="lede"
    vm_delay="10"

But it should not be a problem with rc.conf as this also happens when using "vm startall" from the command line.

For completion here are the conf file for the vms.

lede:
```
guest="linux"
uefi="csm"
graphics="yes"
graphics_port="5911"
graphics_wait="no"
#xhci_mouse="yes"
#loader="grub"
virt_consoles="2"
cpu=2
memory=192M
utctime="yes"
debug="yes"
network0_type="virtio-net"
network0_device="tap0"
network0_mac="58:9c:fc:04:34:76"
network1_type="virtio-net"
network1_device="tap1"
network1_mac="58:9c:fc:06:1b:cc"
network2_type="virtio-net"
network2_device="tap2"
network2_mac="58:9c:fc:0e:15:0c"
disk0_type="virtio-blk"
disk0_name="lede-17.01.4-x86-64-combined-ext4.qcow2.img"
uuid="deef0131-314d-11e8-b249-00237dfd1833"
virt_random="yes"
```

servers:
```
guest="linux"
#uefi="cms"
#graphics="yes"
#graphics_port="5912"
#graphics_wait="yes"
#xchi_mouse="yes"
loader="grub"
#grub_install0="linux /arch/boot/x86_64/vmlinuz archisobasedir=arch archisolabel=ARCH_201712 ro"
#grub_install1="initrd /arch/boot/x86_64/archiso.img"
grub_run_partition="msdos1"
grub_run0="linux /vmlinuz-linux root=/dev/vda3 modules=ext4"
grub_run1="initrd /initramfs-linux.img"
grub_run2="boot"
cpu=4
memory=384M
utctime="yes"
debug="yes"
virt_random="yes"
network0_type="virtio-net"
network0_device="tap3"
network0_mac="58:9c:fc:01:72:7e"
disk0_type="virtio-blk"
disk0_name="servers.img"
uuid="efd0302d-3153-11e8-b249-00237dfd1833"
```

**Comment by emwe1** [comment]
After I had to reinstall the system because upgrading packages from ports left me with an unusable system (even single user did not work) now it works although I'm using the very same config (copied from the unusable system before reinstalling).
