### ISSUE TITLE
Gentoo fails to boot, grub2-behyve shows grub prompt

### ISSUE THREAD

**Issue by tnsasse** [churchers/vm-bhyve#208]
I am trying to install a gentoo guest, on FreeBSD 11.1 and vm-bhyve latest from ports. Followed the gentoo handbook and have created the following partition table via GPT:

    Model: ATA BHYVE SATA DISK (scsi)
    Disk /dev/sda: 34.4GB
    Sector size (logical/physical): 512B/131072B
    Partition Table: gpt
    Disk Flags: 

    Number  Start   End     Size    File system     Name    Flags
     1      1049kB  3146kB  2097kB  grub            bios_grub
     2      3146kB  137MB   134MB   ext2            boot
     3      137MB   2285MB  2147MB  linux-swap(v1)  swap
     4      2285MB  34.4GB  32.1GB  ext4            rootfs

Upon boot I am greeted with the grub prompt, which after reading in the docs, tells me that the grub config wasn't found. I can boot with the following commands:

    grub> set root='hd0,gpt2'
    grub> linux   /vmlinuz-4.9.76-gentoo-r1 root=/dev/sda4 ro
    grub> boot

My vm-byhve config looks like this:

    loader="grub"
    cpu=2
    memory=4G
    network0_type="virtio-net"
    network0_switch="public"
    disk0_type="ahci-hd"
    disk0_name="disk0.img"
    grub_run_partition="2"
    grub_run_dir="/boot/grub"
    uuid="162362c1-3667-11e8-a51b-ac1f6b62ccce"
    network0_mac="58:9c:fc:0a:94:35"

In the guest I verified the grub config:

    gentoo /boot # ls /boot/grub
    fonts  grub.cfg  grubenv  i386-pc  locale  themes

See [grub.cfg](https://github.com/churchers/vm-bhyve/files/1868367/grub.cfg.txt) for the contents, please. 

I am running out of ideas here, how to fix this. Thanks for advice :-)

**Comment by tnsasse** [comment]
An interesting observation: besindes the gentoo guest, I also have a debian guest, which boots just fine. It occurs that debian is using msdos partition tables, could that be the issue?

    Model: ATA BHYVE SATA DISK (scsi)
    Disk /dev/sda: 34.4GB
    Sector size (logical/physical): 512B/131072B
    Partition Table: msdos
    Disk Flags: 

    Number  Start   End     Size    Type      File system     Flags
     1      1049kB  33.8GB  33.8GB  primary   ext4            boot
     2      33.8GB  34.4GB  535MB   extended
     5      33.8GB  34.4GB  535MB   logical   linux-swap(v1)

**Comment by tnsasse** [comment]
Update, the gentoo machine boots with the following config:

    loader="grub"
    cpu=2 
    memory=4G
    network0_type="virtio-net"
    network0_switch="public"
    disk0_type="ahci-hd"
    disk0_name="disk0.img"
    grub_run_partition="2"
    grub_run0="linux /vmlinuz-4.9.76-gentoo-r1 d root=/dev/sda4 modules=ext4"

I still disklike the approach, as the kernel file name probably changes over time, and I don't want to change the grub_run0 parameter all the time, nor do I like to remember to put a symlink to /vmlinuz or similar. I'd much rather have the grub-mkconfig update the grub config and have grub2-behyve read it from there. Still struggling to understand, why the parameter works, but reading the config from /boot/grub/grub.cfg seems not to.

Other than that I am not seeing a login prompt on the gentoo guest, but I guess this problem is unrelated to the grub issue.

**Comment by edenist** [comment]
I'm having a similar issue as the last one you described here, but with attempting to boot into the void-linux live iso. The system appears to correctly find the /boot/grub/grub.cfg and does proceed to boot, but then I'm not seeing a login prompt at all.

Were you able to find a fix to the lack of a login prompt? [I've tried the usual, setting nomodeset etc but no luck so far]. I would like to avoid having to manually specify the entire grub.cfg in the vm bhyve config.

**Comment by iblis17** [comment]
@edenist try the grub `chainloader` command?

**Comment by mattragan** [comment]
I had this same issue installing Ubuntu 18.04.2 from the ubuntu-18.04.2-server-amd64.iso image where it would boot to the `grub> ` prompt and just sit there.  I was able to get around this by setting the root device and then load the grub config from there with:
```
grub_run_partition="2"
grub_run0="set root=(lvm/ubuntu--vg-root)"
grub_run1="configfile /boot/grub/grub.cfg"
```
