### ISSUE TITLE
Feature Request: Configurable VM process priority

### ISSUE THREAD

**Issue by shonjir** [churchers/vm-bhyve#209]
I've found that I need to be able to set the process priority of specific VMs (particularly when running virtualized firewalls) to manage resource contention between competing bhyve processes on the host.

My specific use case is that of a virtual firewall which is managing traffic shaping and prioritization contending for resources with a busier but less important VM.

It would be useful if there were a VM configuration option to specify a default process priority to be applied at VM startup.

**Comment by churchers** [comment]
I've added a `priority="x"` setting to configure the `nice` value for the bhyve process.

The value is directly passed to `nice`, with `0` being the default and having a range from `-20` (high priority), to `20`. According to the `nice` man page, `20` means a process only runs if the system is completely idle (probably never want that with a vm)
