### ISSUE TITLE
Request: default.conf should be installed by vm init

### ISSUE THREAD

**Issue by mzaki-jp** [churchers/vm-bhyve#211]
Just after `vm init`, as .template directory is empty, `vm create` fails as follows:

````
> vm create xxxx
/usr/local/sbin/vm: ERROR: unable to find template /tank/vm/test/.templates/default.conf
````

Maybe, it is as expected; however, I think it would be better if `vm init` installed `default.conf`.
The default template come with vm-bhyve can work without edit for bsd guests,
and we can edit it with `vm configure` after creation of VM.

Copying templates from /usr/local/share/examples/vm-bhyve should be an optional step, in my opinion, because the pathname implies they are examples and hence optional. 

Thanks in advance for your consideration.

**Comment by nihr43** [comment]
I agree.  I'll look at implementing this if I have some free time in the near future.  I'm thinking there must be a good reason why it is not this way already...

**Comment by churchers** [comment]
This makes sense. Without manually creating/copying `default.conf` new users will just get an error trying to run `vm create`.

This now looks for the example template and copies it if it doesn't already exist in `.templates`. 

Maybe `vm-bhyve` should be capable of creating a basic guest without needing a `default.conf`..., but this does the job.
