### ISSUE TITLE
Config for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by rajil** [churchers/vm-bhyve#216]
Here are the setting i used to install 18.04 using grub on FreeBSD-11.1,

loader="grub"
guest="linux"
cpu=1
memory=8192M
grub_run_partition="msdos1"
grub_run_partition="2"
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="/dev/zvol/ubuntu"
disk0_dev="custom"

**Comment by stratacast** [comment]
How did you partition your disk? Can't get it to work, always stuck on booloader state

**Comment by scornet256** [comment]
@stratacast Ubuntu 18.04 LTS works fine here using the default Ubuntu template, I dont use LVM for the disk partitioning.

**Comment by stratacast** [comment]
Huh interesting. I haven't been using LVM either. I can get it to install just fine but yeah, gets stuck at bootloader. Tried changing the grub boot partition config in the .conf file but that hasn't resulted in much success. Ubuntu 14.04-16.04 works just fine

**Comment by scornet256** [comment]
@stratacast Please share your configuration and software versions.

**Comment by stratacast** [comment]
Got it! I ended up having to remove the grub_run_partition line, and default configs didn't work. Here was my resulting configuration file:

```
loader="grub"
cpu=2
memory=2048M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid=""
network0_mac=""
grub_run_partition="2"

```

**Comment by Ofloo** [comment]
LVM works on this config

no need for extra configuration:

```
loader="grub"
cpu=3
memory=1024M
network0_type="virtio-net"
network0_switch="private"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
grub_run_partition="2"
```
