### ISSUE TITLE
auto snapshot before start vm?

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#226]
How about adding a config line, such as 
```
autosnap="yes"
```
When starting vm by ```vm start <vmname>```, vm-bhyve will take a snapshot for that vm in case you want to have a rollback.

**Comment by jasonbrowne** [comment]
That is a great idea, I would add a pruning schedule to get rid of them after so many days.

**Comment by churchers** [comment]
I'd rather not get too bogged down providing every possible feature. We're already at almost 6k loc in a shell script. Snapshots and subsequent pruning/etc is really more something for a dedicated ZFS tools to handle.

Having said that, I do see that, without full integration with guests ala VMWare tools (which isn't likely to happen), it's useful to be able to take snapshots of guests if they reboot, giving a fully consistent copy of the guest at that point.

I've had other requests for prestart/stop/etc scripts and so for the moment I've added support for a `prestart` config option in master to see how useful it is. Creating a snapshot of a guest can be done quite easily with the following setup. (Note this runs on first boot and restarts)

/guest-path/guest.conf

    ...
    prestart="take-snapshot.sh"

/guest-path/take-snapshot.sh

    #!/bin/sh
    vm snapshot -f $1

(The `-f` option being required as although the guest is stopped when the script runs, `vm-bhyve` still has it marked as locked)

The second argument to the script is the ZFS dataset and so it would be just as easy to use a dedicated ZFS snapshot management tool instead.

**Comment by Ofloo** [comment]
Here's a script that will only keep the last 3 snapshots

`prestart="/root/.bin/vm_pre_start.sh"`

/root/.bin/vm_pre_start.sh:
```
#!/bin/sh
/sbin/zfs list -t snapshot -o name | /usr/bin/grep -i ${1}'@' | /usr/bin/sort -r | /usr/bin/tail -n +3 | /usr/bin/xargs -n 1 /sbin/zfs destroy -r
/usr/local/sbin/vm snapshot -f $1
```
