### ISSUE TITLE
VMs won't start for a second time during the same boot

### ISSUE THREAD

**Issue by stratacast** [churchers/vm-bhyve#230]
As stated, the boot process is very flaky. At least for Linux VMs. I'm on FreeBSD 11.2, with vm-bhyve version: v1.2 (build 102070)

The first time I use a VM it works great, and then let's say I want to shut it down or restart it, the only way it will ever get out of the "Bootloader" state is if I reboot my computer. At that point, I can boot into the VM again, and then the process repeats.

**Comment by churchers** [comment]
What's the OS and guest template contents?

**Comment by stratacast** [comment]
Guest: Ubuntu 14.04 64-bit
Template: 
```
loader="grub"
cpu=2
memory=2048M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid=""
network0_mac=""

```

**Comment by stratacast** [comment]
Found out why. vm-bhyve would show that the VMs were stopped (this is after running a shutdown now from the guest), but they were in fact still operating in the background to some capacity:
```
 8773 root      101   0  6368  2264 R 95.8  0.0 20h53:57 cu -l /dev/nmdm-ubuntuTestBkps.1B
20760 root      101   0  6368  2264 R 95.8  0.0 21h03:41 cu -l /dev/nmdm-ubuntu1404.1B
```

If I go and kill the process, then I can start the vm again and all is good. So something in the stopping process isn't working right

**Comment by churchers** [comment]
If the VM is still running they you would see the bhyve processes, or possibly a device node for it under `/dev/vmm`.

From the output above it looks like you have connected to the guest console (which by default uses `cu`), and this console session has been left open. It's possible that having the console session stuck open may be stopping it from starting again, I'll have to test to make sure.

I personally prefer using `tmux` for accessing the guest console these days. Seems to work a bit better and I don't ever have trouble with the detach command (`Ctrl+B, D` in tmux) like I did with `cu`.

    pkg install tmux
    vm set console=tmux

**Comment by churchers** [comment]
> It's possible that having the console session stuck open may be stopping it from starting again, I'll have to test to make sure.

Hmm, well that doesn't seem to be a problem. If I connect the the console, shutdown the guest but never end the console session, I do see the `cu` command in process list as expected (Also twice like in your output but not quite sure why there's 2). The guest is fully shutdown at this point. However, I can start the guest again without any trouble and the guest boot shows up on the existing cu session.

This doesn't seem to be why you can't restart the guest. What does the `vm-bhyve.log` show when it tries to start the guest?

**Comment by stratacast** [comment]
Neat! I suddenly can't get it to reproduce...I can't confirm that this is the output I got on one of the failed startups, but this is the only "out of place" message I get in my `vm-bhyve.log` file:
`fatal; loader returned error 1`

I think what I will do at this point is give this another whack later today and see if I can get it to reproduce again

**Comment by churchers** [comment]
If it runs once but not a second time it doesn't sound like a problem with the boot settings, as that would affect the first boot as well.

If you can reproduce the same problem, try running in foreground mode to see if the loader outputs any errors.

    vm -f start guest

**Comment by handcode** [comment]
i agree, unless "first boot" was meant as 'the installation' ;-)

but as i said: it was just a guess as hanging bootloader is reproducable with ubuntu/debian and lvm without changing the -d opt for grub-bhyve

**Comment by stratacast** [comment]
I can confirm none of my VMs are using LVM, just plain old EXT4, but I'll update this if I can reproduce again
