### ISSUE TITLE
vm switch import customswitch bridge0 doesn't work

### ISSUE THREAD

**Issue by maackintosh** [churchers/vm-bhyve#234]
Hi

I am running freebsd jails with vnet and iocage on the same machine as i want to use vm-bhyve, so i have already created bridge0 and want to import it into vm-bhyve but:

vm switch import customswitch bridge0

doesn't work, is this a feature not working yet, or can you recommend another way to run iocage with vnet and vm-bhyve on the same host.

Regards,

Thomas

**Comment by churchers** [comment]
If you're using 1.2 or newer try the following -

    vm switch add -t manual -b bridge0 customswitch

**Comment by lebel** [comment]
I'm using bastille, the same doesn't working with bastille's embridge0. As a matter of fact, it didn't work with iocage's when I was using it. I kept getting the following:

↳ doas vm switch add -t manual -b em0bridge customswitch                                                             11.3m  dim. 2020-08-02 10h22
/usr/local/sbin/vm: ERROR: unable to configure switch of unknown type
 1  I  lebel@sulaco  ~/g/mysql-server   master  
↳ 

I'm using 12.1-RELEASE-p7. 

vm-bhyve-1.4.2
bastille-0.7.20200714

**Comment by Efiartes** [comment]
Same case here using IOCage:
```
odyssey # ~> vm switch add -t manual -b bridge0 public
/usr/local/sbin/vm: ERROR: unable to configure switch of unknown type
```

System info:
```
odyssey # ~> pkg info vm-bhyve
vm-bhyve-1.5.0_1
Name           : vm-bhyve
Version        : 1.5.0_1
Installed on   : Tue Apr 16 23:36:11 2024 CEST
Origin         : sysutils/vm-bhyve
Architecture   : FreeBSD:14:*
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD2CLAUSE
Maintainer     : churchers@gmail.com
WWW            : https://github.com/churchers/vm-bhyve
Comment        : Management system for bhyve virtual machines
Options        :
	BHYVE_FIRMWARE : off
	EXAMPLES       : on
	GRUB2_BHYVE    : off
	TMUX           : off
Annotations    :
	build_timestamp: 2024-04-09T07:01:59+0000
	built_by       : poudriere-git-3.4.1-1-g1e9f97d6
	port_checkout_unclean: no
	port_git_hash  : b3aa1ea86
	ports_top_checkout_unclean: no
	ports_top_git_hash: c5cd82114
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 243KiB
Description    :
A frontend for bhyve which provides the 'vm' command
Create/start/stop virtual machines easily
Bridged/NAT networking
BSD/Linux/Windows guest support

odyssey # ~> freebsd-version -kru
14.0-RELEASE-p6
14.0-RELEASE-p6
14.0-RELEASE-p6
```
