### ISSUE TITLE
Address on virtual switch bridge and defaultrouter

### ISSUE THREAD

**Issue by abishai** [churchers/vm-bhyve#236]
Hello.
I've noticed the new feature when configuring virtual switches. However, it's impossible to configure primary physical interface in such manner - system will have no default routing path.

For example,

```
switch_list="default"
type_default="standard"
ports_default="em1"
vlan_default="1"
addr_default="10.0.0.88/24"
private_default="no"
```

```
Internet:
Destination        Gateway            Flags     Netif Expire
10.0.0.0/24        link#4             U      vm-defau
10.0.0.88          link#4             UHS         lo0
localhost          link#3             UH          lo0
```

The reason is that defaultrouter is ignored as it's executed before vm init Probably, vm-bhyve should handle this situation.

Workaround is possible though - create em1.1 in rc.conf and add it to standard bridge without vlan and addr features.

**Comment by churchers** [comment]
This seems like a very awkward configuration. As I understand it you're putting the default gateway in rc.conf, but trying to configure the primary IP of the host via vm-bhyve, meaning that the host relies on vm-bhyve starting to have any network connectivity.

I would advise against relying on vm-bhyve to fully control the host networking. The host itself should have connectivity regardless of vm-bhyve, which should only be dealing with guest networking. If you need the host traffic tagged vlan 1 than I would configure this via `rc.conf`, then either attach that vlan interface to a vm-bhyve switch, or use a manual bridge.

**Comment by churchers** [comment]
Closing issue.
