### ISSUE TITLE
Boot from iSCSI Device

### ISSUE THREAD

**Issue by kakadoo** [churchers/vm-bhyve#237]
hi

i run an devuan(debian) system on an iscsi block device with kvm .
i would to like shift this to my new hardware with FreeBSD 11.2

so i connect the block device with the devuan installation by iscsid to my new bhyve server.
i figure out following

loader="grub"
cpu=4
memory=4096M
network0_type="virtio-net"
network0_mac="58:9c:fc:01:f3:1b"
network0_switch="lan"
disk0_type="virtio-blk"
disk0_name="/dev/da0"
disk0_dev="custom"
uuid="0fc235f5-a910-11e8-ae54-001517e72b95"

so if i say vm start devuan i see the grub menu with the devuan boot item but 
he dont boot the system, he keep at the grub menu.

can someone help me ?

holger

**Comment by churchers** [comment]
I'm not sure how much I can help as I don't have too much experience with Linux.
Is it a 64 bit guest?

Are you able to see the kernel/etc on the disk from the grub cli. What happens if you try to boot the guest manually from the grub cli.

**Comment by churchers** [comment]
Glad you got it sorted.

Note that the `cpu_*` settings will only work on FreeBSD HEAD as the code was recently committed and not in a release yet. Also I believe threads should be 1 or 2 although I've not had a chance to actually see what happens with higher numbers.
