### ISSUE TITLE
leftover vm lockfiles prevent vm autostart on host reboot

### ISSUE THREAD

**Issue by shonjir** [churchers/vm-bhyve#24]
VM lockfiles (run.lock) are left behind on host reboot, preventing vm autostart from occuring on host reboot.  This happens whether or not host is booted gracefully.

Manually removing lock file allows VM startup.

Suggested fix: Lock should be removed or ignored if VM isn't running on start (perhaps using /dev/vmm check?).

**Comment by churchers** [comment]
Are you rebooting the machine the 'correct' way, with `shutdown -r now`, or just using `reboot`?
The first method allows all application to run their own shutdown logic (and `vm-bhyve` should ask each vm to stop, then remove the lock file if the service stopped correctly), the second just sends a `kill` to everything running.

This has been discussed before and the main issue is that the lock files are primarily designed for larger shared-storage environments to stop the virtual machine being started on multiple hosts. We already do a check in `/dev/vmm` just to make sure a guest isn't running locally. Maybe I need the option to disable lock files for users who don't want or need that second level of protection.

I would however give the same advice I have done previously. Operating systems generally do not like being stopped uncleanly, and we don't have perfect control over how the FreeBSD host handles stopping processes on reboot/shutdown. I personally think it makes little sense to reboot a host that has known running virtual machines. Stop the guests first then shutdown/reboot the host.

**Comment by shonjir** [comment]
I may have gotten a bit lazy over the years :)  I almost never use shutdown -r because I'd never noticed a significant difference in the behavior.  

Regardless of the behavior difference between administrative use of reboot and shutdown, if the host experiences a power-fail the VMs will still fail to restart due to the leftover lock file.  That seems like a bug to me.

Since the lock file records the name of the machine holding the lock, this suggests that a small extra check might be in order.  If the name of the machine checking the lock matches the name recorded in the lock, then it should be safe to ignore the lock and rely on the /dev/vmm check.

I think this might solve the unclean restart issue while retaining the semantics in the larger environments you mentioned without needing any extra configuration to do the right thing.
