### ISSUE TITLE
Image create speed vs size trade offs

### ISSUE THREAD

**Issue by oodgaard** [churchers/vm-bhyve#248]
Hi Matt. Have you tested / considered other compression tools for use with 'image create' ? 

Test case. An ubuntu vm, fresh install and updated. All archivers used all available cpu cores, and were fed data with zfs send (like vm image create would)

xz -T0 : Size 703MB - time 3m 56s (part of base)
pbzip2 : Size 860MB - time 59 seconds (requires installing)
pigz : Size 931MB - time 22 seconds (requires installing)
zstd -T0 : Size 890MB - time 7 seconds (requires installing)
zstd -T0 -19 : Size 750M - time 2m 44s
zstd -T0 -22 --ultra : Size 663M - time 5m 52s (and >10x the memory of non ultra mode)

Perhaps this could be a configurable option in rc.conf or a .config/ file ? Some people don't want to wait :)

I could have some time to add that feature if you like.

**Comment by oodgaard** [comment]
that is the time for xz -T0

**Comment by churchers** [comment]
I didn't try any other utilities. `xz` was used as it's available without installing anything. In all honesty I don't really use the `image` commands much. They were added a long time ago as a first stab at the idea of being able to create and maybe publish/distribute guest images although I've never been 100% happy with the way it works.

I've added the ability in master to allow the compress/decompress utility to be set via global options.

```
# vm set compress=zstd decompress="zstd -cd"
# vm get all
SETTING             VALUE
console             tmux
compress            zstd
decompress          zstd -cd
```

Note that both the compress and decompress commands need to be specified as these may vary. With `zstd` I found I needed to specify `-c` to make it write the decompressed stream to stdout so I could pipe it into zfs. The decompress command is stored with the image so it can (hopefully) decompress correctly even if these options are changed.

**Comment by oodgaard** [comment]
Awesome work Matt. I'll give it a test.
