### ISSUE TITLE
Directly store an ISO on different datastore

### ISSUE THREAD

**Issue by Duffyx** [churchers/vm-bhyve#251]
Hello,

At the moment "vm iso URL" only supports downloading to the default directory $vm_dir/.iso
Can we make it so that we can specify -d (datstore name) so that vm can download the iso directly to that location? For example:

vm iso -d storage ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/10.1/FreeBSD-10.1-RELEASE-amd64-disc1.iso

This will download the iso and store it on the iso type datastore storage (which for me is the directory storage/software/OS).

Thanks

**Comment by churchers** [comment]
Thanks for the suggestion
I've added support for this to the master version

```
# vm data l
NAME            TYPE        PATH                      ZFS DATASET
default         zfs         /backup/vm                backup/vm
media           iso         /backup/iso     
# vm iso -d media http://ftp.uk.freebsd.org/pub/FreeBSD/README.TXT
/backup/iso/README.TXT                        100% of 4259  B  440 kBps 00m00s
# vm iso
DATASTORE           FILENAME
default             FreeBSD-11.2-RELEASE-amd64-disc1.iso
media               README.TXT
```
(Just used README.TXT here as it was a small file to test with)
