### ISSUE TITLE
Can not initialize on FreeBSD 11.2-RELEASE AMD Turion(tm) II Neo N54L

### ISSUE THREAD

**Issue by quexpl** [churchers/vm-bhyve#252]
I have a problem with the initialization of VM on my HP server Microserver. I used FreeNAS before and there was no problem with creating vms with vm-bhyve, so I suppose it is not a hardware problem. Now I'm running FreeBSD 11.2.

When I try to initialize vm-bhyve, I get the error message:
```
root@moon:~ # vm init
/usr/local/sbin/vm: ERROR: kernel vmm not initialised (no VT-x / AMD SVM cpu support?)
```

Tested on:
```
root@moon:/usr/src/vm-bhyve # vm version
vm-bhyve: Bhyve virtual machine management v1.2-p3 (rev. 102071)

root@moon:~ # vm version
vm-bhyve: Bhyve virtual machine management v1.3-devel (rev. 103024)
```

System info:

```
root@moon:~ # dmesg 
Copyright (c) 1992-2018 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
	The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
VT(vga): resolution 640x480
CPU: AMD Turion(tm) II Neo N54L Dual-Core Processor (2196.39-MHz K8-class CPU)
  Origin="AuthenticAMD"  Id=0x100f63  Family=0x10  Model=0x6  Stepping=3
  Features=0x178bfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,MMX,FXSR,SSE,SSE2,HTT>
  Features2=0x802009<SSE3,MON,CX16,POPCNT>
  AMD Features=0xee500800<SYSCALL,NX,MMX+,FFXSR,Page1GB,RDTSCP,LM,3DNow!+,3DNow!>
  AMD Features2=0x837ff<LAHF,CMP,SVM,ExtAPIC,CR8,ABM,SSE4A,MAS,Prefetch,OSVW,IBS,SKINIT,WDT,NodeId>
  SVM: NP,NRIP,NAsids=64
  TSC: P-state invariant
```

SVM is enabled in BIOS, and **I can easily create virtual machines using https://github.com/chyves/chyves**

```
root@moon:~ # ls -al /dev/vmm
total 1
dr-xr-xr-x   2 root  wheel   512 Oct  5 21:21 .
dr-xr-xr-x  10 root  wheel   512 Oct  5 23:09 ..
crw-------   1 root  wheel  0x92 Oct  5 22:09 chy-big-debbie
crw-------   1 root  wheel  0x80 Oct  5 21:21 linuxguest
```

**Comment by churchers** [comment]
Looks like the checks for virtualisation support are failing. Can you show the output of "sysctl hw.vmm"

On 1.3 you can try setting vm_disable_host_checks="yes" in rc.conf

**Comment by churchers** [comment]
At least you can get it working by bypassing the host checks.

In 1.3, we are currently checking `hw.vmm.vmx.initialized`, which in your case is 0. Looking at the description for the sysctl makes the reason for this obvious of course -

```
# sysctl -d hw.vmm.vmx.initialized
hw.vmm.vmx.initialized: Intel VMX initialized
```

Not sure why it wouldn't run with 1.2 without seeing the error message as that uses completely different checks.

I did try and asks the devs for a solid way to tell if a host will run bhyve or not, but didn't get very far. The general consensus seems to be I should remove all checks and just let bhyve error out if it can't run.
