### ISSUE TITLE
remove some options

### ISSUE THREAD

**Issue by Nitr0Filler** [churchers/vm-bhyve#255]
Hi ))

Search in wiki, but not found this information...
How remove some options from cmd line for bhyve ?

[bhyve options: -c 2 -m 6G -Hwl bootrom,/vm/vmbhyve/.config/BHYVE_UEFI.fd -U b8648838-a9d8-11e8-8704-d43d7e01b134 -u]
[bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,ahci-hd,/vm/vmbhyve/Win10PRO/win10.hdd -s 5:0,virtio-net,tap1,mac=58:9x:fw:0a:01:4a -s 5:1,virtio-net,tap11,mac=52:9a:cf:d0:26:ge -s 6:0,fbuf,tcp=192.168.212.7:5901,w=1024,h=768 -s 7:0,xhci,tablet]
[bhyve console: -l com1,/dev/nmdm-Win10PRO.1A]

Remove -u option
and
console

How, tell please ?

**Comment by churchers** [comment]
You can set `utctime="no"` to remove the `-u` flag. 

You could try setting `comports=""` to remove the console port, although I've not tested this so I'm not 100% certain there is nothing that relies on at least one console port being available. If you're not using the console port I can't see why it's really doing any harm for it to be there though.

**Comment by Nitr0Filler** [comment]
Thanks very mach )))
Yes, console does not interfere ))
