### ISSUE TITLE
Feature request: Creating virtual machines from cloud images

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#256]
Besides traditional ISO files, FreeBSD project releases Virtual Machines images:
http://ftp.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/. This is also true for some distributions of Linux.

While ISOs are fine for installing operating system to real computers I think that using prepared images for virtual machines is more convenient. The flow could be similar to ISO's:
```
# vm img add http://ftp.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/11.2-RELEASE/amd64/Latest/FreeBSD-11.2-RELEASE-amd64.raw.xz # vm downloads and decompresses the image to the datastore
# vm create -t freebsd-zvol -s 100G -i FreeBSD-11.2-RELEASE-amd64.raw freebsd-vm
# vm -f start freebsd-vm # we have working freebsd guest immediately
```

I have tested this manually and it worked as expected

### FreeBSD 11.2 ###
```
# fetch http://ftp.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/11.2-RELEASE/amd64/Latest/FreeBSD-11.2-RELEASE-amd64.raw.xz
# xz -d 11.2-RELEASE/amd64/Latest/FreeBSD-11.2-RELEASE-amd64.raw.xz
# vm create -t freebsd-zvol -s 100G freebsd-vm
# dd if=FreeBSD-11.2-RELEASE-amd64.raw of=/dev/zvol/zroot/vm/freebsd-vm/disk0 bs=1M
# vm -f start freebsd-vm
```
Tip: run /etc/rc.d/growfs onestart to expand filesystem
Default login: root and empty password

### Ubuntu 18.04 ###
Ubuntu produces cloud images. Unfortunately only in qcow2 format so the extra step is required.
```
# fetch http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-uefi1.img
# qemu-img convert -f qcow2 -O raw xenial-server-cloudimg-amd64-uefi1.img xenial-server-cloudimg-amd64-uefi1.raw
# vm create -t linux-zvol -s 100G ubuntu-vm
# dd if=xenial-server-cloudimg-amd64-uefi1.raw of=/dev/zvol/zroot/vm/ubuntu-vm/disk0 bs=1M
# vm -f start ubuntu-vm
```
Note: I didn't figure out default credentials yet. Seems that cloud-init is required by default. I'll followup on this later.

@churchers thoughts?

**Comment by mateuszkwiatkowski** [comment]
@churchers I created a pull request with partial implementation of this feature. This is work in progress but I decided to share early to get your feedback.

**Comment by mateuszkwiatkowski** [comment]
@churchers I think it's ready for review. Looking forward for your feedback.

**Comment by churchers** [comment]
Hi @mateuszkwiatkowski, thanks for the PR. Looks good with a quick read through.

I'll see if I can go through it in more detail today and get it imported.

**Comment by mateuszkwiatkowski** [comment]
@churchers, did you have a chance to take a look on this PR?

**Comment by mateuszkwiatkowski** [comment]
@churchers, I added a note about using cloud images to README.md.

**Comment by mateuszkwiatkowski** [comment]
Hi @frootmig,

Thank you for reporting the issue. The problem here is that your backing zvol is too small for FreeBSD image to fit in. It's reported by qemu-img. Please resize this zvol to, for example, 50GB and try again.
I don't know why FreeBSD image has so big filesystem in it. Maybe it's worh reporting this as a bug? Ubuntu and others are much, much smaller.

PS. I'm really happy that you're using this feature. :-)

**Comment by frootmig** [comment]
Hi @mateuszkwiatkowski,

thanks for your quick reply. This seems to refer to [FreeBSD Bug 232313](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232313). The ~30GB size is required. So using -s parameter on vm init call does the trick. The image should be that big. ;-)

Next up would be providing any cloud-init data to the VM. Have you ever tried this?

**Comment by mateuszkwiatkowski** [comment]
Yes, I've just created an issue for that to discuss the idea with @churchers and others: https://github.com/churchers/vm-bhyve/issues/289

I'll be happy to see your input there. :-)

**Comment by mateuszkwiatkowski** [comment]
I'm closing this issue as the feature is merged and works.

**Comment by molander** [comment]
Outstanding!!! Can't wait to test it out @ work, hopefully this weekend!
Thanks for doing this you guys! Maybe now I can stop raging @ (some) of the cloud :P

**Comment by mateuszkwiatkowski** [comment]
@molander thanks! That's motivating. :-)

**Comment by jasonbrowne** [comment]
Outstanding this is fantastic news!

**Comment by mateuszkwiatkowski** [comment]
FYI, default image size was reduced to 3GB: https://github.com/freebsd/freebsd/commit/bcc2f353aeb761b9d904e9c98701fa493cdc5988
