### ISSUE TITLE
Feature request - detailed guest/switch information

### ISSUE THREAD

**Issue by meabandit** [churchers/vm-bhyve#28]
So at this point I have a number of VM's managed by this tool and given the diversity in the networking setup it's getting rather difficult to easily figure out what is doing what on the networking side.

It would be great if functionality like:

```
vm list <name> / <all>
```
printed out the vm details / all vm details.

And/or if there was some built-in method of listing out vm nic(s)/switch(s)

Much of the interface here reminds of the Xen/xm days and in that vein I'm asking for:

 ```
xm network-list
```

**Comment by churchers** [comment]
I've been considering an `info` or `stats` sort of command for a while that can output a bunch of vm information. What do you think of something like the following from my dev version? I'm not sure if it's actually going too far...

```
# vm info fbsd
------------------------
Virtual Machine: fbsd
------------------------
  state: Running (10198)
  guest: freebsd
  uuid: b9d81b65-7263-11e5-8c2d-50e549369bc6
  uefi: no
  cpu: 1
  memory: 256M
  memory-resident: 56856576 (54.222M)

  network-interface
    number: 0
    emulation: virtio-net
    virtual-switch: public
    fixed-mac-address: -
    fixed-device: -
    active-device: tap0
    tag: vmnet-fbsd-0-public
    mtu: 1500
    bridge: bridge0
    bytes-in: 52076972 (49.664M)
    bytes-out: 7108 (6.941K)

  network-interface
    number: 1
    emulation: virtio-net
    virtual-switch: -
    fixed-mac-address: -
    fixed-device: tap6
    active-device: tap6
    tag: vmnet-fbsd-1-custom
    mtu: 1500
    bridge: *unavailable*
    bytes-in: 0 (0.000B)
    bytes-out: 0 (0.000B)

  virtual-disk
    number: 0
    device-type: file
    emulation: virtio-blk
    options: nocache,direct
    system-path: /data/vm/fbsd/disk0.img
    bytes-size: 21474836480 (20.000G)
    bytes-used: 380457984 (362.833M)
```

```
# vm switch info public
------------------------
Virtual Switch: public
------------------------
  type: auto
  ident: bridge0
  vlan: -
  nat: -
  physical-ports: re0
  bytes-in: 1299847482 (1.210G)
  bytes-out: 1278867167 (1.191G)

  virtual-port
    device: tap0
    vm: fbsd

  virtual-port
    device: tap2
    vm: win2012
```

**Comment by meabandit** [comment]
Yes, that's almost perfect in my view.  My nitpicks include:

* tag: should be renamed to description: or some abbreviation. 
  * That's what you get from ifconfig output 
  * When I think of networking tag I think vlan.
* Some method of getting all info should be present eg
```
vm info
------------------------
Virtual Machine: 1
------------------------
<etc>
------------------------
Virtual Machine: 2
------------------------
<etc>
```
```
------------------------
Virtual Switch: sw1
------------------------
<etc>
------------------------
Virtual Switch: sw2
------------------------
```

What do you think?

**Comment by churchers** [comment]
Yeah I already designed it to output all if no switch or vm name is listed.
I'll update the interface details to show description then commit it
