### ISSUE TITLE
Can't use UUID as machine name

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#281]
Default limit for name of virtual machine is 30 chars. I propose to bump that limit to 37 so that we can use UUIDs as names. We need this to integrate vm-bhyvee with our application.

@churchers what do you think?

**Comment by mateuszkwiatkowski** [comment]
@churchers I've just created pull request. Please take a look if you agree with it.

**Comment by mateuszkwiatkowski** [comment]
I've found that the limit is 32 chars in bhyve. I'll ask if it could be bumped. On vm-bhyve side, creation of vm works fine. It just can't be started. :-)

**Comment by churchers** [comment]
Yes I did think the limit was 32 as I had another request for longer names a while back on the mailing list. If there is an increase in base then it shouldn't be a problem increasing it here.

**Comment by mateuszkwiatkowski** [comment]
The limit has just been bumped: https://svnweb.freebsd.org/base?view=revision&revision=349948

**Comment by mateuszkwiatkowski** [comment]
@churchers ping :-)

**Comment by churchers** [comment]
This should be fixed with the increased 48 char name limit

**Comment by mateuszkwiatkowski** [comment]
Thanks!
