### ISSUE TITLE
disk0_dev="custom"

### ISSUE THREAD

**Issue by lvasiliev** [churchers/vm-bhyve#283]
Hello, thanks for your work!

We use disk0_dev="custom" and found a mistake.

bhv03# cat /pool/vm/.templates/relay-test.conf 
guest="relay-test"
...
disk0_type="virtio-blk"
disk0_name="/dev/zvol/pool/vm/relay-test/disk0"
disk0_dev="custom"

bhv03# vm create -t relay-test relay-test  
chmod: /pool/vm/relay-test//dev/zvol/pool/vm/relay-test/disk0: No such file or directory

Possible patch:
```
bhv03# diff -u /usr/local/lib/vm-bhyve/vm-core.orig /usr/local/lib/vm-bhyve/vm-core
--- /usr/local/lib/vm-bhyve/vm-core.orig        2018-07-30 12:54:22.000000000 +0300
+++ /usr/local/lib/vm-bhyve/vm-core     2018-12-20 18:41:10.794682000 +0300
@@ -162,6 +162,8 @@
             sparse-zvol)
                 zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
                 ;;
+            custom)
+                ;;
             *)
                 truncate -s "${_disk_size}" "${VM_DS_PATH}/${_name}/${_disk}"
                 [ $? -eq 0 ] || util::err "failed to create sparse file for disk image"
```

**Comment by churchers** [comment]
Thanks, didn't consider users putting custom disks in templates...
