### ISSUE TITLE
VM unable to access internet when using dnsmasq and a NAT switch

### ISSUE THREAD

**Issue by manasb** [churchers/vm-bhyve#29]
Hello,

I am running `vm: Bhyve virtual machine managament v0.9.13`
I have a switch which I have set to NAT mode:
```
# vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         -            igb0 tap0 tap1 tap2 tap3
natswitch       auto       bridge2     -         yes          -
```
The VM I am using is a Debian guest and it is set to use the `natswitch` switch. It gets a private IP address fine but I am not able to ping out onto the internet.
I have multiple IPs on my physical interface, so I am not sure how pf's NAT will handle the NAT instruction in pf.conf. I tried changing the line
```
nat on igb0 from {172.16.2.0/24} to any -> (igb0)
```
to
```
nat on igb0 from {172.16.2.0/24} to any -> $EXT_IF
```
then loaded the ruleset into pf, but I am still not able to access the internet. 
In `tcpdump` I see the traffic on the `bridge2` interface but I do not see any traffic leaving `igb0` to the `ping` command's destination.

Any tips would be appreciated.

Thanks,
Manas

**Comment by churchers** [comment]
Unrelated but the ports on your public switch look strange. Have you manually created and added `tap0-3` to it?

Anyway, back to the main problem. `$EXT_IF` is just a variable which will be unset unless you've actually defined it in the ruleset somewhere.

This webpage seems to suggest putting the WAN interface IP address into the rule may work.
http://funcptr.net/2011/09/08/nat-with-pf-on-an-interface-with-multiple-ip-addresses/

nat on igb0 from {172.16.2.0/24} to any -> 1.2.3.4 # The main IP on your WAN interface

**Comment by manasb** [comment]
Yes, I did manually add those in. I have a few guests running on plain bhyve from before and I guessed what the syntax would be, I wasn't sure if I would have problems or not if it wasn't populated. Should I remove the changes that I made? 

$EXT_IF is populated and I have tried with just entering the external IP itself but I do not seem to have any network access.

**Comment by churchers** [comment]
Ah ok, yes that should work fine.

I can't see any other reason why NAT shouldn't work although I haven't tested with multiple IP addresses on the external interface. Are you sure there's no other pf rules that might be stopping the traffic?

If you do have other rules I would first suggest trying with just the bhyve NAT rule. The easiest way to do that is just tell it to temporarily use the vm-bhyve rule file directly (add the below to `/etc/rc.conf` then run `service pf restart`)

    pf_rules="/path/to/vm/directory/.config/pf-nat.conf"

**Comment by manasb** [comment]
The issue is fixed. I changed the rule to redirect traffic to point at the external interface. Thanks.

**Comment by churchers** [comment]
Thanks for the update
Glad it's working

**Comment by herrbischoff** [comment]
> The issue is fixed. I changed the rule to redirect traffic to point at the external interface. Thanks.

@manasb: What exactly did you do (e.g. the pf.conf entry)? I have a similar issue and it's driving me nuts.

**Comment by herrbischoff** [comment]
@churchers: Can you help?
