### ISSUE TITLE
it doesn't look like your cpu supports bhyve (missing POPCNT)

### ISSUE THREAD

**Issue by kaanlab** [churchers/vm-bhyve#293]
I can't start vm in intel Q6600 processor. VT-x are enabled in BIOS.
`
~ vm init 
/usr/local/sbin/vm: ERROR: it doesn't look like your cpu supports bhyve (missing POPCNT)
`
use vm-bhyve-1.2.3
Dmesg output:
Copyright (c) 1992-2018 The FreeBSD Project.
Copyright (c) 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
        The Regents of the University of California. All rights reserved.
FreeBSD is a registered trademark of The FreeBSD Foundation.
FreeBSD 12.0-RELEASE-p3 GENERIC amd64
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1                                   )
VT(vga): resolution 640x480
CPU: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (2399.58-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x6fb  Family=0x6  Model=0xf  Stepping=11
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,C                                   MOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0xe3bd<SSE3,DTES64,MON,DS_CPL,VMX,EST,TM2,SSSE3,CX16,xTPR,PDCM>
  AMD Features=0x20100800<SYSCALL,NX,LM>
  AMD Features2=0x1<LAHF>
  VT-x: HLT,PAUSE

**Comment by churchers** [comment]
bhyve relies on Extended Page Tables, which first appeared in Nehalem processors around 2008. Based on a quick check it looks like your processor predates this and doesn't support it.

Bit of a pain, especially when the processor does have VT-x support, but bhyve is a fairly recent hypervisor and relies heavily on the CPU doing most of the grunt work. Unfortunately there's far too much work involved in implementing this stuff in software, especially when it's only going to be useful for 10+ year old processors and still be missing the years of bug reports and tweaks that went into making these software implementations perform half decent and reasonably bug free in other hypervisors.

In my case I have a couple of machines around I would like to run bhyve on, that do have EPT, but are slightly too old to support unrestricted guest, which means I can only run single CPU BSD guests :(

**Comment by kaanlab** [comment]
got it, thank you
