### ISSUE TITLE
Fresh 12.0p3 server, vm-bhyve, CentOS7, after install: error: not a correct XFS inode

### ISSUE THREAD

**Issue by mathiasp** [churchers/vm-bhyve#297]
With a fresh 12.0p3 Server, with vm-bhyve from pkg, I installed CentOS with the following template

```shell 
loader="grub"
cpu=2
memory=8G
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
grub_install0="linux /isolinux/vmlinuz LANG=en_US.UTF-8 KEYTABLE=us SYSFONT=latarcyrheb-sun16 console=ttyS0"
grub_install1="initrd /isolinux/initrd.img"
grub_run0="linux /vmlinuz-3.10.0-327.el7.x86_64 root=/dev/mapper/centos-root LANG=en_US.UTF-8 KEYTABLE=us SYSFONT=latarcyrheb-sun16 console=ttyS0"
grub_run1="initrd /initramfs-3.10.0-327.el7.x86_64.img"
```
and the following commands:
```
vm create -t centos7-zimbra -s 200G mail 
vm -f install mail CentOS-7-x86_64-DVD-1810.iso
```
This worked fine, the installer ran seemingly flawlessly until the end.
On reboot the following error showed up the first time,
then I existed the boot prompt ('c', 'halt') and rebooted with 'vm start mail'
but on the console (vm console mail) I got the same errors:

```
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: not a correct XFS inode.
error: file `/vmlinuz-3.10.0-327.el7.x86_64' not found.
error: you need to load the kernel first.
```
I tried again with a sparse zvol: same result

I had installed a freebsd guest before without problems.

Any idea where I can look for the problem?

Thanks, Mathias

**Comment by anteract** [comment]
First, I'm far from an expert, but you are definitely going to want to use the UEFI stuff, and even then, you probably aren't going to install anything past Centos7 release 1708.  But please, if you do, share here!

**Comment by bleakwind** [comment]
I have same problem.
Really hope someone can give some help.

**Comment by mathiasp** [comment]
Thanks for the tip with UEFI and 1708 version. Would be great if that was documented somewhere, all the templates use grub. 
How do I get a console in UEFI? This is on a remote server, I'm not keen on using VNC.

**Comment by mathiasp** [comment]
Oh, and I tried with just uefi=yes, and I get the boot prompt, but on Enter the screen blanks and stays that way...

**Comment by anteract** [comment]
You have to use VNC, sorry...  There isn't a "regular" console with UEFI.

**Comment by mathiasp** [comment]
Ok, so back to grub. VNC is a no go.
Works fine with Ubuntu 14...
