### ISSUE TITLE
ubuntu 14: grub boot menu not displayed, works with 'configfile (hd0,msdos1)/grub/grub.cfg

### ISSUE THREAD

**Issue by mathiasp** [churchers/vm-bhyve#298]
I just installed ubuntu 14 on a freshly instralled 12.0p3 system.

It seems to have worked, but I need to manually specify the grub.cfg before it boots.
Since my linux-fu is rather limited: what can I do so the system boots automatically?

Thanks, Mathias

This is the template I used to create the VM:
```
loader="grub"
cpu=2
memory=8G
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
disk0_size="200G"
```

**Comment by mathiasp** [comment]
Ok, in the grub command line I can see that prefix is (hd0,1)/boot/grub, but actually it should be (hd0,1)/grub, if I understand this correctly. The system shows the boot menu with 'configfile (hd0,1)/grub/grub.cfg'. So, how do I change where grub2 looks for it's config? I tried update-grub, followed by grub-install /dev/vda, both seemed to work, but I have the same problem. Can I somehow manipulate the prefix grub-install uses?

**Comment by mathiasp** [comment]
I found a workaround:
```
cd /boot
ln -s . boot
```
Now grub find /grub when it searches for /boot/grub. Not nice, but works for now(tm).

I'm really curious where I could change either
- the way grub sees the file system, e.g. sees (hd0,1)/boot where it now has (hd0,1)/
- the way grub looks for it's config, e.g. setting it's prefix to /grub instead of /boot/grub...
Any ideas would be nice. My current workaround is a bit... workaroundish ;)

Thanks,

Mathias

**Comment by churchers** [comment]
As you mention, `grub2-bhyve` looks for `/boot/grub/grub.conf` by default.
It should be possible to alter this using the following vm-bhyve guest config settings -

```
grub_run_dir="/grub"
grub_run_file="grub.conf"
```

(You probably wouldn't need the second option in your case as it defaults to `grub.conf`.
