### ISSUE TITLE
vm clone will create a snapshot everytime.

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#30]
if I use
```
vm clone guest guest1
vm clone guest guest2
```
vm-bhyve will create snapshot of guest first, then 
clone that snapshot to guest1/guest2

I think it would be nice to have a feature such as 
```
vm clone guest@snapshot guest1
```
for this command, clone will not create snapshot first, using the snapshot from first argc.
It will void creating useless snapshot every clone.

**Comment by churchers** [comment]
Good idea
It's now possible to do the following

    vm clone guest newguest
    vm clone guest@snapshot newguest2

**Comment by WanpengQian** [comment]
when clone by snapshot, vm is runing or not should not affect this operation.
I think check should be ignored.
```
root@vmhost01:/zones/vm/em43 # vm clone em43@base em00
/usr/local/sbin/vm: WARNING: em43 appears to be running on vmhost01.zteafter.local (locked)
```
