### ISSUE TITLE
About the CPU core assigned to the client.

### ISSUE THREAD

**Issue by bleakwind** [churchers/vm-bhyve#304]
About the CPU core assigned to the client

My computer has 8 cores, 32G memory, I built a windows7 client, allocated 4 cores, 8G memory, when the windows7 virtual machine client is installed, I found that the windows7 virtual machine only has 2 cores.

windows7.conf
```
loader="uefi"
cpu=4
memory=8G
ahci_device_limit="8"
utctime="no"

graphics="yes"
graphics_listen="0.0.0.0"
graphics_port="5900"
graphics_res="1600x900"
graphics_wait="auto"

disk0_type="ahci-hd"
disk0_name="disk0"
disk0_dev="sparse-zvol"
disk0_opts="sectorsize=512"

disk1_type="ahci-cd"
disk1_name=""
disk1_dev="custom"

network0_type="virtio-net"
network0_switch="bridge0"

```

vm-bhyve.log
>  5 02 12:47:01: initialising
>  5 02 12:47:01:  [loader: uefi]
>  5 02 12:47:01:  [cpu: 4]
>  5 02 12:47:01:  [memory: 8G]
>  5 02 12:47:01:  [hostbridge: standard]
>  5 02 12:47:01:  [com ports: com1]
>  5 02 12:47:01:  [uuid: 3e5f4997-6b1d-11e9-9f0e-8c164564f2dc]
>  5 02 12:47:01:  [utctime: no]
>  5 02 12:47:01:  [debug mode: no]
>  5 02 12:47:01:  [primary disk: disk0]
>  5 02 12:47:01:  [primary disk dev: sparse-zvol]
>  5 02 12:47:01: initialising network device tap0
>  5 02 12:47:01: adding tap0 -> bridge0 (bridge0 addm)
>  5 02 12:47:01: bring up tap0 -> bridge0 (bridge0 addm)
>  5 02 12:47:01: booting
>  5 02 12:47:01:  [bhyve options: -c 4 -m 8G -Hwl bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd -U 3e5f4997-6b1d-11e9-9f0e-8c164564f2dc]
>  5 02 12:47:01:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,ahci,hd:/dev/zvol/zroot/vm/windows7/disk0,sectorsize=512 -s 5:0,virtio-net,tap0,mac=58:9c:fc:02:f5:b2 -s 6:0,fbuf,tcp=0.0.0.0:5900,w=1600,h=900]
>  5 02 12:47:01:  [bhyve console: -l com1,/dev/nmdm-windows7.1A]
>  5 02 12:47:01:  [bhyve iso device: -s 3:0,ahci-cd,/vm/.config/null.iso]
>  5 02 12:47:01: starting bhyve (run 1)

**Comment by WanpengQian** [comment]
Yes, this is common problem when new to bhyve or FreeBSD.
you can add following setting to your loader.conf, add a reboot.
```
hw.vmm.topology.cores_per_package=4
```
Because Windows 7 only support 2 CPU sockets, in real world. so without this setting, when you set 4 CPUs to vm, that is 4 CPUs, each CPU has one core. not a CPU with 4 cores.
that is why Windows 7 only see 2 CPUs.
Linux/BSD or Windows Server will work fine.

**Comment by WanpengQian** [comment]
As new version of FreeBSD, bhyve alrealy support following configration:
```
# cpu (required)
# specify the number of cpu cores to give to the guest
#
cpu="1"

# cpu_sockets
# manually configure the number of sockets that bhyve should
# expose to the guest.
# note that sockets*cores*threads should equal the above cpu count
#
cpu_sockets="1"

# cpu_cores
# the number of cores to create per physical processor
#
cpu_cores="1"

# cpu_threads
# the number of cpu threads per core
#
cpu_threads="1"
```
please check ```/usr/local/share/examples/bhyve/config.samele``` for more details.

**Comment by bleakwind** [comment]
@WanpengQian Thanks, solved my problem...
