### ISSUE TITLE
Documentation for vm-migrate is missing

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#308]
I discovered that there's no documentation for vm send subcommand.

**Comment by anteract** [comment]
These notes will get you headed in the right direction.

https://gist.github.com/churchers/b5dc5ccb77d9096af56b84d0d1df20b9

**Comment by mateuszkwiatkowski** [comment]
Fixed by https://github.com/churchers/vm-bhyve/commit/0d5905bd69222602d2017df4afcec6e0dfd68200
