### ISSUE TITLE
Automatic MAC address assignment

### ISSUE THREAD

**Issue by churchers** [churchers/vm-bhyve#31]
Up until now `vm-bhyve` has worked like most other bhyve managers, and lets bhyve assign mac addresses to virtual interfaces (unless manually specified). According to documentation, bhyve uses the slot & function number, and device name to create a 'unique' mac address. There are a few problems with this:

* Guests on multiple hosts, using the same tap device number could end up getting the same mac address
* The mac address is prone to changing if a guest is restarted and gets given a different tap interface to the last time it ran. I expect this might cause problems for guests that consider an interface to be 'new' if the MAC changes (Windows?)

As such I believe the best solution is to assign a fixed mac address to each interface. Once set, the guest will see the exact same MAC permanently, regardless of device/slot/host/etc.

**Comment by churchers** [comment]
We now automatically create a static MAC for each interface when a guest is started (if one isn't already defined).

These are based on the FreeBSD bhyve allocation of `0x589cfc000001` - `0x589cfc00ffff`. The last 4 digits (32 bits) are generated automatically from the guest name, interface number and time. We only have these 32 bits to work with but hopefully that's enough to have a reasonable chance of creating unique addresses. Other than that we'd have to create some central database to keep track of it.

**Comment by WanpengQian** [comment]
how about vm clone?
currently, vm clone will generate a new UUID, but not the MAC. 
I think it should be the same behavior, generate new one both, or keep old one.

**Comment by churchers** [comment]
Good catch
I need to modify MAC addresses on clone.

**Comment by jasonbrowne** [comment]
Here is what we got to work, for changing mac addresses on VMs. 

https://docs.google.com/document/d/1tes3prRBUsqnEsO0xgOV7p9jvvakymr7UN40gX4AHUY/edit?usp=sharing

I
