### ISSUE TITLE
Creating VM from Cloud image cause system Crash

### ISSUE THREAD

**Issue by ole-db** [churchers/vm-bhyve#327]
On a fresh FreeBSD 11.2 system with updates creating a VM from FreeBSD cloud image will crash the system. Tested with master from github and 1.3 from ports.

vm-bhyve calls qemu-img which gets an unkillable process and writes to disk untill its full.

```
# uname -r
11.2-RELEASE-p14

# vm version
vm-bhyve: Bhyve virtual machine management v1.3-devel (rev. 103101)

# cat /vm/.templates/mytemplate
loader="bhyveload"
cpu=5
memory=32G

network0_type="virtio-net"
network0_switch="vm-net"

network1_type="virtio-net"
network1_switch="jails1

network2_type="virtio-net"
network2_switch="jails2

disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
disk0_size="32G"


disk1_type="virtio-blk"
disk1_name="disk1"
disk1_dev="sparse-zvol"
disk1_size="1024G"


# vm create -t mytemplate -i FreeBSD-12.0-RELEASE-amd64.raw jails2-dbconn-net
```

**Comment by ole-db** [comment]
If I run the commands by hand, it also crashes:
```
# zfs create -V32G -o volmode=dev cryptopool/vm/jails2-dbconn-net/disk0
# qemu-img dd -O raw if=/vm/.img/FreeBSD-12.0-RELEASE-amd64.raw of=/dev/zvol/cryptopool/vm/myvm/disk0 bs=1M
```

at first `zfs list` takes longer and longer, then the whole system does not response.

Any Idea what could be the problem?

**Comment by ole-db** [comment]
Ok, I solved it
```zfs set compression=on cryptopool```
did the trick. I understand why it is expanding to 32GB without. But not why machine goes crazy.

**Comment by mateuszkwiatkowski** [comment]
@ole-db maybe it's worth reporting the reproduction to FreeBSD's bugzilla?
