### ISSUE TITLE
Create next release to support 13.0-CURRENT

### ISSUE THREAD

**Issue by sarcasticadmin** [churchers/vm-bhyve#328]
## Description

Im running `13.0-CURRENT` with `vm-bhyve-1.3.0` from pkgng. I get the following due to `1.3.0` not checking for the combined `if_tuntap` module:

```
root@current:~ # vm init
/usr/local/sbin/vm: ERROR: unable to load if_tap.ko!
root@current:~ # kldstat -qm if_tuntap
root@current:~ # echo $?
0
```

I was able to work around this by during against `master` since it incorporates #305 but is there going to be a release soon to support this? A hotfix to 1.3 seems sufficient vs bumping to 1.4.

system info:

```
~ # uname -a -U
FreeBSD current 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r353072: Fri Oct  4 04:16:40 UTC 2019     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64 1300048
```

**Comment by kevans91** [comment]
Hi,

Just FYI- the lack of release should be worked around as of r353877, which completed the job that r351229 was supposed to do and make kldstat -m if_tap, for example, work correctly for applications that hadn't adjusted for the new name yet

**Comment by sarcasticadmin** [comment]
@kevans91 thanks for the heads up, Ill take a look after updating my install of CURRENT
