### ISSUE TITLE
failure to boot Ubuntu 15.04 VM copied from VirtualBox

### ISSUE THREAD

**Issue by cgull** [churchers/vm-bhyve#33]
I've got vm-bhyve 0.9.13 (??? there's no tag for this in the repo?) installed from packages on 10.2-RELEASE.  I copied this VM out of VirtualBox into a flat file. It's mostly working, but I can't get it to boot automatically in vm-bhyve.  The VM is currently running Ubuntu 15.04, but it's been around a while and it's upgraded from whatever the original install was, something between 12.04 and 13.10 probably.

The three issues I'm having:

* With `guest="ubuntu"`, grub-bhyve doesn't seem to pick up `/grub/grub.cfg` and boot automatically.  I think this is because it's looking for `/boot/grub.cfg` instead, but I'm not sure.

* When I try and use grub_commands, grub_bhyve doesn't seem to pick up the `configfile /grub/grub.cfg` I have in there.  It then hangs spinning when its redirected stdio hits EOF.

* This is all hard to debug with normal operation since `vm start` redirects to null and doesn't have a debug choice to redirect to a log file.  So I have to use `vm _run` by hand (not the worst thing, but I had to figure this all out).

So currently I have to do `vm start linux-apps`, then `vm console linux-apps` and then manually type `configfile /grub/grub.cfg`, and everything takes off from there.

Diffs between the install vm-bhyve and github master don't seem to show anything relevant.  Anything else to try before I start seriously hacking on this?

**Comment by cgull** [comment]
I noticed that I needed to do `set root=...` in my `grub_commands`, and it now works automatically.

More issues of note:
* I now think the Ubuntu boot is failing because that envar is not being set by anything, and grub-bhyve autoselects the wrong partition as root (this is an LVM install, with separate boot and root partitions)
* Needs documentation :)  (grub-bhyve needs it as well)
* The `__log` command for grub-bhyve invocation in `__guestpri_custom_grub()`, at least, is not up to date.  I suggest adding a `__log_and_exec` function so you only write those lines once.
* Redirecting grub-bhyve stdin from a file is going to cause pain on EOF.  I suggest redirecting from something that will keep stdin open as long as grub-bhyve is running, perhaps `(cat file; sleep 86400) | grub-bhyve`.

**Comment by churchers** [comment]
Hi @cgull 
Thanks for using `vm-bhyve`, and all the effort you've put into tracking down the problems you are having. Unfortunately Linux support is a bit ugly (both in `vm-bhyve` & `bhyve` itself) and is the one part of `vm-bhyve` I'm really not that happy with. (It doesn't help that I don't really use Linux myself).

Originally I pulled most of the grub commands from the few `bhyve` posts scattered around the net. Unfortunately it seems different install options can affect the required commands, and even slightly different versions of a distro can require changes. My original plan was to have each guest supported in `vm-bhyve' and make the guest boot without any additional configuration, just like FreeBSD & Windows do. (ironically Windows support which arrived in bhyve last month works flawlessly). Obviously that's not really feasible.

What I'm looking at now is the possibility of reducing the guest support in `vm-bhyve` to just `linux`, and adding configuration options (in addition to `grub_commands`) to allow install/boot commands to be specified, as well as `grub-bhyve` command line arguments. From there, making it possible to create templates that include these options, and come with the associated command files. This would allow `vm-bhyve` to start building up a database of templates for different distros/versions/configurations. It would then also be possible for users to start creating templates for different situations without requiring `vm-bhyve` to support them all directly.

Regarding some of your comments here, I am looking at adding a `-f` option to `vm start` to create a documented 'foreground' mode.

The last comment is interesting, I've so far been using a method similar to every other bhyve manager to pss in grub commands. I did try `(cat; sleep)` but it seemed to hang `grub-bhyve`. I'll have to do more testing. Getting that working in the first place was a bit of a nightmare - the only way I could get it to work on boot was with the `env -i TERM=xterm` prefix. Without that it would work perfectly from the console, but hang on 100% cpu during boot.

**Comment by cgull** [comment]
I hope to spend a little time this afternoon implementing some of that. 

And two more dumb ideas:  
- run grub on a pty
- if we could run grub interactively and capture input, and later play it back, that might simplify users bootstrapping odd OSes.

**Comment by churchers** [comment]
I'm closing off some old persistent issues that should be at least partially addresses by new grub code.
Feel free to comment or re-open if needed.
