### ISSUE TITLE
no VM console output on FreeBSD 12.1 host

### ISSUE THREAD

**Issue by cgull** [churchers/vm-bhyve#332]
I've been experimenting with vm for a little while.  It was working for me with 12.0, and I think 12.1-BETAs and -RCs, but is working less well for me now with 12.1-RELEASE.  With either nmdm or tmux console, I get console output from bhyveload, but none from the kernel once it starts.  If i set `debug=yes` in the config file, I see the output there, and from that I can see that console *input* works.  I think the VM is running normally otherwise, but I'm doing install/boot testing and I haven't exhaustively checked.  The same VM produces normal console output if I start bhyve manually in tmux.  IIRC I saw similar behavior with a Linux guest yesterday (output from grub-bhyve, none from guest).  I see this with both vm-1.3 from packages, or tag `v1.4.0` from github.

I suspect I might be doing something wrong somewhere but I haven't found it yet.

**Comment by drozdowsky** [comment]
flag -f does not work for me
workaround:
```
vm start guest
vm console guest 
```

**Comment by scornet256** [comment]
Im definitely not qualified to suggest a fix of some sort, but this helped me (for now).

```
/usr/local/lib/vm-bhyve/vm-run (from line 266) :

        # actually run bhyve!
        # we're already in the background so we just wait for it to exit
        bhyve ${_opts} \
              ${_devices} \
              ${_iso_dev} \
              ${_comstring} \
              # ${_name} >>"${_logpath}" 2>&1
              ${_name}
```

**Comment by anteract** [comment]
this all fails also without vm-bhyve, so its not really an issue for this project...  Not to say it wouldn't be nice of someone comes up with a fix.

**Comment by bsdxbsdx** [comment]
I think the cause is https://svnweb.freebsd.org/changeset/base/352720. I've been reverting it to fix vm-bhyve. If the change stays then I suspect vm-bhyve or whatever it uses internally will need to detect and compensate.

**Comment by anteract** [comment]
This change worked for me.  Thanks
