### ISSUE TITLE
bhyve uses over allotted memory

### ISSUE THREAD

**Issue by pestalent1** [churchers/vm-bhyve#340]
Lately my box has been locking up due to all memory being full (swap (10G) and real (32G)).
When I view the "system monitor" it shows my vm's in the stopped state and using more memory than allocated in the configs of each vm.
This a recent problem, that I believe happened after I upgraded 2 of the vm's from win7 to 8.1 (the 8.1 installs use the same config files as the 7's did). I also had updated my pkg 's.
I first noticed it when I was copying the .img files to a UFS formatted drive as backups. I thought is was a ZFS issue so added "vfs.zfs.arc_max="17G" to my loader.conf. (the problem also happened when just running vm's after that point)
I have 1.3.0 vm-bhyve on 12.1-RELEASE-p1 on a ZFS partition: "ryzen 7 1700 (overclocked to 3700Mhz, if that matters) 32 GB of ram on a MSI x370 Gaming Plus motherboard with the latest bios".
I use bhyve to run 3 vm's (all windows (2012r2 server(7G of memory) and 2 8.1 (each with 3G of memory)). My 8.1 installs were win 7 but recently upgraded to 8.1.
The vm .img are on a separate zfs formatted nvme drive.

**Comment by churchers** [comment]
This may be better off as a FreeBSD bug report.
vm-bhyve is just a front end to running the main `bhyve` executable and we don't really have any involvement with how bhyve guests use memory.
