### ISSUE TITLE
Cannot boot Debian iso

### ISSUE THREAD

**Issue by sachaz** [churchers/vm-bhyve#341]
Following https://github.com/churchers/vm-bhyve/wiki/Supported-Guest-Examples but they are not working for Debian.

My environment: FreeBSD 12.1 / vm-bhyve 1.3.0 / grub2-bhyve-0.40_7
I'm trying to boot the debian-10.2.0-arm64-netinst.iso 

my conf:
```
guest="linux"
loader="grub"
grub_run_partition="msdos1"
cpu=6
memory=2048M
network0_type="virtio-net"
network0_switch="public"
disk0_type="ahci-hd"
disk0_name="disk0.img"
uuid="31f09a4b-2a2e-11ea-8fa0-0cc47a9a9f36"
network0_mac="58:9c:fc:08:0c:92"
```
after the grub menu on Install I got the following message:
```
error: invalid magic number.
error: you need to load the kernel first.

Press any key to continue...
```
On grub console all seems to be all right:

```
grub> ls (cd0,msdos1)/       
boot/ boot.catalog css/ debian dists/ doc/ EFI/ firmware/ install/ install.a64/
md5sum.txt pics/ pool/ README.html README.txt README.mirrors.html README.mirror
s.txt
```
What I am missing ?

**Comment by sachaz** [comment]
ping ?

**Comment by sparvu** [comment]
I just tried debian 10 and it works just fine. 

```
NAME      DATASTORE  LOADER     CPU  MEMORY  VNC  AUTOSTART  STATE
debian10  default    grub       1    512M    -    No         Running (9391)
testvm    default    bhyveload  1    256M    -    No         Stopped
```

I have used this media: debian-10.2.0-amd64-netinst.iso

**Comment by sachaz** [comment]
Hooo my bad I was on a arm iso instead of amd64, sorry for the noise.
