### ISSUE TITLE
"can't find '/boot/entropy'" on FreeBSD 12.1 (host and guest)

### ISSUE THREAD

**Issue by apecat** [churchers/vm-bhyve#342]
I upgraded a host to FreeBSD 12.1 from 12.0. After the upgrade I get this error while running
`vm install -f luva FreeBSD-12.0-RELEASE-amd64-bootonly.iso`, selecting the normal Multi user boot.

`Loading kernel...`
`/boot/kernel/kernel text=0x1678a68 data=0x1cd288+0x768b40 syms=`
`[0x8+0x174cd8+0x8+0x19224a]`
`Loading configured modules...`
`can't find '/boot/entropy'`

I've tried using both 12.0 and 12.1 installers
https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.1/FreeBSD-12.1-RELEASE-amd64-bootonly.iso
https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.0/FreeBSD-12.0-RELEASE-amd64-bootonly.iso

Any advice or suggestions on more info I could provide?

**Comment by dch** [comment]
@apecat  TLDR I don't think this is a vm-bhyve issue. Just run `service random saveseed` to create these files, I believe it should be started by default as it's a dependency of `netif`, and I think it's also run on shutdown too.

Does your boot get past that point or not? If yes, the above will address the error. If not, this may be related to ACPI issues on certain CPU configs, see https://forums.freebsd.org/ for a number of posts.

See [random(4)](https://www.freebsd.org/cgi/man.cgi?query=random&sektion=4&manpath=FreeBSD+12.1-RELEASE) for details & [entropy](https://svnweb.freebsd.org/base/head/usr.sbin/bsdinstall/scripts/entropy?view=markup) for how it's created during install and [random](https://svnweb.freebsd.org/base/head/libexec/rc/rc.d/random?view=markup) for what's supposed to happen at startup/shutdown, and [rc.conf](https://www.freebsd.org/cgi/man.cgi?query=rc.conf) for a few tunables.

If you can replicate this on upgrade then please file a bug at https://bugs.freebsd.org/

**Comment by churchers** [comment]
As far as I'm aware this should only appear on the first boot then the file should be created. Either way it's nothing to worry about and not a vm-bhyve issue

**Comment by carepack** [comment]
Only for others, you'll see the stucking screen on boot/entropy if you, for example, assign a wrong disk. You want to install on a zfs dataset but in your config you point to a non existing disk0.img.
