### ISSUE TITLE
Configuration without hdd config. aka "incomplete virtual machine configuration"

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#344]
As with NVMe UEFI firmware support, we can run bhyve without a emulation of HDD.
UEFI firmware with NVMe boot support can get from below link.
[https://people.freebsd.org/~grehan/BHYVE_NVMe.fd.xz](url)

I manage to run bhyve without disk emulation support within vm-bhyve. but current version
of vm-bhyve has 2 checkpoint to forbid that. one in vm-core

```
 # check minimum configuration
    if [ -z "${_cpu}" -o -z "${_memory}" -o -z "${_disk}" ]; then
        echo "  ! incomplete virtual machine configuration"
        return 1
    fi
```

and one in vm-run

```
    # check basic settings
    if [ -z "${_loader}" -o -z "${_cpu}" -o -z "${_memory}" -o -z "${_bootdisk}" ]; then
        util::log "guest" "${_name}" "fatal; unable to start - missing required configuration"
        exit 15
    fi
```

After remove the check of HDD existence,  we can run windows 10 with a NVMe PCI passthrugh.
here is my test configuration
```
loader="uefi"
graphics="yes"
xhci_mouse="yes"
cpu=2
memory=8G
network0_type="e1000"
network0_switch="lan"
utctime="no"
passthru0="4/0/0"
```

```4/0/0``` is a Intel Optane 280GB 900P SSD, I can get the beremental performance of that drive within vm.

**Comment by churchers** [comment]
Thanks
I have added changes to allow guests with no bootdisk when using uefi
