### ISSUE TITLE
null.iso is not necessary now, can we have an option to disable it.

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#345]
when bhyve first support uefi boot, it should attach a null.iso, otherwise it will fail booting.
I found we can boot windows without it anymore.

I test following situations:

- a PCI passthru NVMe device, complete without any emu disk/cdrom

- a SATA emu disk only.

It is better to have an option to disable adding this null.iso automatically.

**Comment by WanpengQian** [comment]
I have open a pull request for this issue https://github.com/churchers/vm-bhyve/pull/347

**Comment by churchers** [comment]
New option for this added
