### ISSUE TITLE
Installing OpenBSD 6.6 with UEFI is not straight forward

### ISSUE THREAD

**Issue by bwegh** [churchers/vm-bhyve#351]
The problems I was facing:

1. No interactive console:

> vm install -f OpenBSD install66.fs

hangs and never shows any output from OpenBSD or the boot loader

2. Cannot connect to serial console with install

> vm install OpenBSD isntall66.fs

Seems to reboot at a certain moment and then boots without the install media (at least that is what it looks to me).

Question: Is there an easier way than the described procedure below?

--------------

The procedure to install OpenBSD on UEFI anyway needs two steps:

1. Installation using the following config

> 
> loader="uefi"
> cpu=1
> memory=512M
> network0_type="virtio-net"
> network0_switch="public"
> 
> install_slot="2"
> start_slot="3"
> disk0_name="../.iso/install66.fs"
> disk0_type="ahci-hd"
> disk0_dev="file"

> disk1_name="disk0"
> disk1_type="ahci-hd"
> disk1_dev="sparse-zvol"
> 

the `install_slot="2"` is needed to move the null.iso out of the way see https://github.com/churchers/vm-bhyve/issues/345
the `start_slot="3"` attaches the disk0 (install media) in the same way an iso would be added by vm-bhyve when using install.

Then 

> vm start OpenBSD
> vm console OpenBSD

works and the installation can proceed using serial console 

After the installation the configuration needs to be changed to:

> loader="uefi"
> cpu=1
> memory=512M
> network0_type="virtio-net"
> network0_switch="public"
> 
> disk0_name="disk0"
> disk0_type="ahci-hd"
> disk0_dev="sparse-zvol"
> 

now a normal

> vm start OpenBSD
> vm console OpenBSD

works

**Comment by churchers** [comment]
The main issue with getting output using foreground/interactive mode is likely due to a bug with redirecting bhyve output. This has been fixed and is in ports, but I'm not sure pkg has updated yet.

If needed this can be fixed manually by applying the fix in the below pull request.

https://github.com/churchers/vm-bhyve/pull/337

I'm currently looking at an option to disable the automatic addition of the `null.iso` file.

**Comment by bwegh** [comment]
the patch in the linked PR helped a lot, thank you very much.
