### ISSUE TITLE
mounting /dev/cd0

### ISSUE THREAD

**Issue by bhyve-user** [churchers/vm-bhyve#359]
I don't think this is a real "issue" but I can't figure out the right place to ask this question... I have a DVD device that is recognized as /dev/cd0 on the host.  I can put a DVD in this drive and mount it just fine within the host.  I've spent a lot of time trying to figure out how to have this /dev/cd0 visible to a Ubuntu 18.04 bhyve vm.  I could get into a lot of detail about the failed attempts to have my bhyve VM recognize /dev/cd0, but I'm hoping there is a straightforward way to do this and someone can tell me.  Thanks.

**Comment by churchers** [comment]
There isn't really a simple way you're going to be able to pass a cd device through to the guest that I can think of.

Unless I'm missing something obvious bhyve doesn't currently have a method of passing the host cd through to the guest like vmware workstation etc do.
