### ISSUE TITLE
How can I export vm machine to one file?

### ISSUE THREAD

**Issue by bleakwind** [churchers/vm-bhyve#361]
How can I export vm machine to one file?
Especially when use ZVOL?

Because i need backup to another file system.

**Comment by WanpengQian** [comment]
You can use zfs send.

something like
```
zfs send -R vm01@snapshot01 | <PROCESS BY PIPE, SSH, COMPRESS ETC.>
```

**Comment by bleakwind** [comment]
I thought vm-bhyve has a command.
I get what you meant, use zfs send.
Thanks.
