### ISSUE TITLE
bhyve and CentOS 8

### ISSUE THREAD

**Issue by kingfisher77** [churchers/vm-bhyve#367]
Hi, has someone installed successfully CentOS 8 with bhyve? Tried both grub and uefi - both got stuck on loader prompts.

**Comment by anteract** [comment]
This was fixed in https://github.com/churchers/vm-bhyve/pull/337

update vm-bhyve?

**Comment by tatuzemdp** [comment]
seems to work without any issues, this can be closed right?

**Comment by kingfisher77** [comment]
Yes, thank you.
