### ISSUE TITLE
Feature Request: add tmux/screens console support

### ISSUE THREAD

**Issue by misterfinster** [churchers/vm-bhyve#37]
Would anyone else like to use tmux and/or screens for console in addition to nmdm?

**Comment by WanpengQian** [comment]
Since you can start a tmux/screen and execute ```vm console VMNAME``` to catch the output of vm.
I can't catch the reason why vm-bhyve should add support to them.

**Comment by misterfinster** [comment]
Maybe i'm doing something wrong, but something i'm testing doesn't work with nmdm.  I'm on freebsd-11-current trying to bhyve pfSense-2.2.5.  When I start the vm console, the vm locks up and never boots - I can't even install from the fetch'd ISO.  When I start the vm console with com1=stdio, it works just fine.  If I script-fiddle the vm-bhyve scripts to only use tmux/stdio, all of my test cases work but now I'm diverging from these fine scripts.

**Comment by churchers** [comment]
I may look at adding support for stdio, so that a guest can just be run in a terminal and have the loader & bhyve run directly in the terminal.

Not a high priority but this should be fairly straight forward and quite useful for people who are happy to set up tmux/screen sessions and just want the guest to run directly without disappearing off into the background

**Comment by churchers** [comment]
Not sure if this is satisfies the original feature request, but I have added support for running guests in the foreground.

You can start a shell or tmux/screen/etc session, then use the `-f` option

    vm -f start guest

This runs both the bootloader (for bhyveload/grub-bhyve guests) and bhyve on stdio. I've tested this with a few guests and it actually works very well for something that only changed about 8 lines of code. Starting a freebsd guest you are presented with the bootloader, it then boots to the console, and on shutdown you are returned back to the host prompt.

Strange that you had problems with pfSense. I've tested 2.2.6 recently using the default template and it was pretty flawless. I also used the 'embedded' kernel option in the installer.

One thing I do notice with `cu`, which is used internally to connect to the nmdm console, you have to press `Enter` once connected for it to actually start doing anything. This is especially true with the Ubuntu installer, which seems to output nothing on screen, but will not boot into the installer at all unless you connect to the console and press `Enter`.
