### ISSUE TITLE
how to vm-bhyve ubuntu 20.04

### ISSUE THREAD

**Issue by ivr588** [churchers/vm-bhyve#375]
Hi,

host is 12-stable r362720 and vm-bhyve is 1.4.2. I've been trying to use ubuntu.conf to make a ubuntu20 guest. It all seems to install fine; however when it's shut down and rebooted I just get the grub prompt and don't know where to go from there. Any clues?

edit: ubuntu is ubuntu-server

thanks,

**Comment by eborisch** [comment]
You might be running into [this](https://www.ixsystems.com/community/threads/ubuntu-virtual-machine-no-longer-works.83737/) if you're using ahci-hd devices; try changing to virtio-blk.

**Comment by anteract** [comment]
Try the centos7.conf instead.  or fix the ubuntu one to use UEFI instead of GRUB.  All the VM's I have built lately pretty much run easier with UEFI.

Bonus, no fiddling around everytime there is a kernel update.
