### ISSUE TITLE
Bridge only works on one VM not on another

### ISSUE THREAD

**Issue by Quixus** [churchers/vm-bhyve#378]
So I configured switch as follows:
<details>
  <summary>Switch config</summary>
  
  ```root@NAS02:/etc # vm switch info
------------------------
Virtual Switch: rt-lan
------------------------
  type: standard
  ident: vm-rt-lan
  vlan: -
  physical-ports: lan igb1
  bytes-in: 482438233628 (449.305G)
  bytes-out: 1386079689604 (1.260T)

  virtual-port
    device: tap0
    vm: urbackup
  ```
</details>
And it is correctly applied to one VM
<details>
  <summary>VM1 Config</summary>

```
root@NAS02:/etc # vm info urbackup
------------------------
Virtual Machine: urbackup
------------------------
  state: running (67945)
  datastore: default
  loader: grub
  uuid: 5dd37708-c2a6-11ea-a263-e83935b1c8ca
  uefi: default
  cpu: 2
  memory: 2048M
  memory-resident: 1168134144 (1.087G)

  console-ports
    com1: /dev/nmdm-urbackup.1B

  network-interface
    number: 0
    emulation: virtio-net
    virtual-switch: rt-lan
    fixed-mac-address: 58:9c:fc:08:42:8f
    fixed-device: -
    active-device: tap0
    desc: vmnet-urbackup-0-rt-lan
    mtu: 1500
    bridge: vm-rt-lan
    bytes-in: 153993 (150.383K)
    bytes-out: 124480 (121.562K)

  virtual-disk
    number: 0
    device-type: file
    emulation: virtio-blk
    options: -
    system-path: /mnt/NAS02-1/vm/urbackup/disk0.img
    bytes-size: 21474836480 (20.000G)
    bytes-used: 3635123200 (3.385G)
```
</details>

but not to another

<details>
<summary>VM2 Config</summary>

```
root@NAS02:/etc # vm info bareos
------------------------
Virtual Machine: bareos
------------------------
  state: running (71245)
  datastore: default
  loader: grub
  uuid: 26a42ee0-c823-11ea-8ce5-e83935b1c8ca
  uefi: default
  cpu: 2
  memory: 2048M
  memory-resident: 648450048 (618.410M)

  console-ports
    com1: /dev/nmdm-bareos.1B

  network-interface
    number: 0
    emulation: virtio-net
    virtual-switch: rt-lan
    fixed-mac-address: 58:9c:fc:09:81:7e
    fixed-device: -
    active-device: tap1
    desc: vmnet-bareos-0-public
    mtu: 1500
    bridge: -
    bytes-in: 0 (0.000B)
    bytes-out: 463581 (452.715K)

  virtual-disk
    number: 0
    device-type: file
    emulation: virtio-blk
    options: -
    system-path: /mnt/NAS02-1/vm/bareos/bareosdisk.img
    bytes-size: 21474836480 (20.000G)
    bytes-used: 1205994496 (1.123G)
```
</details>

Obviously the second machine cannot connect to any outside host. 
What do I have to change to get a bridge for the second VM as well?

If you need additional information, please ask.

Thanks in advance for your help.

**Comment by mateuszkwiatkowski** [comment]
Can you show config files of these vms?

**Comment by Quixus** [comment]
Will do tomorrow, but except for the location of the vhd and its UUID they are identical.

**Comment by mateuszkwiatkowski** [comment]
Ok, so additional data would be helpful. Output of `ifconfig -a`, vm-bhyve log (it's located in vm's directory).

**Comment by mateuszkwiatkowski** [comment]
According to logs `bareos` vm tries to attach to switch `public`:
```
Jul 17 14:04:19: initialising network device tap1
Jul 17 14:04:19: failed to find virtual switch 'public'
```
Here's code that emits this message: https://github.com/churchers/vm-bhyve/blob/776ae8dac9c2567d94ac85b71e5aee8f2e7feb2e/lib/vm-run#L599

I don't know why this is happening but I think this should prevent booting the VM. @churchers What do you think?

**Comment by Quixus** [comment]
The vm boots, but it cannot make connections outside itself.

**Comment by mateuszkwiatkowski** [comment]
@Quixus which vm-bhyve version do you use?

**Comment by Quixus** [comment]
Good question. How do I find out?

**Comment by mateuszkwiatkowski** [comment]
`pkg info vm-bhyve`
please also show output of `freebsd-version -ku`.

**Comment by WanpengQian** [comment]
From the log, the problem vm never stop, boot first, then restart sereval times.

I think you use public switch from default conf, and then change to rt-lan, but you never stop the vm, so the update conf is never reread.

Just stop/poweroff the vm and start again, you will get the correct status.

**Comment by Quixus** [comment]
Thanks for your help everyone. 

Stopping the vm and starting it a gain did the trick. Is there a functional difference between vm stop <machine> && vm start <machine> and vm restart <machine>?

I don't think it matters anymore but vm bhyve version is 1.3.0 and the FreeBSD version is11.3-RELEASE-p9.

**Comment by mateuszkwiatkowski** [comment]
Stopping vm recreates the bhyve process with new parameters generated from config file. Reboot happens within the same process. 
That's another reason why I think `failed to find virtual switch` message should stop starting the machine.

**Comment by churchers** [comment]
Closing this as it appears to be solved.
The issue didn't make much sense as the config clearly listed `rt-lan` but the log showed vm-bhyve trying to connect to `public`. 

This would however make sense if the guest was never stopped. Currently, a reboot simply kills (`HUP`) the bhyve process and re-starts it. None of the devices (interfaces/etc) are removed/re-created and the config file is not re-read.
