### ISSUE TITLE
"-" in the name of the virtual machine doesn't seems to be processed correctly

### ISSUE THREAD

**Issue by nerozero** [churchers/vm-bhyve#382]
if the name of the virtual machine has "-" in the name, the remaining string including "-" is truncated for some reason.
```sh 
# vm list
NAME           DATASTORE  LOADER     CPU  MEMORY  VNC  AUTOSTART  STATE
freebsd_zweb   default    bhyveload  10   1024M   -    No         Running (9422)
freebsd-db     default    bhyveload  8    1024M   -    Yes [1]    Running (6557)
freebsd-zmail  default    bhyveload  4    1024M   -    Yes [2]    Running (3404)
```
now the switch:
```sh
# vm switch info public
------------------------
Virtual Switch: public
------------------------
  type: standard
  ident: vm-public
  vlan: -
  physical-ports: bge0
  bytes-in: 605848 (591.648K)
  bytes-out: 2168069 (2.067M)

  virtual-port
    device: tap3
    vm: freebsd_zweb

  virtual-port
    device: tap2
    vm: freebsd_zweb

  virtual-port
    device: tap1
    vm: freebsd

  virtual-port
    device: tap0
    vm: freebsd
```
as you can see - name in the "virtual-port->vm" is only "freebsd" if there is a "-" is used in the name.

not sure if this is intended, but .... 
Thanks

**Comment by churchers** [comment]
Hmm, the interfaces are given `vmnet-{guest}-{interface-index}-{switch-name}` as a description so it's possible to see exactly what each tap interface is doing in `ifconfig` output.

To create the info data we are simply looking through the `ifconfig` output and showing the second part of that string. 

I'll have to see if there's a way I can create a more intelligent regex that returns everything apart from the first and last two parts
