### ISSUE TITLE
Need to ensure the device exists before attempting to write to a newly-created zvol

### ISSUE THREAD

**Issue by arcologue** [churchers/vm-bhyve#392]
openzfs/zfs#8669: zvol devices are not necessarily available as soon as the command returns.

    # vm create -t example -i debian-10.6.2-20201124-openstack-amd64.qcow2 -C -k ./example.pub example
    qemu-img: /dev/zvol/zroot/vm/example/disk0: error while creating output image: Could not create file: No such file or directory
    /usr/local/sbin/vm: ERROR: failed to write img file with qemu-img
    # sleep 5
    # ls /dev/zvol/zroot/vm/example/disk0
    /dev/zvol/zroot/vm/example/disk0

**Comment by mateuszkwiatkowski** [comment]
Hi @arcologue,
Thanks for reporting the problem. Can you please reveal on which FreeBSD version are you seeing this?

**Comment by arcologue** [comment]
I ran into this on a fresh 12.2-RELEASE install. `sleep 5` was only illustrative, I think the actual delay was ≤1s, but I never measured it carefully before throwing a test-and-sleep loop at the end of `zfs::make_zvol` to verify it solved the issue.

Other hardware info: running on bare metal, E5-1620v2 processor, 2x16GB DDR3 ECC RAM. `zroot` was on a mirrored pair of HUS726T4TALA6L1 drives.

I no longer have the exact machine available because it's since been reimaged and is serving other tasks, but I can bring up a VM on similar hardware if desired.

**Comment by mateuszkwiatkowski** [comment]
@arcologue I'm sorry, I have never seen similar behaviour. I'm unable to assign resources to vm-bhyve currently but feel free to create a pull request and hopefully it would be merged by @churchers.

**Comment by churchers** [comment]
Looks like normally the create process just creates the zvol and does nothing to it until you start the guest so this issue would have never come up.

Using the image option, the code tries to immediately  write data to the new zvol device. I'll add a 2 second delay to the `write_img` function and ope that's long enough for the system to create the device node.

**Comment by quexpl** [comment]
I'm having the same error, and unfortunately 2 seconds is not enough for my server to create the device. After increasing time to 5 seconds it works again. See #424
