### ISSUE TITLE
[Question] Firewall tips

### ISSUE THREAD

**Issue by abishai** [churchers/vm-bhyve#40]
I have a problem with pf firewall. After reboot, my virtual hosts have no access to the world. I have to manually run pfctl -f /etc/pf.conf

I think this is because bridges and tap devices are not created at the time pf initializes itself. Any tips to work around the issue?

**Comment by WanpengQian** [comment]
you can use rcorder to check the rc order. maybe modify vm-bhyve start script to let vm start before pf.

But I don't think it is a good idea to do that.
better have some post script to execute after vm start.

**Comment by churchers** [comment]
Probably the easiest way to solve this in the short term is modify (hack) /usr/local/lib/vm-bhyve/vm-cmd.
In the section near the top that handles the init command, Add a new line just under the call to __switch_init and add the pfctl command.

I'll have to think more about how this can be handled in a way that can be part of the main code base.
