### ISSUE TITLE
Feature Request: ability to add tap device as a span member of bridge

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#41]
when add tap device to vm switch, currently only act as a normal member. by
```ifconifg bridge0 addm tap0``` command. while tap device can be a span member
by using ```ifconifg bridge0 span tap0```

we can specify this to vm config file. such as 
```
network1_type="virtio-net"
network1_switch="private"
network1_switch_member_type="span"
```
and then when execute vm start command, vm bhyve will add this tap device to bridge as a span member.

**Comment by churchers** [comment]
Never actually used the span option but this shouldn't be much of an issue to add. By the loo of it, it's for snooping the traffic on the bridge?

I'll look at adding a method of configuring this when I have time available

**Comment by WanpengQian** [comment]
Yes, I want to run tcpdump/wireshark inside VM and capture/analysis traffic inside VM.
Now I have a quick fix. add two tap devices to the same switch, one for normal member,
one for span member.

Actually, I think vm-bhyve need to have the ability when complex/flexible design can be done by extra configuration. such as 
```
network1_post_script="ifconfig $TAP xxx xxx"
```
in this case, we can do what ever we want.

**Comment by shonjir** [comment]
I'll add a "+1" to this - it would be very useful when setting up VMs as passive IDS.

**Comment by churchers** [comment]
Closing this for now as more unusual configurations can be achieved using custom bridges and tap devices. Please reopen if anything isn't working properly.
