### ISSUE TITLE
Graphics Template

### ISSUE THREAD

**Issue by fasxmut** [churchers/vm-bhyve#420]
I use "-t windows" to create graphics template for freebsd guest and some other os that supports uefi, maybe you should add three templates: best graphics, general graphics, low graphics.

**Comment by churchers** [comment]
Generally we recommend that the UEFI graphics are used mainly for initial setup and emergency access. It's very basic and low performance. Not sure on the current status but pci pass-through is the way to get decent graphics support.

All the various supported resolutions are listed in the sample config file so I think users can choose their own options depending on what they want to do.
