### ISSUE TITLE
Wiki: Add an entry for VirtIO 9p

### ISSUE THREAD

**Issue by jlduran** [churchers/vm-bhyve#421]
This is a very basic sample configuration for sharing files/folders with a VM using VirtIO 9p. I think it would be a handy addition to the Wiki.

### On the host's VM configuration file

    ...
    diskN_type="virtio-9p"
    diskN_name="sharename=/path/to/share"
    diskN_dev="custom"
    ...

Optionally, append `,ro` to `diskN_name` to make it read-only.

### On the guest

To mount it manually:

    # mount -t 9p -o trans=virtio sharename /local/mount/point/of/share

To mount it at boot (`/etc/fstab`):

    ...
    sharename          /local/mount/point/of/share    9p      trans=virtio,rw 0 0
    ...

**Comment by 0mp** [comment]
I've added the documentation to the wiki: https://github.com/churchers/vm-bhyve/wiki/Virtual-Disks

**Comment by jlduran** [comment]
Thank you!

**Comment by rj-hwang** [comment]
How to use this on Windows 10 guest?
