### ISSUE TITLE
Project governance

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [churchers/vm-bhyve#438]
Hi @churchers,

It seems that vm-bhyve became the go-to solution when it comes to managing virtual machines on FreeBSD. I very often see it as the first recommendation in many places yet it seems to be lacking manpower.
Would you like to assign more people to manage the project? I'd love to be a volunteer and help with maintaining and developing vm-bhyve.

**Comment by churchers** [comment]
Hi @mateuszkwiatkowski ,

Thanks for the interest in the project. I haven't been able to attend to it much over the past year due to work/covid and other personal issues. I've sent you an invite as it would be useful for others to be able to work on the code, apply fixes/PRs, etc.

**Comment by mateuszkwiatkowski** [comment]
@churchers many thanks for inviting me to the project. I'll try to help with keeping it alive. I hope you have all your personal  issues resolved. :-)
