### ISSUE TITLE
VNC Keyboard problem

### ISSUE THREAD

**Issue by luciovalentini** [churchers/vm-bhyve#444]
I would like to apply this patch
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246121

Can you help me?

`[bhyve][PATCH] Append Keyboard Layout specified option for using VNC.

When a guest OS is loaded using UEFI and connected with VNC, if the keyboard on the VNC client side is other than the US keyboard, some keys input may not be p
erformed correctly.
For example, if you press the '@' key on a Japanese keyboard, the number '2' will be entered on the guest OS.
The cause is that the '@' key on the US keyboard is assigned to Shift + '2' keys.
In addition, there is a problem that keys that do not exist on the US keyboard cannot be entered.
  (example, Zenkaku-Hankaku key in the Japanese Keyboard)

In the current bhyve(13-Current & 12.1-RELEASE-p3), in the virtual PS2 keyboard driver, there is a conversion table that converts from the key entered from the
 VNC client side to the virtual keyboard ScanCode for the Guest OS.
However, since this conversion table is set for US keyboards, the above problem will occur if the client side is not a US keyboard.`

**Comment by churchers** [comment]
This isn't really applicable here as we have no involvement with bhyve development itself, only the shell based frontend.
