### ISSUE TITLE
Add support to specify a BHYVE_UEFI_VARS file to -l for launching bhyve

### ISSUE THREAD

**Issue by driesmp** [churchers/vm-bhyve#449]
FYI; https://reviews.freebsd.org/D19976

```
bhyve -c 2 -m 4g -w -H \\
  -s 0,hostbridge \\
  -s 31,lpc -p com1,stdio \\
  -l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI_CODE.fd,BHYVE_UEFI_VARS.fd
```

So we need a way to specify a BHYVE_UEFI_VARS file in the VM config. 
This can store UEFI variables such as boot entries.

I think it makes sense for vm-bhyve to search in the respective vm directory for this file. 
The file has a specific template and is shipped with uefi-edk2-bhyve.

**Comment by churchers** [comment]
I've not had much of a chance to look into this yet.

I'm assuming we can create a copy of the provided file with the guest and pass the full path to that along? - e.g

`-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI_CODE.fd,/path/to/guest/BHYVE_UEFI_VARS.fd`

**Comment by driesmp** [comment]
Yea that should be sufficient. Maybe with an opt out/opt in config variable, like uefi_vars="yes" / uefi_vars="no". Depending on what you want as default.

**Comment by churchers** [comment]
I've added support for this that should work. I have tested that the `-l` option is updated correctly, but I don't have a recent enough build of bhyve to actually try running it.

It does make sense for this to be the default, but without an obvious way to check if bhyve supports the updated option syntax, for now it only applies if `uefi_vars="yes"` is set in the config file.

**Comment by driesmp** [comment]
I can test this on my server. I'm running 13-STABLE, needed code should be present.
Just a question around the naming of the copy; right now we make a copy to "uefi-vars.fd".

If I look at the above code, we try to keep naming consitent with whats in edk2-bhyve.
```
uefi-custom)
            **_bootrom="${VM_DS_PATH}/.config/BHYVE_UEFI.fd"**
           ;;
        *)
           _bootrom="/usr/local/share/uefi-firmware/BHYVE_UEFI.fd"
           ;;
```
Should be make a copy to BHYVE_UEFI_VARS.fd?

**Comment by driesmp** [comment]
> Thanks! I can test this on my server. I'm running 13-STABLE, needed code should be present.
Unfortunately this has never been MFCed to 13-STABLE. Given the 14-STABLE branch is not that far out I'll test as one of the first.

> Should the copy be made to "BHYVE_UEFI_VARS.fd"?
My question remains :-), now we still have some flexibility to change the default as not a lot of users are using it yet.
When 14 branches a lot more people can start using it.

**Comment by driesmp** [comment]
Yeah this works great, this is awesome. No more special care for efi vars for linux guest!
