### ISSUE TITLE
Feature request: vm_dir per VM ?

### ISSUE THREAD

**Issue by oodgaard** [churchers/vm-bhyve#45]
It would be great if there was a way to create VMs in a different data store than the default vm_dir. Perhaps this could be a command line switch that is then added to the global config ? Or, all your data stores are in rc.conf and only those can be selected on the cmd line ?

Scenario: I have an ssd as the main boot drive and some VMs are living there. But, I'd like to create file storage and caching VMs on a spiny disk.

**Comment by churchers** [comment]
Long time coming but this is now possible. `vm` now supports global options, the first of which is `-d` to specify a directory to override the value from `rc.conf`:

```
vm -d /some/path start myvmname
```
