### ISSUE TITLE
bhyveload vs uefi?

### ISSUE THREAD

**Issue by benoitc** [churchers/vm-bhyve#455]
What is teh difference between the 2 loaders byveload and uefi? It sees we can't have graphicboot with bhyveload. Why could an image boot  with byveload (but stop due to lack of grapical access) and uefi? 

When I arrive on UEFI I didn't find a way to disable PXE/CD boot or change the order before it boot. As I understand there are o such boot choice with the bhyveloader which may explain the difference I am finding.

**Comment by churchers** [comment]
`bhyeload` is the original loader for FreeBSD guests. It simply loads a BSD kernel into the guest vm and executes it. There is no BIOS or graphical devices so access is only via console. (Although it should in theory be possible to pass a GPU device to the guest and use that directly). I personally like `bhyveload` for FreeBSD guests as it is very quick and simple. I see little point in running through an entire UEFI boot firmware just to load a virtual machine.

The UEFI loader uses a third party UEFI implementation to emulate a normal UEFI boot process. This should (in theory) allow any operating system that supports UEFI to boot. However this does require the vm loading UEFI firmware, scanning devices for EFI bootcode, and running that to eventually get to the guest's own loader (similar to an old BIOS boot). UEFI has the option to provide a graphical device, which is implemented in the bhyve edk2 firmware so you get rudimentary graphics support.

Many of the bhyve managers have started to just standardise on UEFI as it means all the guests use the same boot process, simplifies the code & guest configuration, and allows VNC access to all guests (especially useful for web based managers)

Unless you have a bootable CD connected (usually via install mode in `vm-bhyve`) you shouldn't have any problem booting in UEFI. I have Windows guests with an empty CD device which just skip PXE/CD and boot of the virtual disk. I think it is possible to access the UEFI shell and choose a boot device, although it's not ideal to have to do this every boot.

**Comment by benoitc** [comment]
thanks for the answer!
