### ISSUE TITLE
How to run vm from non-root user?

### ISSUE THREAD

**Issue by rj-hwang** [churchers/vm-bhyve#460]
When I run vm command in non-root user, I get this error:

```
$ vm list
/usr/local/sbin/vm: ERROR: virtual machines can only be managed by root
```

**Comment by WanpengQian** [comment]
currently vm-bhyve needs root permission. you can using sudo to permit non-root user.

**Comment by churchers** [comment]
Unfortunately bhyve currently only runs as root. Hopefully this will change in the future and we can allow creating/starting/stopped guests as other users.
