### ISSUE TITLE
custom bhyveload options

### ISSUE THREAD

**Issue by avg-I** [churchers/vm-bhyve#462]
I would like to set some loader variables using -e option.
To be specific, I actually want to pass `-e smbios.system.uuid=${uuid}`.
Is it possible to do that?
If not, would it be a good extension?

**Comment by churchers** [comment]
You should be able to do this using the `bhyveload_args` config setting although there's no straight forward way of being able to use variables inside the config file.
```
bhyveload_args="-e smbios.system.uuid=xyz"
```

**Comment by avg-I** [comment]
Thank you for the suggestion.
I used:
```
bhyveload_args="-e smbios.system.uuid=$uuid"
```

In my opinion, it would be nice to have that as the default behavior.
But I am happy as long as there is a way to configure it.
