### ISSUE TITLE
Update of bhyve-firmware pkg - can't boot windows VM anymore

### ISSUE THREAD

**Issue by LightningRhino** [churchers/vm-bhyve#464]
Today there was an update of the bhyve-firmware package.
After the update my windows VM isn't able boot anymore.
According to the infos on freshports.org

> sysutils/edk2: Add bhyve as a new FLAVOR of edk2
> 
> Instead of having a separate sysutils/uefi-edk2-bhyve port, add bhyve
> as a FLAVOR of sysutils/edk2 and delete sysutils/uefi-edk2-bhyve.
> 
> To support existing users who depend on firmware in
> /usr/local/share/uefi-firmware create compatibility symlinks.

something changed.

I suppose the vm can't find the uefi firmware anymore and therefore crashes.

Anyone with similar problems?

**Comment by LightningRhino** [comment]
Can someone provide me with the
**/usr/local/share/uefi-firmware/BHYVE_UEFI.fd**
file from a version before the package was altered on may, the 25th?
I think with that file I would be able to resurrect my VM.

**Comment by arfycat** [comment]
I have the same issue.  Get the old package directly from the package repo - https://pkg.freebsd.org/FreeBSD:13:amd64/release_1/All/uefi-edk2-bhyve-g20210226,2.pkg for example.  You can extract the files using tar rather than actually installing the old package.  I copied the .fd files to my <bhyve>/.config directory and set loader to "uefi-custom" instead of "uefi".  Allows my Windows VMs and an Ubuntu VM to boot again.

**Comment by LightningRhino** [comment]
> I have the same issue. Get the old package directly from the package repo - https://pkg.freebsd.org/FreeBSD:13:amd64/release_1/All/uefi-edk2-bhyve-g20210226,2.pkg for example. You can extract the files using tar rather than actually installing the old package. I copied the .fd files to my /.config directory and set loader to "uefi-custom" instead of "uefi". Allows my Windows VMs and an Ubuntu VM to boot again.

Thank you. This is exactly what I was looking for.
Also the workaround with uefi-custom in the .config folder.
Will try that tomorrow. 
I hope the package will be fixed soon.

**Comment by LightningRhino** [comment]
@arfycat 
You are absolutely right. This is not an vm-bhyve issue. I posted here because this is where the knowledge is :)
Thank you for your help.
As this is no vm-bhyve bug, I am closing this and will keep an eye on the Bugzilla report.
