### ISSUE TITLE
dnsmasq fails to start up due to bridge0 absence on boot

### ISSUE THREAD

**Issue by aukaost** [churchers/vm-bhyve#47]
I'm trying to use a configuration with dnsmasq. When I reboot the machine dnsmasq fails to start up because the vm service has not created the interfaces yet. Any idea how I could make this work?

Jan 11 01:27:33 aukaost dnsmasq[594]: unknown interface bridge0
Jan 11 01:27:33 aukaost dnsmasq[594]: FAILED to start up
Jan 11 01:27:33 aukaost root: /etc/rc: WARNING: failed to start dnsmasq

**Comment by churchers** [comment]
You could try changing the rc.d script parameters as follows.

    REQUIRE: NETWORKING SERVERS
    BEFORE: dnsmasq

I was very cautious with the original settings and made it start very late. This will start it before dnsmasq, so the bridges should be set up before dnsmasq starts. I haven't actually tried it myself though..
