### ISSUE TITLE
New guest provisioned from old guest's image has identical UUID

### ISSUE THREAD

**Issue by tnalpgge** [churchers/vm-bhyve#48]
freebsdguest was installed from a FreeBSD-10.2 ISO as per the instructions in the vm man page.

```
[root@hesseth /vm/vm-bhyve]# vm image create -d freebsdimage freebsdguest
Creating a compressed image, this may take some time...
Image of freebsdguest created with UUID c6feaf0d-ba26-11e5-9985-000c29330a8b
[root@hesseth /vm/vm-bhyve]# vm image provision c6feaf0d-ba26-11e5-9985-000c29330a8b
[root@hesseth /vm/vm-bhyve]# echo freebsd*/freebsd*.conf
freebsdclone/freebsdclone.conf freebsdguest/freebsdguest.conf
[root@hesseth /vm/vm-bhyve]# grep -h uuid freebsd*/freebsd*.conf
uuid="987971a8-ba23-11e5-9985-000c29330a8b"
uuid="987971a8-ba23-11e5-9985-000c29330a8b"
```

Should the UUID of the newly-created guest really be identical to that of the guest from which it was created?  I realize that this probably doesn't have a lot of material effects on the operation of each individual guest, but the concept of uniqueness of UUIDs seems a bit abused here.

**Comment by churchers** [comment]
I probably added UUID to the configuration after implementing the provision command. Ideally I'll need to update the provision command to assign a new uuid to the guest.
