### ISSUE TITLE
Typo in info::switch_show()

### ISSUE THREAD

**Issue by SirDice** [churchers/vm-bhyve#486]
https://github.com/churchers/vm-bhyve/blob/07f96108eac52f60ecafd633da90fc9463ad0c99/lib/vm-info#L99

There's a comma that shouldn't be there. It causes a `local: _netgraph,: bad variable name` with `vm switch info`. Doesn't appear to cause any further issues.

**Comment by churchers** [comment]
Thanks SirDice, this has been fixed in PR #485
