### ISSUE TITLE
Scrubbing running VMs? 

### ISSUE THREAD

**Issue by GogoFC** [churchers/vm-bhyve#499]
So If I can't take a snapshot (or I shouldn't) of a running VM, I must first shut it down, then should I also not scrub VM's while they are powered on? I mean will the scrub work properly. I am very far from undersanding this still. I have done snapshots of running VM's via regular `zfs snapshot` command while Ubuntu was in the process of installing and then I forcefully shut it down, and yeah some data was lost, just wanted to see what would happen, it worked partly, it resumed with broken packages that needed to be fixed, but it rolled back. So what about the scrub?

**Comment by churchers** [comment]
Snapshots of a running vm are often called "crash consistent", which is not the greatest term but basically means the snapshot is effectively the same state as if the machine crashed.

When you take a snapshot, the disk is momentarily paused, snapshot is taken, then it resumes. If you boot up from this snapshot, as far as the guest is concerned, it looks exactly as if the machine had instantly been powered off when the snapshot was taken. Obviously this happens in real life with power loss and computers will *usually* boot fine. The biggest issue is possible corruption or loss of data that was being written at the time. Most filesystems will do some sort of recovery process on boot.

During install is a bad time to test this as it's obviously in the process of doing a large amount of disk writes, and installers are not generally written to care about resuming or dealing with a failed install. It will likely try to boot into the new installation and have no idea that some of the files weren't copied - you'll normally be expected to just start the installation again if it didn't complete.

Personally I take snapshots of running guests all the time. The majority do very little writing to their own disks (pretty much just logs) and all my user data is on network storage that is backed up independently. 

A scrub is completely different. You are simply looking at the data on disk to make sure it still matches its checksum and hasn't become corrupted. There is no issue with doing this while guests are running.

**Comment by GogoFC** [comment]
Hey I just saw this, thanks for answering in detail and making a distinction from how scrub operates. It makes sense now and everything is clear after I had read the last sentence that scrub just compares checksum against data even though I knew it does that but there was no way I could have come up with an answer because my mind I had overanalyzed it. So thanks for simplifying it.
