### ISSUE TITLE
Does this use QEMU?

### ISSUE THREAD

**Issue by TeknosQuet** [churchers/vm-bhyve#518]
I'm aware that this program uses QEMU to make a .img file (if I'm not mistaken), but other than that, I'm not sure what else it is being used for. Is it used in part to actually run the VM alongside bhyve, like how KVM/QEMU works? Sorry if this is the wrong place to ask this question.

Thanks.

**Comment by antranigv** [comment]
Hey @TeknosQuet , that's a good question if you're new here :)

No, QEMU is used only for image management if needed because `bhyve` runs only raw images.

I hope that clears it up.

**Comment by TeknosQuet** [comment]
I see. Thanks for the help!
