### ISSUE TITLE
"ERROR: ZFS support requested but ZFS not available" when zfs is compiled into the kernel

### ISSUE THREAD

**Issue by Mask66** [churchers/vm-bhyve#53]
Hi,

I have an FreeBSD 10.2-STABLE #0 r292683 amd64 with zfs compiled into the kernel.
On "vm init" I get "ERROR: ZFS support requested but ZFS not available".
Looking at vm-zfs, I noticed that the the script only checks, if the kernel module is loaded:
        # check zfs running
        kldstat -n zfs >/dev/null 2>&1
        [ $? -ne 0 ] && __err "ZFS support requested but ZFS not available"

Adding "-m zfs" to the line seems to work, and _should_ also find a loaded kernel module, but I can't test it.

Should I also (or instead) open an issue for the port on bugzilla?

Patch attached
[vm-zfs.patch.txt](https://github.com/churchers/vm-bhyve/files/93458/vm-zfs.patch.txt)

**Comment by churchers** [comment]
Don't see any need to open a bug in FreeBSD for this.
On my machine with the module loaded `-m` seems to work fine so I'll commit the change.

```
# kldstat -qm zfs
# echo $?
0
```

**Comment by Mask66** [comment]
If you would also kindly update the port (as you are listed as the maintaner), that'd be perfect. Also, many thanks for this nice set of scripts, it finally made me abandon Virtualbox (Windows-based) for my virtualization needs.
