### ISSUE TITLE
Ubuntu 24.04 guest requires the grub run partition setting

### ISSUE THREAD

**Issue by patterns** [churchers/vm-bhyve#550]
Starting with the Ubuntu 24.04 server (amd64 ISO) the installation completes successfully. This is using the suggested ["Debian and Ubuntu (Grub)" section on the Wiki page](https://github.com/churchers/vm-bhyve/wiki/Supported-Guest-Examples)  However when rebooting, the system stops at the Grub bootloader.

The solution was to change from "msdos1" to "2" for the `grub_run_partition` value as described on this page :  https://www.davd.io/install-ubuntu-on-freebsd-with-bhyve/

**Comment by GogoFC** [comment]
You can use UEFI and add `uefi_vars="yes"` with Debian and it will work, no need to edit partition locations. On Ubuntu uefi variables aren't needed but it doesn't hurt. 

This is what I use for Ubuntu

```
loader="uefi"
cpu=4
memory=4096M
network0_type="virtio-net"
network0_switch="public"
graphics="yes"
xhci_mouse="yes"
graphics_res="1600x900"
zfs_zvol_opts="volblocksize=128k"
disk0_name="disk0"
disk0_dev="sparse-zvol"
disk0_type="virtio-blk"
uefi_vars="yes"

```

**Comment by patterns** [comment]
Thank you, very helpful !
