### ISSUE TITLE
vm init can't find nmdm if it's compiled into the kernel

### ISSUE THREAD

**Issue by Mask66** [churchers/vm-bhyve#56]
Same as in issue #53 : kldstat -m instead of kldstat -n in vm-common fixes it.
Also, could you pretty please update the port?
Thanks.

**Comment by churchers** [comment]
I have updated the code so any module should be picked up correctly if compiled into the kernel.
Getting the ports tree updated can be a pain but I'll get it submitted as soon as I can.
