### ISSUE TITLE
Feature Request: add cpu resource limit over RCTL

### ISSUE THREAD

**Issue by ramdaron** [churchers/vm-bhyve#57]
bhyve may limit the guest OS in the number of CPU cores and RAM. But sometimes it is necessary to limit the guest not only by the number of cores. You can use the limitation of resources through RCTL: https://wiki.freebsd.org/SummerOfCode2012/CPULimits

Also restrictions will be added soon to the disk subsystem: https://wiki.freebsd.org/RudolfTomori/IOLimits

Can you add a resource limit function? This will require a new settings in the config file and transfer bhyve's PID as a parameter for the RCTL.

**Comment by churchers** [comment]
Been a while but I've finally got round to committing the pull request for this.
I've tried to simplify the code but it could do with a bit of testing
