### ISSUE TITLE
Bug: network info bytes in/out are incorrect

### ISSUE THREAD

**Issue by ramdaron** [churchers/vm-bhyve#62]
My system:
```
uname -ri
10.2-RELEASE-p9 GENERIC
freebsd-version
10.2-RELEASE-p12
```
In netstat output info about in/out bytes in columns 8 and 11:
```
netstat -biI "bridge0"
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll
bridg  1500 <Link#4>      02:d7:73:80:6f:00 10368111     0     0 5313151200 18655683  4496 13320749763     0
```
But 'vm switch info' get info from columns 7 and 10
```
vm switch info | grep bytes
  bytes-in: 0 (0.000B)
  bytes-out: 4496 (4.390K)
```
`_stats=$(netstat -biI "${_bridge}" |grep '<Link#' | tail -n1 | awk '{print $7,$10}')`

Also, the same in 'vm info vm_name':
```
vm info freebsd | grep bytes
    bytes-in: 0 (0.000B)
    bytes-out: 0 (0.000B)
    bytes-size: 21474836480 (20.000G)
    bytes-used: 16225059840 (15.110G)
```
```
netstat -biI "tap0"
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll
tap0   1500 <Link#5>      00:bd:4e:36:b3:00      355     0     0      43722     5519     0     475060     0
```
`_stats=$(netstat -biI "${_id}" | tail -n1 | awk '{print $10,$7}')`

I'm not shure, that netstat output not changes in some version FreeBSD, but in 10.2 and 11-CURRENT they are identical. It may be necessary to add a check to the version FreeBSD.

**Comment by oodgaard** [comment]
I see the same issue.

freebsd-version
10.2-RELEASE-p10

 netstat -biI "tap1"
Name    Mtu Network       Address              Ipkts Ierrs Idrop     Ibytes    Opkts Oerrs     Obytes  Coll
tap1   1500 <Link#10>     00:bd:6c:34:00:01  1010415     0     0  291274477  1048231     0  332329120     0

netstat -biI "tap1" |grep '<Link#' | tail -n1 | awk '{print $7,$10}'
0 0

netstat -biI "tap1" | grep '<Link#' | tail -n1 | awk '{print $8,$11}'
291274477 332422824

**Comment by churchers** [comment]
Hmm, I seem to get an empty `Address` column on my dev machine in both instances (for both the `tap` and `bridge` interfaces). I'll have to see if I can account for the Address column being blank or having a value, although I can't see any obvious way of doing that at the moment...

**Comment by churchers** [comment]
I'm hoping this is fixed.
As the number of fields is different depending on whether the `Address` field has a value or not, it's impossible to know what number columns the in/out bytes are in.

I'm not attempting to reverse the order of the columns, so that `Coll` is first. As the last columns are all numeric, and appear to default to 0, this should mean the in/out bytes are always in columns 2 & 5.
