### ISSUE TITLE
Arch Linux does not boot automatically

### ISSUE THREAD

**Issue by manasb** [churchers/vm-bhyve#66]
I'm not sure what I should be using as my 'guest' setting when running Arch Linux.

I used:
```
guest="arch"
cpu=2
memory=1024
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
```

But the VM does not boot automatically. It seems to get stuck at the 'grub>' prompt where I have to manually enter the 'linux ...' and 'initrd ...' commands and then 'boot'.

How can I get this guest to boot automatically?

Thanks,
Manas

**Comment by churchers** [comment]
Have a look at the latest version 0.10.
You'll need to change the guest type to `linux` in the configuration file.

When booted, the guest will stop at the boot loader. Use the `vm console` command to connect and enter the grub commands needed to boot successfully. Once you've (hopefully) found the commands that make it boot, add them to the configuration file:

    grub_run0="linux ..."
    grub_run1="initrd ..."
    grub_run2="boot"

**Comment by churchers** [comment]
Closing this for now

I got the arch iso to boot on `vm-bhyve-0.11` using the following configuration options. (Note that the linux line contains `201510` which is the date of the iso I had hanging around)

    grub_install0="linux /arch/boot/x86_64/vmlinuz archisobasedir=arch archisolabel=ARCH_201510 ro"
    grub_install1="initrd /arch/boot/x86_64/archiso.img"

It seemed to boot straight to a shell, and I didn't spend too long looking around for how to actually install it. Getting it to boot after install should just be a case of finding out the correct grub linux/initrd commands and setting them in the config via `grub_runX` options.

If arch installs its own grub2 config file, you should also be able to boot from that if you specify the correct partition to look on

    grub_run_partition="msdos1"
    grub_run_dir="/boot" (only needed if it's not /boot/grub)
    grub_run_file="grub.conf" (only needed if it's not grub.cfg)
