### ISSUE TITLE
config.sample questions

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#67]
config.sample contains this text
"This is a sample configuration file containing all supported options
Please do not try and use this for a guest"

If I am unable to use these configuration options for a guest, then what do I use it for? I assumed that config.sample showed all the options available for a guest?

**Comment by churchers** [comment]
The `config.sample` file shows all the available configuration options that can be used for guests, and gives a brief description.

That text is trying to tell you to not actually use the `config.sample` file itself as the configuration file for a guest. That file is only for information purposes and all the settings in it are just dummy examples.
