### ISSUE TITLE
vm install testvm does not work

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#68]
I have followed the instructions from the github page as well as making sure the vmm kernel module is loaded. I am unable to get a vm to install or booth any vm. The vms are created as I can see them in the output of "vm list".

When I run vm install testvm FreeBSD-10.2-RELEASE-amd64-disc1.iso nothing happens, no output and just get a new line.

Probably something stupid that I am doing but following your instructions exactly I have been unsuccessful.

**Comment by xerovis** [comment]
I have worked out what the issue was. I was using virtualbox, which bhyve doesn't seem to work on. This command happily works on an R710.

**Comment by churchers** [comment]
It's likely that VirtualBox isn't exposing the necessary CPU features for bhyve to work. I will look at improving the error reporting if a guest doesn't start although this is fairly low priority.

Also of use, there should be a `vm-bhyve.log` file inside the guest directory which contains more details of what `vm-bhyve` is doing and how far it got.
