### ISSUE TITLE
vm install test -> list available ISOs and be able to select

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#69]
Instead of having to know the exact filename, it would be great to be able to get a list of them.

**Comment by churchers** [comment]
The `vm iso` command can be used to list the available ISO files. I used to use this regularly then I would copy/paste the file I wanted into the install command.

If you are using the default `csh` or `tcsh` shell in FreeBSD, you should be able to use the auto-complete instructions at the bottom of the README on the GitHub project page. On my test system this auto completes all the `vm` commands, including ISO filenames.

**Comment by xerovis** [comment]
Thanks @churchers I will try this.
