### ISSUE TITLE
control D does not exit vm console

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#71]
I do not know what I am doing wrong but I have never been able to get control D to exit the vm console and get back to the host console.

**Comment by churchers** [comment]
Sometimes I find I have to try a couple of times before I can get back to the host. This is all handled by the `cu` program though so I don't really have any control over it.

If I get time I may look at the ability to use other terminal methods although it may not be worth the effort when `cu` is very simple and generally good enough.

**Comment by xerovis** [comment]
I have never been successful in getting back to the host. Best I have gotten is a login prompt for the guest.

**Comment by churchers** [comment]
Have you tried ~+Ctrl-D or ~+.
```
~^D or ~.
	     Drop the connection and exit.  Only the connection	is dropped -
	     the login session is not terminated.
```

**Comment by xerovis** [comment]
Going to do some more testing today, I will try this and report back.

**Comment by churchers** [comment]
Closing this

~ + Ctrl-D should exit the console. Although it does seem a bit tricky to get this to actually work sometimes, this is part of `cu` and not really an issue with vm-bhyve.

**Comment by kwinsch** [comment]
Whit an _US Keyboard_ layout on Windows 10, using putty to login, `~ ~ .` (`~^ ~^ .`) works fine for me.

In Ubuntu 20.20 LTS, using UEFI as the loader, I had to put the following settings in to _/etc/default/grub_ config file:
```
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8"

GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
```

For some reason this is not working with tmux. Could be simply some baut problem.
Also have a look  for files in _/etc/default/grub.d/*_ which could overwrite the settings above.
