### ISSUE TITLE
vm console test = all ports busy

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#72]
When this happens, how do I connect to the virtual machine?

**Comment by churchers** [comment]
Have you forcefully exited another console session or left one open? I've never seen this message in my testing, although I wouldn't be surprised to see this if there was already a `cu` process using the relevant `/dev/nmdm` device. Make sure there are no existing `cu` processes still running in your process list.

**Comment by xerovis** [comment]
It occurred because I was unable to leave the guest console using control D, so I had to close the window.

**Comment by xerovis** [comment]
I simply killed the cu process and did vm console test and it worked.
