### ISSUE TITLE
Clone of existing vm to use for other vms and be portable (send to other hosts)

### ISSUE THREAD

**Issue by xerovis** [churchers/vm-bhyve#74]
I would love to be able to have this function, though I am not 100% sure how to do this. I have looked at the man page and the clone function is there but it seems that its a zfs snapshot and not an image of the running machine that I can use vm install "cloneName" for. I guess I am not 100% sure how vm clone works and was hoping someone could help me out please?

**Comment by churchers** [comment]
You can try the `vm image` commands although these were thrown together just as a test and could probably do with a lot of work.

```
vm image create -d "some description" vmname
vm image list
```
(copy the compressed image and manifest file to new host)
```
vm image list
vm image provision {image-uuid} {new-vm-name}
```
