### ISSUE TITLE
error setting interface capabilities on lagg

### ISSUE THREAD

**Issue by agrman** [churchers/vm-bhyve#77]
Hi!
I did aggregation interfaces, and after a reboot is such an error appeared in the logs
Apr  1 14:16:39 vm2 kernel: bridge0: link state changed to UP
Apr  1 14:16:39 vm2 kernel: em0: promiscuous mode enabled
Apr  1 14:16:39 vm2 kernel: em1: promiscuous mode enabled
Apr  1 14:16:39 vm2 kernel: lagg0: promiscuous mode enabled
Apr  1 14:16:39 vm2 kernel: tap0:
Apr  1 14:16:39 vm2 kernel: Ethernet address: 00:bd:37:35:00:00
Apr  1 14:16:39 vm2 devd: Executing '/etc/pccard_ether tap0 start'
**Apr  1 14:16:39 # vm2 kernel: bridge0: error setting interface capabilities on lagg0**
Apr  1 14:16:39 vm2 kernel: tap0: promiscuous mode enabled
Apr  1 14:16:44 vm2 kernel: tap1:

But virtual machines (FreeBSD) work

vm switch list
NAME            TYPE       IDENT       VLAN      NAT          PORTS
public          auto       bridge0     -         -            lagg0

rc.conf

ifconfig_em0="up"
ifconfig_em1="up"
cloned_interfaces="lagg0"
ifconfig_lagg0="laggproto lacp laggport em0 laggport em1 x.x.x.x/x"

**Comment by churchers** [comment]
You say the virtual machines work but do you mean network connectivity is actually working?

It looks like there's something that the bridge is trying to set on the `lagg` interface that `lagg` doesn't support. I'll have to see if I can find some way of replicating it and narrowing down what's actually being done when that error is reported.

**Comment by danmeuk** [comment]
This is when it tries to remove features from the NIC, but the lagg interface can't do it (it doesn't seem to pass it back up to the physical NICs).

On my installation, I have to edit my /etc/rc.conf and apply "-tso4 -rxcsum -txcsum" on any NICs i use in the lagg.  This gets rid of the warning as it doesn't need to try to remove the options from the lagg :-)

The reason for that is that tap* interfaces don't support TSO or hardware checksum features.  It tries to remove them from the physical interface but laggs dont propagate.

**Comment by churchers** [comment]
Thanks for the information @danmeuk 

I don't think this is something I can very easily solve from vm-bhyve. I'm reluctant to start messing with user's physical interfaces, so this may be something users have to configure for themselves if they are in this situation.
