### ISSUE TITLE
How to Enable Autostart 

### ISSUE THREAD

**Issue by jstarcher** [churchers/vm-bhyve#81]
I'm not finding anything in the docks and the source code just shows listing if autostart is enabled. How does one actually enable it though?

**Comment by churchers** [comment]
HI @jstarcher 
Thanks for trying out vm-bhyve!

The options for autostart are mentioned in the GitHub readme, although maybe I should add a heading to make it stand out a bit more. It uses the `startall` command on boot, and the configuration is also described in the manpage under the `startall` command:

On host boot, vm-bhyve will use the 'vm startall' command to start all machines. You can
control which guests start automatically using the following variables in /etc/rc.conf:

    vm_list="vm1 vm2"
    vm_delay="5"

The first defines the list of machines to start on boot, and the order to start them. The second
is the number of seconds to wait between starting each one. 5 seconds is the recommended setting,
although a longer delay is useful if you have disk intensive guests and don't want them all booting
at the same time.

**Comment by jstarcher** [comment]
Many thanks! I'm not sure how I missed that in the readme, I read through it a few times too - sorry! Thanks for putting this tool together, I was using bhyve native commands for a while and thought it was pretty ugly and then I found vm-bhyve. This makes using bhyve so much more user-friendly!
