### ISSUE TITLE
Feature req: Ubuntu preseed

### ISSUE THREAD

**Issue by thnisweden** [churchers/vm-bhyve#82]
Would it be possible to use pressed sending something like this in the client.conf file?
guest="ubuntu"
cpu=1
memory=512M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
uuid="e1e4b448-3862-11e5-9df6-70106f3e6178"
grub_install0="linux /install/vmlinuz
file=/storage/vm/.preseed/ubuntu1604.seed quiet --
initrd /install/initrd.gz
boot"
grub_run0=""

This would simplify multiple installations a lot

Very good work with the vm-bhyve !!!!

/Thomas

**Comment by churchers** [comment]
I'm not sure exactly how the preseed works. Is that `file=` line part of the `linux ...` line, or a new line on it's own?

Either way, as long as this can be done through the grub loader, it should be possible through the vm-bhyve configuration file. You can specify multiple lines as follows:

    grub_install0="linux ..."
    grub_install1="file=(host)/storage/..."
    grub_install2="initrd ..."
    grub_install3="boot"

Basically you just want to find the commands that work in grub manually, then copy them into the guest configuation file. Note that in `0.11` or newer, you don't need the `boot` command in the guest config.

During install, we pass `(cd0)` as the root device, so commands like `linux /install/vmlinuz` will look on the cd for that file. The `(host)` device is also available, pointing to the bhyve host, so hopefully you can use `file=(host)/path/to/preseed/file/on/host` to point the preseed variable at your file.

Of course if you're on ZFS, you also have the option of creating a working guest, then using the `clone` command to make copies. You can also create an image of a guest and create independent copies using the `vm image create|provision` commands.
