### ISSUE TITLE
Upgrading from 0.12.3 to 1.0 results in VMs unable to be installed or restarted

### ISSUE THREAD

**Issue by unlateral** [churchers/vm-bhyve#83]
I am running 10.3-RELEASE on vm-bhyve 0.12.3 (from ports) and created several VMs on zvols successfully.  Here's an example relevant line from vm-bhyve.log for one of those VMs:

> Apr 22 16:42:01:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol/zroot/vm/logstash/disk0 -s 5:0,virtio-net,tap1,mac=(masked)]

I saw 1.0 was recently available in the ports tree and upgraded to it.  Now I am unable to go through the "vm install" process.  The relevant section of vm-bhyve.log for that VM looks like this:

> May 02 12:19:49: booting
> May 02 12:19:49: bhyveload -c /dev/nmdm6A -m 768M -e autoboot_delay=3 -d /zroot/vm/.iso/FreeBSD-10.3-RELEASE-amd64-bootonly.iso docs
> May 02 12:19:52:  [bhyve options: -c 2 -m 768M -AHP -U (masked)]
> May 02 12:19:52:  [bhyve devices: -s 0,hostbridge -s 31,lpc -s 4:0,virtio-blk,/dev/zvol//docs/disk0 -s 5:0,virtio-net,tap6,mac=(masked)]
> May 02 12:19:52:  [bhyve console: -l com1,/dev/nmdm6A]
> May 02 12:19:52:  [bhyve iso device: -s 3:0,ahci-cd,/zroot/vm/.iso/FreeBSD-10.3-RELEASE-amd64-bootonly.iso]
> May 02 12:19:52: starting bhyve
> May 02 12:19:52: bhyve exited with status 1

Clearly, the issue is that vm-bhyve is pointing the bhyve disk device to the wrong place (the "/dev/zvol//docs/disk0" above should actually be "/dev/zvol/zroot/vm/docs/disk0").

So, I am unable to create new VMs.  Can I reboot or restart them?  Turns out that doesn't work either...here's the vm-bhyve.log from the first VM:

> May 02 12:34:55: initialising
> May 02 12:34:55:  [guest: freebsd]
> May 02 12:34:55:  [loader: bhyveload]
> May 02 12:34:55:  [uefi: no]
> May 02 12:34:55:  [cpu: 2]
> May 02 12:34:55:  [memory: 768M]
> May 02 12:34:55:  [hostbridge: standard]
> May 02 12:34:55:  [com ports: com1]
> May 02 12:34:55:  [uuid: (masked)]
> May 02 12:34:55:  [utctime: no]
> May 02 12:34:55:  [debug mode: no]
> May 02 12:34:55:  [primary disk: disk0]
> May 02 12:34:55:  [primary disk dev: sparse-zvol]
> May 02 12:34:55: initialising network device tap1
> May 02 12:34:55: adding tap1 -> bridge0 (public)
> May 02 12:34:55: booting
> May 02 12:34:55: bhyveload -c /dev/nmdm1A -m 768M -e autoboot_delay=3 -d /dev/zvol//logstash/disk0 logstash
> May 02 12:34:55: loader returned error 64

I haven't changed any rc.conf settings during this time... the vm-related settings are still set to:

> vm_delay: 5
> vm_dir: zfs:zroot/vm
> vm_enable: YES

I took a few glances through the code, particularly at vm-zfs and vm-run in the lib directory, but I'm not seeing anything that pops out at me as a problem.  So it gets filed as an issue instead of a pull request -- sorry about that.  :)

**Comment by churchers** [comment]
Thanks for raising this issue. It looks like a serious bug has found it's way into ZFS support in 1.0
Can you try making the following changes in [file]/usr/local/lib/vm-bhyve/vm-core[/file] around line 400.
(Basically removing the `-d ${vm_dir}` option.)
```
-        $0 -fd "${vm_dir}" _run "${_name}" "${_iso}"
 +        $0 -f _run "${_name}" "${_iso}"
      else
 -        $0 -d "${vm_dir}" _run "${_name}" "${_iso}" >/dev/null 2>&1 &
 +        $0 _run "${_name}" "${_iso}" >/dev/null 2>&1 &
```
If this fixes it for you I'll need to push an update to ports asap.

**Comment by churchers** [comment]
This seems to fix it for me.
Looks like a last minute bug fix to the `-d` option (alternate vm location) in 1.0-stable caused the ZFS dataset to be handled incorrectly.

I've submitted an update to ports, hoping it makes it in before the next package build is run. I just hope the next quarterly package build doesn't happen first.

**Comment by unlateral** [comment]
Sorry, I just saw this.  I'll check your change on my system in the next hour and report back.  Thanks for looking into it so quickly!

**Comment by unlateral** [comment]
Made the change to the two lines that you outlined, and things have returned to expected behavior - the existing VM started, and I was able to initiate the install of the other one.

**Comment by churchers** [comment]
Thanks for raising it. God knows when I would of spotted it otherwise, I've been mainly working on 1.1. I just hope this is one of the occasions where my ports bug is picked up within a few hours rather than a week.

**Comment by churchers** [comment]
Reopening this until the 1.0 package is no longer available.
Sorry to anyone who experiences this problem. If you do, please remove the package and install the latest port.

````
# pkg delete vm-bhyve
# portsnap fetch update (or extract if first time)
# cd /usr/ports/sysutils/vm-bhyve
# make install clean
```

**Comment by churchers** [comment]
Closing this for now. Latest packages have been up to date for quite a while.
The latest port (`1.0-p4`) was supposed to be merged into the 2016Q2 quarterly branch, but for some reason they have only merged the `pkg-descr` file and nothing else, so that is stuck at 0.9.13.

I'm expecting the next quarterly branch to include 1.0-p4, so while most users are having to unfortunately make do with a very old version at the moment (FreeBSD defaults to quarterly branch), they should go straight to a fully patched version when the packages are finally updated.
