### ISSUE TITLE
Custom bhyve options

### ISSUE THREAD

**Issue by jgillich** [churchers/vm-bhyve#88]
By default, a VM occupies all assigned cores, so I'd like to set `-H`:
```
     -H		 Yield the virtual CPU thread when a HLT instruction is
		 detected.  If this option is not specified, virtual CPUs will
		 use 100% of a host CPU.
```
But there's no way to set a custom option, right?

**Comment by churchers** [comment]
We always specify `-AHP` for normal guests, and `-Hw` for UEFI (based on bhyve developer docs). I should probably make these configurable at some point but it's so rare that people don't want these options that I'd had no problem with having these hard coded so far.

You can look in the `vm-bhyve.log` file to see the exact bhyve command that is being run.

**Comment by jgillich** [comment]
Interesting. My CPUs look like this:

![](http://i.imgur.com/8qYyham.png)

This is not normal, right? According to `vm-bhyve.log`, `-H` is set, so maybe it's not supported on my hardware or something.

**Comment by churchers** [comment]
Strange, I'm not aware of any hardware-specific issues which would cause 100% cpu usage.
What are you using to display that CPU usage?

I currently have a Win2012 & FreeBSD guest running (both just idling really) and cpu usage looks normal on the host:

```
CPU 0:  0.0% user,  0.0% nice,  0.0% system,  0.0% interrupt,  100% idle
CPU 1:  0.0% user,  0.0% nice,  0.4% system,  0.0% interrupt, 99.6% idle
CPU 2:  0.0% user,  0.0% nice,  0.8% system,  0.0% interrupt, 99.2% idle
CPU 3:  0.0% user,  0.0% nice,  0.0% system,  0.0% interrupt,  100% idle

49117 root        20    0  2091M  1010M vmidle  3  15:56   0.56% bhyve{vcpu 0}
58229 root        20    0   286M 23352K vmidle  3   0:06   0.23% bhyve{vcpu 0}
49117 root        20    0  2091M  1010M vmidle  0   7:17   0.20% bhyve{vcpu 1}
58229 root        20    0   286M 23352K vmidle  0   0:04   0.09% bhyve{vcpu 1}
```

49117 is my Windows guest and 58229 is FreeBSD.

**Comment by jgillich** [comment]
Ha, it was htop, and that [seems to be a bug](https://github.com/hishamhm/htop/issues/456). top shows 
```
CPU:  0.6% user,  0.0% nice, 23.6% system,  0.0% interrupt, 75.8% idle
```
Thanks for the help!
