### ISSUE TITLE
Enabling switch

### ISSUE THREAD

**Issue by carriercomm** [churchers/vm-bhyve#89]
[root@edge1 /home/khatfield]# vm switch nat public on
******
  NAT has been enabled on the specified switch
  A sample dnsmasq configuration has been created in /usr/local/etc/dnsmasq.conf.bhyve
  To enable DHCP on this switch, please install the dnsmasq confguration or merge with your existing.
******
/usr/local/sbin/vm: _config_core_get: not found

Unsure what this means?

**Comment by carriercomm** [comment]
Also,
 I have noticed if I do a 'shutdown -h now' for example, in CentOS, it will show locked. Therefore, it is not deleting the /dev/vmm/centos file. Unsure why this is happening as well.

**Comment by carriercomm** [comment]
Another issue -

Unable to delete a switch or remove it's members. For some reason my switch is showing an "ident: -"

------------------------
Virtual Switch: public
------------------------
  type: auto
  ident: -
  vlan: -
  nat: -
  physical-ports: - bce1
  bytes-in: 0 (0.000B)
  bytes-out: 0 (0.000B)

**Comment by churchers** [comment]
Does `shutdown -h` actually power off the machine? On FreeBSD `-h` just halts the system, I usually use `shutdown -p now` to get the system to go off completely. I'm not really a Linux user, but on my test vm's I use `poweroff`.

The problems with your virtual switch are possibly related to the `_config` errors you got. To remove it manually just edit `/my/vm/path/.config/system.conf` (v1.1+) or `/my/vm/path/.config/switch` (v1.0). Remove the switch from `switch_list` and any other settings that reference `public` in the name.

If you're using the master version from GitHub (v1.1), pull the latest version to get @jkni's fix.

**Comment by carriercomm** [comment]
Excellent.
Thanks so much!
