### ISSUE TITLE
Dirty way to insert the drivers disc for windows after installation.

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#92]
I can't find a simple way to let Windows have a virtio driver disc.
the config file cannot support ahci-cd.
Finally, the simplist way is replace null.iso with driver iso.

**Comment by churchers** [comment]
Hmm, I hadn't thought about getting the virtio-net drivers into a guest. I'll have to think of the best way to make the virtio drivers available.

It is however possible to provide an additional `ahci-cd` device to the guest using the existing configuration options. I haven't fully tried this during a Windows install but have tested mounting a CD as an extra device in an existing Windows guest.
```
disk1_type="ahci-cd"
disk1_dev="custom"
disk1_name="/path/to/my/cd.iso"
```

**Comment by churchers** [comment]
I'm going to close this issue for now.

As mentioned above, it is possible to add a custom ISO to the guest using the `ahci-cd` emulation. It would be nice to have some specific `cdrom0` etc config options, but it's not really worth it when the disk options already cover it.

There's also a small 'hack' you can use to provide the virtio driver ISO to the guest once the OS has been installed:

    vm stop winguest
    vm iso http://path.to.the/virtio/installer/iso
    vm install winguest virtio-installer.iso

This starts it in normal installation mode with the virtio-net ISO in the first cdrom drive. Obviously it won't boot of the virtio ISO, so boots off the OS disk.

I will update the Windows wiki page shortly to include a bit more information and cover some of the recent improvements in bhyve/vm-bhyve. Unfortunately at the moment the functionality can vary quite a lot depending on the version of FreeBSD and vm-bhyve you are using. (Just between ports/pkg & github there are currently 3 noticeably different versions of vm-bhyve available)
