### ISSUE TITLE
fatal; pci passthrough not supported on this system (no VT-d)

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#93]
My machine support VT-D and already enabled.

```
root@fbsd11:/zones/vm/win2012 # acpidump -t |grep DMAR
  DMAR: Length=120, Revision=1, Checksum=30,
```

if I comment out the ```__check_bhyve_iommu``` in ```vm-run``` it works. and vm can have the vt-d device.

**Comment by churchers** [comment]
Hi

Can you try the latest commit. Inside the function I run `test` (`[`) to see if the `acpidump` output is blank. If this test succeeds (we can't find the DMAR table), the code returns an error code.

However, if the test failed, I wasn't returning an explicit success `0` code, so the function was returning the result of the `test` call, which was a fail.

Hopefully this explicit `return 0` should fix it.

**Comment by WanpengQian** [comment]
I confirmed it works.
