### ISSUE TITLE
How to display vm's snapshot?

### ISSUE THREAD

**Issue by WanpengQian** [churchers/vm-bhyve#97]
I can't find a command to show vm's snapshot. 
currently I use `zfs list -t snapshot | grep vmname` to do it.

It will be better integrate a command to show vm's snapshot. 
such as

```
vm list -t snapshot
```

**Comment by rayddteam** [comment]
Add
                echo "  Snapshots:"
                zfs list -rt snapshot "${_path#/dev/zvol/}" | sed "s/^/${_INDENT}/"
                echo "  Origin:"
                zfs get -r origin "${_path#/dev/zvol/##/[^/]}" | sed "s/^/${_INDENT}/"
inside "info::guest_disks()" /usr/local/lib/vm-bhyve/vm-info
